### ISSUE TITLE
Owner and Group Always Set to 0 ("root")

### ISSUE THREAD

**Issue by elasticdog** [kelseyhightower/confd#115]
I'm running confd v0.5.0 on an Ubuntu 14.04 LTS host and am having trouble with altering the owner and group for a template...no matter what I do, it changes things to be owned by the root user and root group, which is not desirable.

**/etc/confd/conf.d/example-json.toml**
```TOML
[template]
src = "example.json.tmpl"
dest = "/etc/example.json"
owner = "elasticdog"
group = "elasticdog"
mode = "0644"
keys = [
  "/jdbc_url",
]
reload_cmd = "/sbin/reload example-server"
```
...and it's creating the file with the desired contents, but the permissions are always set back to 0:

```
$ ls -l /etc/example.json
-rw-r--r-- 1 root root 1011 Aug  7 04:54 /etc/example.json
$ id elasticdog
uid=999(elasticdog) gid=999(elasticdog) groups=999(elasticdog)
$ sudo chmod elasticdog:elasticdog /etc/example.json
$ sudo reload confd
```
**/var/log/upstart/confd.log**
```
2014-08-07T04:54:21Z ip-10-193-17-174 /usr/local/bin/confd[2404]: INFO /etc/example.json has UID 999 should be 0
2014-08-07T04:54:21Z ip-10-193-17-174 /usr/local/bin/confd[2404]: INFO /etc/example.json has GID 999 should be 0
```

**Comment by popsikle** [comment]
+1 to not changing uid:gid unless specified.

**Comment by crandles** [comment]
What about executing `id $username` or `getent group` (if they exist) (`dscacheutil -q group` on osx)? Is it too much a stretch to assume they exist?

**Comment by kelseyhightower** [comment]
We have a solution for this on master. https://github.com/kelseyhightower/confd/commit/6354ddd43eb8589fea16805e935ecdf9491fb7a6

The rules for this are as follows:

If the uid or gid is not set then use the effective uid or gid for the confd process owner. We will no longer default to uid or gid.

**Comment by zeyuye-airwallex** [comment]
does the below work 😄 

```toml
owner = "user"
group = "user"
```

i'm following the docs https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md#create-template-resources

it uses `mode="nginx"`, however during my experimentation, the destination file permission is root:root

below is my example

`/etc/confd/conf.d/consul.toml`
```bash
root@iZp0w71s9grno2wfitjltjZ:/etc/confd# cat /etc/confd/conf.d/consul.toml 
# generated by root (Tue 24 Apr 2018 16:08:22 AEST) using ansible
[template]
src = "agent.json.tmpl"
dest = "/etc/consul.d/agent.json"
owner = "consul"
#group = "consul"
mode = "0640"
check_cmd = "/usr/bin/consul validate --config-format=json /etc/consul.d"
reload_cmd = "/usr/bin/consul reload"
```

```bash
root@iZp0w71s9grno2wfitjltjZ:/etc/confd# confd -onetime
2018-04-24T14:10:40+08:00 iZp0w71s9grno2wfitjltjZ confd[11688]: INFO Backend set to consul
2018-04-24T14:10:40+08:00 iZp0w71s9grno2wfitjltjZ confd[11688]: INFO Starting confd
2018-04-24T14:10:40+08:00 iZp0w71s9grno2wfitjltjZ confd[11688]: INFO Backend source(s) set to 127.0.0.1:8500
```
file permission on `/etc/consul.d/agent.json`
```bash
root@iZp0w71s9grno2wfitjltjZ:/etc/confd# ls -lah /etc/consul.d/agent.json 
-rw-r----- 1 root root 252 Apr 24 14:10 /etc/consul.d/agent.json
```

**Comment by vkakhnych** [comment]
Is there a strong reason why discussed option still doesn't work?
Running confd process with other owner is not always helpful. One confd process has to change different configs ownership in my case:
nginx templates to nginx user, logstash configs to logstash user, etc. Thus I have to run it as root.
Using UID/GID is also not always works. It turned out that nginx and logstash in my case could have different values on different instalations.
Thanks!

**Comment by hubo1016** [comment]
@vkakhnych I would suggest using a check script which calls `chown` as a hack :(

**Comment by vkakhnych** [comment]
thanks, but check script will not help - config doesn't exist on that stage. I'm using reload script for workaround.
Still wonder why authors didn't implement the same for owner.
