### ISSUE TITLE
prefix is required in toml file however it does not interpolate env variables

### ISSUE THREAD

**Issue by bfosberry** [kelseyhightower/confd#131]
Im namespacing config behind an id, so my execution looks like this:

```
confd -verbose -onetime -node "http://$ETCD_SERVER" -confdir /opt/server/confd/ -prefix="/_$SERVER_ID/config/
```

Lets say there is a value at /_$SEVER_ID/config/mykey = myvalue

If I want to write a template

```
key {{ .mykey }}
```

my toml file needs to look like this:

```
[template]
src = "server.cfg.tmpl"
dest = "/opt/server/cfg/server.cfg"
keys = [
  "/_$SERVER_ID/config/mykey"
]
```

Ideally I could just place "mykey" into the keys array, however, I could not get that to work with the prefix.

The problem is that the toml file does not interpolate env variables, so I'll have do sed replace $SERVER_ID in the file before using it :(

**Comment by fruch** [comment]
:+1:
I'm looking for the exact same thing.
We have multiple version of our app, and I want each to have its own set of keys. Without resorting to very complex template scripting.

Yea sed is easy enough, be having this baked into confd seems like clear solution maybe a .toml.tmpl file that only works with getenv.
