### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gozer** [kelseyhightower/confd#180]
I am seeing this with confd 0.7.1 from time to time, during what appears to be a watch waiting period.

$> confd -backend=consul -watch=true -node=127.0.0.1:8500 -verbose=true -debug=true -prefix="/production"

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ff627]

goroutine 63 [running]:
runtime.panic(0x72b9c0, 0x942bd3)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/kelseyhightower/confd/backends/consul.func·001()
        /Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/backends/consul/client.go:56 +0xe7
created by github.com/kelseyhightower/confd/backends/consul.(*Client).WatchPrefix
        /Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/backends/consul/client.go:57 +0x121

goroutine 16 [select, 5 minutes]:
main.main()
        /Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/confd.go:50 +0x7d0

goroutine 19 [finalizer wait, 5 minutes]:
runtime.park(0x415d70, 0x9476c8, 0x945949)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x9476c8, 0x945949)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 5 minutes]:
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [semacquire, 5 minutes]:
sync.runtime_Semacquire(0xc208000f48)
        /usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc208052070)
        /usr/local/go/src/pkg/sync/waitgroup.go:129 +0x14b
github.com/kelseyhightower/confd/resource/template.(*watchProcessor).Process(0xc208052000)
        /Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/resource/template/processor.go:88 +0x1ad
created by main.main
        /Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/confd.go:46 +0x466

goroutine 22 [select]:
github.com/kelseyhightower/confd/backends/consul.(*Client).WatchPrefix(0xc208034048, 0x0, 0x0, 0x1d2b, 0xc208004300, 0x1d2b, 0x0, 0x0)
        /Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/backends/consul/client.go:59 +0x21e
github.com/kelseyhightower/confd/resource/template.(*watchProcessor).monitorPrefix(0xc208052000, 0xc208026600)
        /Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/resource/template/processor.go:94 +0xcb
created by github.com/kelseyhightower/confd/resource/template.(*watchProcessor).Process
        /Users/kelseyhightower/go/src/github.com/kelseyhightower/confd/resource/template/processor.go:86 +0x166

**Comment by bacongobbler** [comment]
ping @gozer

**Comment by bacongobbler** [comment]
closing for now as there hasn't been any activity for quite some time, but please feel free to re-open if you get back with a reproducible test case or something which we can follow up with. Thanks!
