### ISSUE TITLE
confd exiting without explanation

### ISSUE THREAD

**Issue by gregsymons** [kelseyhightower/confd#182]
When I run confd 0.7.1 , it loads its configuration, and then promptly exits with no message and a 0 exit code. The config and sample output can be found in [this gist](https://gist.github.com/gregsymons/56410a35186be7cdedbd).

I'm a total Go noob, so after reading the code, I don't fully understand how this could happen.

**Comment by gregsymons** [comment]
After mucking around some more, I changed all the lines in my `zoo.cfg.toml` to have initial caps, and it started "working" (I had a syntax error in the template that got reported properly). However, all the examples have the lines in all-lowercase. Is this a code bug or a documentation bug?

**Comment by bacongobbler** [comment]
@gregsymons can you supply a reproducible failure case so we can confirm and test against it?

**Comment by gregsymons** [comment]
Oops... had the wrong URL for the gist. You can find it [here](https://gist.github.com/gregsymons/56410a35186be7cdedbd).

**Comment by gregsymons** [comment]
I'll add the working config file later tonight; I don't have access to it at the moment.

**Comment by bacongobbler** [comment]
Given [the following files](https://gist.github.com/bacongobbler/aa166632d66756d70363), I was able to reproduce this, though I think it's a limitation of `getv` being unable to determine if $server is a variable or a literal string.

```
2015-01-13T23:39:36-08:00 mutalisk ./confd[18735]: ERROR template: zoo.cfg.tmpl:7:12: executing "zoo.cfg.tmpl" at <getv "/servers/$serv...>: error calling getv: key does not exist
```

**Comment by gregsymons** [comment]
@bacongobbler I think you've created a new issue. If you use [this file](https://gist.github.com/gregsymons/56410a35186be7cdedbd#file-working_zoo-cfg-toml) with the rest of the configuration in my gist, it works fine.

**Comment by gregsymons** [comment]
Though now that I think of it, I hadn't actually gotten as far as you did and actually put servers under the servers key... I'll have to see what happens.

**Comment by gregsymons** [comment]
Yeah... I'm seeing the same problem with getv now.

**Comment by bacongobbler** [comment]
@gregsymons my files are just a few tweaks such that I could use the integration tests but essentially it's the same keys/values, just under different keyspaces.

**Comment by gregsymons** [comment]
Yeah, the getv thing was definitely me not understanding how interpolation works. I made it work by using a pipeline: `{{ printf "/servers/%s/host" $host | getv }}`. The case sensitivity in the toml file though seems weird, because the integration tests all use lower case just like the documentation.

**Comment by kelseyhightower** [comment]
@bacongobbler @gregsymons Maybe we should update the docs here to make this more clear.

**Comment by kelseyhightower** [comment]
I've just pushed a couple of commits that should improve the error handling in confd to output errors and exit non-zero in all error cases.
