### ISSUE TITLE
function "exists" not defined

### ISSUE THREAD

**Issue by bcicen** [kelseyhightower/confd#184]
I'm attempting to use one of the patterns in the docs, but getting the error:
```
panic: template: haproxy.tmpl:26: function "exists" not defined
```
relevant code:
```
{{if exists "/my/testkey"}}
frontend mytest
{{end}}
```

**Comment by jeff-johnston** [comment]
I had this issue when using 0.6.3 as the exists function does not exist in 0.6.3 - this went away when I pulled down the latest binary version 0.7.1.

**Comment by bcicen** [comment]
Great; have it working now. Thanks!
