### ISSUE TITLE
confd processes all files in /etcd/confd/conf.d

### ISSUE THREAD

**Issue by DixonsBrnoDevs** [kelseyhightower/confd#185]
I'm not sure if I'm missing something, but when I run:

     confd -onetime -node $ETCD -config-file /etc/confd/conf.d/backends-apache.toml

confd processes also other files in /etc/confd/conf.d (e,g.: backends-f5.toml). The problem is that both configurations creates same file /etc/varnish/backends.vcl. Is this correct behaviour?

**Comment by kelseyhightower** [comment]
@DixonsBrnoDevs Yes, this is by design. You can create more than one confdir if you want to only generate one set of templates at a time.
