### ISSUE TITLE
Optional ranges for dynamic nginx proxy-ing multiple services.

### ISSUE THREAD

**Issue by jeff-johnston** [kelseyhightower/confd#187]
We have an application where we want to proxy multiple services dynamically based on etcd keys. At any given time the etcd keys may exist for one service but not the other. When not all keys are present one of the following tmpl blocks will fail and no configuration gets written so no service gets proxied. I tried using the 'exists'  but it does not seem to handle wildcards. Inside the poolone directory will be a hostname/ip which won't be known by anyone but the service itself. These blocks work fine when all the keys are present but we would like to write an empty block for any pool that does not have any keys yet. Is there a way to accomplish this?

upstream pool-one {
{{ range $server := getvs "/services/hosts/poolone/*" }}
    server {{ $server }};
{{ end }}
}

upstream pool-two {
{{ range $server := getvs "/services/hosts/pooltwo/*" }}
    server {{ $server }};
{{ end }}
}

Thanks...

**Comment by bacongobbler** [comment]
@jeff-johnston there's an example in the integration test suite: https://github.com/kelseyhightower/confd/blob/master/integration/confdir/templates/iteration.conf.tmpl#L1-L5

**Comment by jeff-johnston** [comment]
Than you. While the "gets" in that pattern works also "if" all the configuration is set for both pools. It still fails and the template never gets written to destination if the in my test case there are etcd keys for poolone but no etcd keys for pooltwo. The problem isn't retrieving the values - the problem is that if no values exist confd won't keep going which is what we need to happen. Is there any way around that?

**Comment by flantel** [comment]
On 12 January 2015 at 21:35, jeff-johnston <notifications@github.com> wrote:

> Than you. While the "gets" in that pattern works also "if" all the
> configuration is set for both pools. It still fails and the template never
> gets written to destination if the in my test case there are etcd keys for
> poolone but no etcd keys for pooltwo. The problem isn't retrieving the
> values - the problem is that if no values exist confd won't keep going
> which is what we need to happen. Is there any way around that?
>
>
Hi Jeff,

Here is a snippet that I use for haproxy which I think does what you need.
I use "if ls /resource" to test if the key exists, and do a gets, otherwise
I write out a dummy line.

{{ if ls "/servers/pbxadmin"}}{{range gets "/servers/pbxadmin/*"}}server {{
base  .Key }} {{.Value}} cookie {{ base .Key}} check
{{end}}{{else}}server dummy 127.0.0.1:88888 backup{{end}}


Hope this helps.


-Barry Flanagan

**Comment by bacongobbler** [comment]
I think @flantel's snippet solves this problem quite nicely.

@jeff-johnston does that work for you?

**Comment by jeff-johnston** [comment]
Yes I was able to get this working using the conditional if approach. Problem solved. Thx
