### ISSUE TITLE
how can I create a tmpl file  through confd ？

### ISSUE THREAD

**Issue by OnSnail** [kelseyhightower/confd#188]
I want to auto create a file "/etc/confd/templates/zookeeper.sh.tmpl",  Can you help me ?

data stored in etcd looks like this:
$etcdctl get /zookeeper/zookeeper01
1

my toml file is:
$ cat /etc/confd/conf.d/zookeeper.sh.tmpl.toml
[template]
src = "zookeeper.sh.tmpl.tmpl"
dest = "/etc/confd/templates/zookeeper.sh.tmpl"
keys = [
    "/zookeeper",
]

I want the dest file "/etc/confd/templates/zookeeper.sh.tmpl"  to be：
$cat /etc/confd/templates/zookeeper.sh.tmpl
MYID={{ getv "/zookeeper/zookeeper01" }}

How can I write the "/etc/confd/templates/zookeeper.sh.tmpl.tmpl" to auto create "/etc/confd/templates/zookeeper.sh.tmpl" above? Can "zookeeper01" will be set by  a variable ?

I tried :
{{ $zk := ls "/zookeeper"}}
MYID=\\{\\{ getv "/zookeeper/{{index $zk 0 }}/1"  \\}\\}

 However the result is : 

MYID=\\{\\{ getv "/zookeeper/zookeeper01/1"  \\}\\}

How can I  get     MYID={{ getv "/zookeeper/zookeeper01/1"  }}  otherthan MYID=\\{\\{ getv "/zookeeper/zookeeper01/1" \\}\\}?

thanks~

**Comment by bacongobbler** [comment]
I'm not quite sure I understand. You want confd to use a template to write out a template? You could run two separate confd processes, each with their own confdir but I'm not sure how well that will go.

**Comment by kelseyhightower** [comment]
OnSnail It seems you want to store the template in etcd and have confd process it from there?

**Comment by kelseyhightower** [comment]
Closing for now as this type of feature is out of scope for confd.
