### ISSUE TITLE
'if exists' broken?

### ISSUE THREAD

**Issue by swat30** [kelseyhightower/confd#189]
Running into an issue with 'if exists' and how unset keys are handled. 

Here is the behavior I'm seeing:
* Key is set in etcd AND key is defined in conf file, 'if exists' works (returns true)
* Key is not set in etcd AND key is defined in conf file, `confd -onetime` errors: `ERROR 100: Key not found (/key) [220]`
* Key is not set in etcd AND key is not defined in conf file, 'if exists' seems to work (returns false)
* Key is set in etcd AND key is not defined in conf file, 'if exists' doesn't work (returns false)

It seems that there is a bit of chicken and egg going on. The key must be defined in the conf file, however if it is, it must exist. So, there's no way to have a defined key not exist, or an undefined key exist.

**Comment by bacongobbler** [comment]
That's confd's intentional behaviour. It only has knowledge of the resources you provide in your template resource config. If it's defined, then it expects those keys, otherwise they're ignored. However, you don't need to define every key you want to template out. You can specify a directory instead:

```
keys = [
    "/database"
]
```

and in your config:

```
{{ if exists "/database/foo" }}hello world!{{ end }}
{{ getv "/database/bar" }}
```

Is there something I'm missing here?

**Comment by swat30** [comment]
Thanks for your help! That does indeed work for my use case.

What about a case where one does not want to monitor a directory? Say the key is in the root, and you don't require every key. Would it be valid to have an "optional_keys" list, where confd will use them if they exist, and ignore them if they do not?

Maybe I'm way off base, but it would certainly make config files more descriptive, and probably more optimal :). Just my $0.02.

**Comment by kelseyhightower** [comment]
@swat30 confd assumes that keys live in the right directories. You can also provide as many "root" directories to help filter which keys confd tries to pull.

**Comment by swat30** [comment]
Makes sense @kelseyhightower. Was just throwing that out there for the sake of discussion really!

Thanks
