### ISSUE TITLE
Support for pongo2

### ISSUE THREAD

**Issue by analytically** [kelseyhightower/confd#190]
I'd be great if we could have templates that are more 'functional', like eg. https://github.com/flosch/pongo2

**Comment by bacongobbler** [comment]
@analytically confd is a wrapper around Go's text/template package, so functional changes like how Go handles its templating language would have to be made upstream.

As far as feature set, the text/template language (along with some convenience functions supplied by confd) can do the same, more or less:

```
{{ range gets "/users/*" }}
{{ $user := json .Value }}
{{ if user.Karma == 40 }}{{user}}{{end}}
{{end}}
```

pongo is meant to deal with Django templates so it's going to have more "convenience" functions geared towards Django. Is there something specifically missing from pongo which you require?

**Comment by thomascramer** [comment]
I think supporting pongo2 would be *huge* and I brought it up in my issue #197 that it would deal well with.  Go's text/template is very "simplistic" and while it offers a lot of ability to build the foundation of a templating engine, I wonder if confd really should really head down that road.  There have already been several template functions added to the function map for text/templates to allow for functionality that was already in pongo2... I think that leveraging a full featured template engine would really "super charge" confd.


Anyway, this request gets a big "+1" from me..

**Comment by kelseyhightower** [comment]
@analytically Thanks for the request. I've taken some time to review pongo2, and it looks great, but my goal is to keep confd really simple and the golang template package works well here. My hope is that people soon move away from config files and use something like etcd in the future.

**Comment by tboerger** [comment]
I think a template engine like pongo got a lower barrier for non-golang developers. I would love to have this instead of the simple but quite easy ugly template files. To switch everything to etcd is a big dream :)

**Comment by kelseyhightower** [comment]
@tboerger I agree, the golang templates do have their limits, but at this point that's what confd supports. I'm open to people forking confd and adding support for pongo. I see confd as only one way to do it.
