### ISSUE TITLE
Combine env backend with consul/etcd?

### ISSUE THREAD

**Issue by analytically** [kelseyhightower/confd#192]
Is is possible to combine backends?

**Comment by bacongobbler** [comment]
No. [Only one backend](https://github.com/kelseyhightower/confd/blob/0b0d0aa15df8709824cc74db386e8ad4e8f6bc6a/backends/client.go#L21) can be chosen at a time.

**Comment by bacongobbler** [comment]
however, there is limited support for both if you set your backend as etcd or consul and use `getenv` to retrieve keys from your environment: https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#getenv

Would that solve your use case?

**Comment by kelseyhightower** [comment]
@analytically Looks like @bacongobbler answered your question so I'm closing this out.
