### ISSUE TITLE
Checking a key exists and that it is set to a value

### ISSUE THREAD

**Issue by thomascramer** [kelseyhightower/confd#197]
I posted this question to the mailing list and irc channel and haven't gotten much of response. 

I'm trying to check that a key exists and that it is set to a value.  However in go templates it looks like both expressions get processed in a condition instead of stopping if the first part fails.  So something like `{{ if and ( exists "/app/admin") ( eq (getv "/app/admin") "private")  }}` fails if the key "/app/admin" doesn't exist because it is still trying to process the second expression.  Obviously I could cascade or embed the expressions `{{ if  exists "/app/admin" }} {{ if eq (getv "/app/admin") "private"  }}` but that gets rather lengthy, especially in an if/else situation you have to do:  `{{ if  exists "/app/admin" }} {{ if eq (getv "/app/admin") "private"  }}foo{{ else }}bar{{ end }}{{ else }}bar{{ end}}` which starts making your template unreadable.  

Is there a better way of doing this?  Or do I need to open a feature request to confd?  This seems fairly standard in many of our templates so surprised this isn't the default...

**Comment by lordelph** [comment]
I have a similar issue - I have an etcd directory `/foo/web`, and webservers write keys under that containing their ip and port. I have a template that writes an nginx config like this

    {{range getvs "/foo/web/*"}}
        server {{.}};
    {{end}}

If there are no webservers, confd will abort the attempt with "error calling getvs: no keys match". How can I tell if `/foo/web/` contains any keys to avoid the error?

**Comment by flantel** [comment]
On 6 February 2015 at 18:46, Paul Dixon <notifications@github.com> wrote:

> I have a similar issue - I have an etcd directory /foo/web, and
> webservers write keys under that containing their ip and port. I have a
> template that writes an nginx config like this
>
> {{range getvs "/foo/web/*"}}
>     server {{.}};
> {{end}}
>
> If there are no webservers, confd will abort the attempt with "error
> calling getvs: no keys match". How can I tell if /foo/web/ contains any
> keys to avoid the error?
>
>
Try:

{{if ls "/foo/web"}}

{{range getvs "/foo/web/*"}}
    server {{.}};
{{end}}

{{end}}


Hope this helps.


-Barry Flanagan

**Comment by lordelph** [comment]
Thanks - that's useful to know. I actually solved my problem using `ls` directly for the range, which doesn't throw an error on empty directories

    {{range ls "/foo/web/"}}
        server {{.}};
    {{end}}

**Comment by analytically** [comment]
We used

```
    {{range $serverkey := ls "/services/http/api"}}
    {{ $serverip := printf "/services/http/api/%s" $serverkey}}
    server {{$serverkey}} {{getv $serverip}}:3000 check inter 1000
    {{end}}
```

**Comment by swynter-ladbrokes** [comment]
We had /prelive/{service}/{port}/{host}

```
{{ range $d := ls "/prelive" }}{{ if eq $d "appserver" }} {{ if gt ( len ( ls "/prelive/appserver" ) ) 0 }}{{ range getvs "/prelive/appserver/9000_tcp/*" }}    server {{ . }};
{{ end }}{{ end }}{{ end }}{{ end }}
```

Note that the if gt (len...) could be written like range $d := l...

**Comment by thomascramer** [comment]
I have been watching, but a lot of the suggestions seems to be around about dealing with a series of keys (i.e. range and ls) and I really just want to say `if "/foo/blah" exists and "/foo/blah" == "bar"` then do...  I know I could easily do that with jinja templating.  It looks like there is a similar package in go called pongo2 (https://github.com/flosch/pongo2) which seems far more robust then the simple go templates...

**Comment by bacongobbler** [comment]
closing as this question seems to have been solved.

**Comment by hookenz** [comment]
@thomascramer - I agree, go templates are pretty limited.  I prefer mustache myself.
