### ISSUE TITLE
Get the last KV pairs of a hierarchy

### ISSUE THREAD

**Issue by AlessandroEmm** [kelseyhightower/confd#199]
hey there

I'm currently trying to get confd to run between skydns entries in etcd and haproxy.
For achieving that I'd like to list all hosts(hostnames) that have been registered in a network.

SkyDNS structures its data like:
Key /skydns/FQDN-Part/FQDN-Part/servicename and its Value is the actual IP address

So my question is whether I can just omit the FQDN Part and just access the key at the end.
Something like ' ls "/skydns/\*/\*/" ' Is that possible or what would be the approach to this?

Thanks!
Alessandro

**Comment by wkruse** [comment]
It is probably an `etcd` issue. It is posible to get all keys/values in `etcd` recursively:

(**keys/values**)

```bash
curl -L http://127.0.0.1:4001/v2/keys/skydns/?recursive=true
```

(**keys**)

```bash
etcdctl ls --recursive /skydns
```

**Comment by bacongobbler** [comment]
I'm not certain, but I think [getvs](https://github.com/kelseyhightower/memkv/blob/7f9c7f36f45ba80c62fe22779ee78d9b4ca36580/store.go#L103) is recursive, so this could work:

```
{{ range getvs "/skydns/*" }}
  {{ $data := json . }}
  host: {{ $data.host }}
  port: {{ $data.port }}
{{ end }}
```

**Comment by AlessandroEmm** [comment]
@bacongobbler i tried that:

`./confd-0.6.3-linux-amd64[648]: ERROR template: haproxy.cfg.tmpl:1:9: executing "haproxy.cfg.tmpl" at <getvs "/skydns/*">: error calling getvs: no keys match`

The Key Section of haproxy.cfg.tmpl is
keys = [
  "/skydns/",
]

But i tried with "/skydns/*" and others as well. The keys are obviously accessible via REST API.

**Comment by bacongobbler** [comment]
I was able to figure out a solution today, FYI:

Assuming the following keys:

```
SET /users/1/foo bar
SET /users/1/car star
SET /users/2/foo bar
```

The following works:

```
{{ range $user := lsdir "/users/" }}
user: {{ $user }}
{{ range gets (print "/users/" $user "/*") }}    {{ .Key }}: {{ .Value }}
{{ end }}
{{ end }}
```

Which will result in

```
user: 1
    foo: bar
    car: star

user: 2
    foo: bar
```

Let me know if that works for you.

**Comment by bacongobbler** [comment]
ping @AlessandroEmm

**Comment by AlessandroEmm** [comment]
@bacongobbler 
This only works if you know about the deepness of your hierarchy. I was looking for a solution that gathers all the leaves of a certain node.

**Comment by kelseyhightower** [comment]
It would be really hard to implement something like this across all backend stores and not cause serious performance issues walking a path to find its leaf nodes. I'm afraid this is out of scope for confd, which is designed to track specific keys and paths.
