### ISSUE TITLE
Site Disabled

### ISSUE THREAD

**Issue by icecreammatt** [kelseyhightower/confd#200]
I think this is the site for this repo...

![screen shot 2015-02-10 at 10 32 09 pm](https://cloud.githubusercontent.com/assets/1154569/6142922/b3816400-b174-11e4-9dfc-abe78604fc55.png)

http://www.confd.io/

**Comment by bacongobbler** [comment]
Indeed. Github recently deprecated a bunch of old IP addresses so we need to update our DNS records for www.confd.io to `CNAME kelseyhightower.github.io`.

https://github.com/blog/1917-github-pages-legacy-ip-deprecation

**Comment by kelseyhightower** [comment]
Ok, I've updated the A records, we should be back online now.
