### ISSUE TITLE
Render a "generated file" warning header

### ISSUE THREAD

**Issue by calh** [kelseyhightower/confd#202]
I've been looking through the Template Resources documents, and I don't see this feature.  Is it possible (easy) to add a warning header on the resulting rendered file, to tell others that any changes to the file will be overwritten by confd?

Here's the general idea I had:

/etc/confd/conf.d/haproxy.toml
```
[template]
src="haproxy.cfg.tmpl"
header="haproxy.cfg.header"
  ...
```
And /etc/confd/templates/haproxy.cfg.header could be a plain text with with something like:
```
##############################################################
###   WARNING:  Do not edit this file, changes will be 
###      overwritten by confd!   
###      Make changes to /etc/confd/templates/haproxy.cfg.tmpl
##############################################################
```

Thank you!

**Comment by kelseyhightower** [comment]
@calh You can do this inside the template. Checkout the docs on how to add a timestamp to the the comment as well:

https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#datetime
