### ISSUE TITLE
Keys in config not transformed into keys for retrieval in templates using {{ .foo_bar }} syntax

### ISSUE THREAD

**Issue by stone** [kelseyhightower/confd#207]
Version: confd 0.7.1 and git master branch.

https://github.com/kelseyhightower/confd/wiki/Quick-Start-Guide

    [myconfig]
    database_url = {{ .myapp_database_url }}
    database_user = {{ .myapp_database_user }}

Does not work, {{ .myapp_database_url }} becomes "no value" in output file.

https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md
template:

    [myconfig]
    database_url = {{getv "/myapp/database/url"}}
    database_user = {{getv "/myapp/database/user"}}

Works.

**Comment by bacongobbler** [comment]
The old syntax has been removed in favour of the latter. good catch :)

**Comment by bacongobbler** [comment]
I've updated the wiki for now, but it might be beneficial if we close the wiki in favour of the docs. I'll create a new bug for that. Thanks!
