### ISSUE TITLE
Setting watch to true only works from the command-line

### ISSUE THREAD

**Issue by gozer** [kelseyhightower/confd#208]
Setting watch=true in /etc/confd/confd.toml has no effect, even if it is documented that it should.

A quick look at confd.go (pardon my weak go-foo) seems to indicate that to me. It's picking the processor based on cmdline arguments early and doesn't look at config.Watch

        switch {
        case watch:
                processor = template.WatchProcessor(templateConfig, stopChan, doneChan, errChan)
        default:
                processor = template.IntervalProcessor(templateConfig, stopChan, doneChan, errChan, config.Interval)
        }

**Comment by scalp42** [comment]
I confirm just spent at least 5 hours on this:

In /etc/confd/confd.toml
```
watch = true
```

Doesn't work.
