### ISSUE TITLE
How to do conditional logic

### ISSUE THREAD

**Issue by cgswong** [kelseyhightower/confd#209]
For the keys:
```
/services/logging/host/172.17.8.101
/services/logging/host/172.17.8.102
/services/logging/host/172.17.8.103
```

I have a JSON array for each as follows:
```
{"host":"core-02"
,"http_port":9200
,"cluster_port":9300
,"cluster_name":"es01"}
```

How would I do conditional logic to only use a comma between values used and not at the end. For example, for a single key the template file would end up with:
```
host => ["172.17.8.102:9200"]
```
For multiple key detected
```
host => ["172.17.8.102:9200","172.17.8.101:9200","172.17.8.103:9200"]
```

I realize this is more of a Go text/template question perhaps.

**Comment by bacongobbler** [comment]
I'd take a look at `printf`: http://golang.org/pkg/text/template/#hdr-Functions

Were you eventually able to resolve this?

**Comment by cgswong** [comment]
@bacongobbler Thanks! I'll read through some more but it looks like it answers my question.

**Comment by bacongobbler** [comment]
Another handy function would be `join`: https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#join

**Comment by brmakana** [comment]
If you solved this, could you give an example of how?

**Comment by rgulewich** [comment]
@brmakana This worked for me:
```
[{{range $idx, $svc := gets "/services/*"}}{{ if (ne $idx 0) }},{{end}}
    {
        "key": "{{.Key}}",
        "value": "{{.Value}}"
    }{{end}}
]
```

**Comment by brmakana** [comment]
@rgulewich thanks for that, appreciated. I needed to get multiple key entries (of host addresses) into a logstash/elasticsearch config section; the trick is that I need them on a single line. I was able to do what I needed with this: 

```
elasticsearch {
      protocol => "http"
      index => "access-%{+YYYY.MM.dd}"
      host => [{{$services := ls "/services/elasticsearch"}}"{{join $services "\",\"" }}"]
      port => 9200
    }
```

This produces something like the following:

```
elasticsearch {
      protocol => "http"
      index => "access-%{+YYYY.MM.dd}"
      host => ["1.2.3.4, 1.2.3.5, 1.2.3.6"]
      port => 9200
    }

```
