### ISSUE TITLE
Is it possible to get the first key in a directory?  What about looking at values

### ISSUE THREAD

**Issue by tleyden** [kelseyhightower/confd#211]
In etcd I have the following key structure:

```
/foo
/foo/10.149.86.131
/foo/10.150.107.88
/foo/10.168.214.233
```

And I just want to get **one** of the children of the `foo` directory key (in fact I don't care which one).  Is this possible in confd?

Also, if would it be possible to add logic based on the value?  For example:

```
/foo
/foo/10.149.86.131 -> failed
/foo/10.150.107.88 -> active
/foo/10.168.214.233 -> failed
```

Is it possible to have confd return me the first key it sees under `/foo` where the value is `active`?

**Comment by bacongobbler** [comment]
> And I just want to get one of the children of the foo directory key (in fact I don't care which one). Is this possible in confd?

Yes. Use the `index` function: http://golang.org/pkg/text/template/#hdr-Functions

> Is it possible to have confd return me the first key it sees under /foo where the value is active?

Try the following and see if it works for you:

```
{{ $found := false }}
{{ range gets "/foo/* }}
{{ if (.Value eq "active") and ($found eq false) }}
{{ $found := true }}
{{ base .Key }}
{{ end }}
{{ end }}
```

**Comment by tleyden** [comment]
Thanks!

**Comment by tleyden** [comment]
I'll report back when I try the value conditional check.
