### ISSUE TITLE
waiting until a condition is met before running reload_cmd

### ISSUE THREAD

**Issue by paulczar** [kelseyhightower/confd#212]
I have a template which sets username/passwords via the API of the application being created by running itself as the `reload_cmd`

I run confd before the application is started and therefore the `reload_cmd` cannot run.    It appears to ignore an `&` if I put in at the end of the `reload_cmd` to try background it ( with a while loop inside checking for the API being up ).

So I would to either support backgrounding the `reload_cmd` so that it can move on ( may create race conditions? )  or have a `reload_when` directive that runs a command in a loop and then moves on and has a callback when the `reload_when` command has a successful return code.

Thoughts ?

**Comment by paulczar** [comment]
I have temporarily solved this by moving the `conf.d/manage.toml` file out of the `conf.d` directory and then after the app starts moving it back into `conf.d`.  not ideal but it unblocks me.

This does suggest an alternative,  allowing user to specify multiple `conf.d` directories.  that way I can have something like

```
./conf.d/config.yml.toml
./conf.d-post/manage.toml
```
and run confd pointing at both directories once the app is started.

**Comment by kelseyhightower** [comment]
@paulczar The solution for this case is the build a tool out of band that handles the retry logic and not return until complete. I've considered in the past to enhance the reload_cmd, but I've chosen to keep it simple to force a clear pattern of usage.
