### ISSUE TITLE
Key Not Found Stops Template 

### ISSUE THREAD

**Issue by mpchlets** [kelseyhightower/confd#216]
When a key is missing or not found, the entire template stops processing. I saw there was an old issue about this and it was decided to continue generating the template - was that abandoned?

I am doing:

{{range $server := gets "/servers/*"}}

If the /servers/ directory is empty, I get:

executing "haproxy.cfg.tmpl" at <gets "/servers/...>: error calling gets: no keys match

confd then stops processing.

I would expect this to continue executing and throw the error or have a way for me to check that keys exists in there before running the gets. exists does not work because I will not know what would or would not exist in that servers dir.

**Comment by cgswong** [comment]
The method to get around this is:
```
# Loop until confd has updated the logstash config
until confd -onetime -backend $KV_TYPE -node $KV_URL -config-file /etc/confd/conf.d/logstash.toml; do
  echo "[logstash] waiting for confd to refresh logstash.conf (waiting for ElasticSearch to be available)"
  sleep 5
done
```

**Comment by mpchlets** [comment]
That is not a working solution, sometimes services are just not present, for instance:

I have haproxy riding off of confd, say that 2 servers go down, 1 is part of a cluster that still has servers in it, the other is the last server, this will prevent an update to haproxy to remove the servers and will just keep them in the config until a server is available. Now add another server to the mix, no update since there is still an error due to no servers in the one group.

**Comment by cgswong** [comment]
What does your current confd command line, and toml file look like? It seems like, not using `-onetime` and instead using `-watch=true` and reloading HAProxy via `reload_cmd` could work to update your configuration whenever there is a change to the KV even if there is no value. I currently use supervisord to run confd and this works fine whenever there is no key or a key change (it reloads/restarts the process).

supervisord.conf:
```
[program:confd]
command=/usr/local/bin/confd -backend etcd -node 127.0.0.1:4001 -config-file /etc/confd/conf.d/logstash.toml -verbose=true
priority=10
numprocs=1
autostart=true
autorestart=true
stdout_events_enabled=true
stderr_events_enabled=true
```
logstash.toml:
```
[template]
src = "logstash.conf.tmpl"
dest = "/etc/logstash/conf.d/logstash.conf"
keys = [
    "/services/logging/es/cluster",
]
reload_cmd = "/usr/bin/supervisorctl logstash restart"
```

Another option is also consul-template.

**Comment by Telmo** [comment]
I actually have the same issue, and I have not been able to find a solution. Anyone has an insight on how to handle the errors? I've tried searching everywhere but all I got was "handle the errors before you render the template" which in the case of confd is not an option.

**Comment by bacongobbler** [comment]
I'm leaning towards the idea that we should change the behaviour of `gets` and `getvs` to return an empty list if no keys were found. This is a pretty big issue, IMO.

**Comment by mpchlets** [comment]
As a work around for now, I am setting a "placeholder" key at startup of my service for all directories that I expect to have a key and then I ignore them in my template, it is alright, a bit dirty but works, here is the interesting part in my haproxy.cfg.tmpl:

      {{range $server := gets "/services/app/80/*"}}
        {{$data := json $server.Value}}
        {{ if ne $data.IP "placeholder"}}
      server {{base $server.Key}} {{$data.IP}}:{{$data.Port}} check 
        {{end}}
      {{end}}

My data looks like this:
/services/app/80/placeholder:
`{"IP": "placeholder", "Port": "8080"}`

**Comment by kelseyhightower** [comment]
@bacongobbler We can make this change, but this issue will be then how to handle empty keys?

**Comment by mpchlets** [comment]
@kelseyhightower - I would lean towards returning the empty keys.

**Comment by kelseyhightower** [comment]
I've made changes on the master branch which makes `gets` and `getvs` return empty list if the key is missing. @bacongobbler @mpchlets

**Comment by kaililleby** [comment]
Nice! when will a new release be available, @kelseyhightower ?

**Comment by danixen** [comment]
Was it ever changed? Reading the documentation i see

gets
Returns all KVPair, []KVPair, where key matches its argument. Returns an error if key is not found.

getv
Returns the value as a string where key matches its argument. Returns an error if key is not found.

getvs
Returns all values, []string, where key matches its argument. Returns an error if key is not found.

**Comment by bacongobbler** [comment]
the change was made but it sounds like the docs weren't updated

**Comment by danixen** [comment]
Im trying to update my haproxy configuration file with confd. I want it to make no changes if no key is found. However confd throw an error saying "key not found" and does not complete the template.
ANy help with this?

Here's a code sample

{{range $service := ls "/microservices/}}
   found
{{end}}

**Comment by bacongobbler** [comment]
@danixen I just checked and verified and it doesn't look like this change ever made it into master.

**Comment by kelseyhightower** [comment]
@bacongobbler If these functions return empty strings and lists how will people know the difference between a missing or empty key?

**Comment by bacongobbler** [comment]
that is a good point. For our templating purposes we consider both the same since we're iterating over a list that typically has a TTL. If the key does not exist, that's fine for our use case.

However for us we are moving away from etcd templating now that we've moved over to kubernetes so my use case could be special, and it'd probably be better to initialize the keyspace with an empty list.

**Comment by kelseyhightower** [comment]
The right way to handle this use case is to use the `ls` and `lsdir` functions which return an empty list if the key is missing or empty. Use the `exists` function if you want to check if the key exists before you try and use it. You can find the documentation to all the template functions here: https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#template-functions

**Comment by mpchlets** [comment]
@kelseyhightower using `exists` or `ls`/`lsdir` does not solve the race condition of a key getting removed between the two - I would not want my template to crash because of a race condition.

**Comment by bacongobbler** [comment]
@mpchlets the template is evaluated all at the same time. We retrieve the values from etcd, then input that as values to the template resource. There should not be any race condition.

**Comment by mpchlets** [comment]
OK - my misunderstanding - thanks for clarifying.
