### ISSUE TITLE
specify certs and keys using environment variables

### ISSUE THREAD

**Issue by alexnauda** [kelseyhightower/confd#217]
Is it possible to configure confd's -client-ca-keys, -client-cert, and -client-key using environment variables? For example, etcdctl allows configuration of these through $ETCDCTL_CERT_FILE, etc.

**Comment by kelseyhightower** [comment]
@alexnauda Currently no. But I think it makes sense to add support for that.

**Comment by alexnauda** [comment]
https://github.com/kelseyhightower/confd/pull/238

**Comment by kelseyhightower** [comment]
Fixed in https://github.com/kelseyhightower/confd/pull/238
