### ISSUE TITLE
I wish there was a `getv` equivalent that accepted a default value

### ISSUE THREAD

**Issue by larsks** [kelseyhightower/confd#219]
My templates often end up being far too verbose because of things like this:

```
option = {{if exists "/example/app/option"}}{{getv "/example/app/option"}}{{else}}default_value{{end}}
```

That makes it quite hard to visually parse the config files.  Much easier would be something like:

```
option = {{getv "/example/app/option" "default_value"}}
```

**Comment by kelseyhightower** [comment]
@larsks I wonder if we can do this on a way that backwards compatible.

**Comment by bacongobbler** [comment]
does `{{ or (getv "/example/app/option") "default_value"}}` accomplish the same thing?

**Comment by bacongobbler** [comment]
kelseyhightower/memkv#4

**Comment by larsks** [comment]
@bacongobbler While that expression accomplishes the same thing, for someone coming from a different background where things like `${somevar:-value}` or `{{somevar|default('value')}}` are possible it seems needlessly verbose.

That linked patch looks like a step in the right direction, although it could use some documentation to go with it.

**Comment by bacongobbler** [comment]
@larsks that expression actually doesn't work; tried it myself today. However, with the proposed function it would look like `{{ getord "/example/key" "default" }}`.

**Comment by kelseyhightower** [comment]
@bacongobbler @larsks I wish go template function took optional params. Some people want thing to error if the key does not exist, some one a default value, some want a default empty value.

I guess we could solve this with more template functions, or figure out new functions that take options.

**Comment by bacongobbler** [comment]
Alternatively, a function which returns an empty string instead of an error would allow us to take advantage of the builtin `or` func. For example, `{{ or (funcName "/example/app/option") "default_value"}}` would default to "default_value" if the key did not exist and returned an empty string.

That should minimize it down to 2 different functions while covering both use cases: one to return an empty string and one returning an error when the key does not exist.

**Comment by Dynom** [comment]
Highly desired feature, due to the limited scoping flexibility it's very hard to produce default values when dealing with single-line properties (such as some HAProxy configuration lines).

**Comment by technosophos** [comment]
Could adding a `default` function accomplish this?

```
getv "foo" | default "bar"
```

Where `default` is basically backed by `func Default(def interface{}, given interface{}) interface{}`. The `Default` func then evaluates `given` to see if it's "empty" (however you want to define that), and returns either `given` if non-empty, or `def` if empty.

**Comment by technosophos** [comment]
Here's an example from Sprig. I'd be happy to port to Confd if others think this fits the bill:

https://github.com/Masterminds/sprig/blob/master/functions.go#L44

https://github.com/Masterminds/sprig/blob/master/functions.go#L231

**Comment by Dynom** [comment]
I don't have a particular preference for syntax, so whatever fits the convention is fine by me. The proposed `.. | default "value"` sounds excellent :+1:

**Comment by mishak87** [comment]
:+1: Any progress?
What about returning second argument on error  `getd (getv "x") "y"`?

**Comment by fruch** [comment]
:+1: 

it's a bit confusing that the documetion mention this now, and the version 0.11.0 doesn't have it, 
maybe adding a link in the documetion to 0.12.0-alpha3, or add a comment add in version.

**Comment by bacongobbler** [comment]
@fruch I'd accept a PR to remove that documentation.

**Comment by estahn** [comment]
Any progress?

**Comment by bacongobbler** [comment]
none.

**Comment by qvdk** [comment]
The documentation should be fixed since the default value is not available [as described in the documentation](https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#with-a-default-value).

**Comment by okushchenko** [comment]
Fixed in https://github.com/kelseyhightower/confd/commit/4388e4b
