### ISSUE TITLE
Are any variables usage inside toml files? 

### ISSUE THREAD

**Issue by nebelpfade** [kelseyhightower/confd#229]
Hello,

I'm trying to get something like:
[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
keys = [
    "/myapp/database/$DB_HOST",
    "/myapp/database/$DB_USER",
] 

of course it doesn't work, but maybe I missed something and there any way to process any variables inside toml files?

**Comment by kelseyhightower** [comment]
@nebelpfade Thanks for the question, but we do not support variables in the toml config files.
