### ISSUE TITLE
How to get json key name?

### ISSUE THREAD

**Issue by nebelpfade** [kelseyhightower/confd#237]
Hello,

Could you please explain how to get json key name?
For example I try to parse the following json:
{"innodb_buffer_pool_size":"128M"}

then I want to get from it:
innodb_buffer_pool_size = 128M

there is not a problem to get json .Value, but how to get json .Key ?

**Comment by worgock** [comment]
I'm not sure but this works for me:

{{ base .Key }} = {{ .Value }}

**Comment by bacongobbler** [comment]
yep, that should be the correct way to retrieve the keys from a json structure as per the arguments section in `text/template`:

> The name of a key of the data, which must be a map, preceded
  by a period, such as
	.Key
  The result is the map element value indexed by the key.

**Comment by nebelpfade** [comment]
Thanks for your answers.
Unfortunately it wasn't help to me. If I try to parse json in the following way:
{{ range json ( getv "/some_key" ) }}
{{ .Key }} = {{ .Value }}
{{ end }} 
I have got errors:
golang can't evaluate field Key in type interface {}
and
golang can't evaluate field Value in type interface {}

So for .Value it can be solved with {{ . }} except {{ .Value }}.

Anyway I have found a solution and maybe it will be good to have documented it:
{{ range $key, $value := json ( getv "/some_key" ) }}
{{ $key }} = {{ $value }}
{{ end }}

**Comment by worgock** [comment]
have you tried to write "base" keyword before ".Key"?

{{ range json ( getv "/some_key" ) }}
{{ base .Key }} = {{ .Value }}
{{ end }} 

Your solution is the same thing with the difference that you declare explicit variable name for Key and Value.
