### ISSUE TITLE
Lack of CHANGELOG file.

### ISSUE THREAD

**Issue by zytek** [kelseyhightower/confd#241]
Lack of CHANGELOG file in the repo makes it harder to quickly scoop for new features and fixed bugs.
"Releases" menu in GitHub is not verbose enough - for example I do not understand impact of changing go-etcd version.

**Comment by kelseyhightower** [comment]
@zytek I just added a change log to the project. While I don't plan to go back in time, I'm going to start logging things going forward. Thanks for the suggestion.
