### ISSUE TITLE
add etcd 2.0 support

### ISSUE THREAD

**Issue by bacongobbler** [kelseyhightower/confd#250]
See conversation in #195

**Comment by zytek** [comment]
FYI I use confd 0.7.1 with etcd 2.0. What issues do you have?

**Comment by kelseyhightower** [comment]
@bacongobbler Is  this still broken on master?

**Comment by zytek** [comment]
@kelseyhightower so, just to get things clear, does it mean it is safe to use confd from master with etcd 2.x ?

**Comment by bacongobbler** [comment]
yes, the integration tests seem to prove that.
