### ISSUE TITLE
additional string manipulation functions for template

### ISSUE THREAD

**Issue by mariusgrigaitis** [kelseyhightower/confd#252]
Currently confd provides only small subset of functions listed here: https://github.com/kelseyhightower/confd/blob/master/resource/template/template_funcs.go#L11

What I would like to have is more functions related to string manipulation. Currently I'm missing replace, toUpper.

consul-template provides such functions: 
https://github.com/hashicorp/consul-template#regexreplaceall

So I think it would be great idea to include those into confd.

**Comment by kelseyhightower** [comment]
@mariusgrigaitis Can this be closed now that #253 has been merged?

**Comment by mariusgrigaitis** [comment]
I think partially closed. Replace would also be good to have I think. Maybe we should close (rename) this and create new one?

**Comment by bacongobbler** [comment]
yes, let's close and add bugs for specific string manipulation functions so we can track their progress individually (some may make sense and some may not).
