### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by rimusz** [kelseyhightower/confd#267]
Thanks for the nice project

**Comment by bacongobbler** [comment]
I'd like to personally thank @kelseyhightower for all the hard work he's put into this project. Deis wouldn't be where it is today without confd, so fot that you have my thanks as well. :heart:

**Comment by rimusz** [comment]
:+1:

**Comment by mboersma** [comment]
:heavy_plus_sign: **100** to that.

**Comment by kelseyhightower** [comment]
Thanks everyone!!!!
