### ISSUE TITLE
Error for missing keys should not be truncated

### ISSUE THREAD

**Issue by carmstrong** [kelseyhightower/confd#268]
Currently, errors for missing keys are truncated, and don't show the full key which caused an issue, just part of its path:
```
ERROR template: confd_settings.py:33:20: executing "confd_settings.py" at <getv "/deis/database...>: error calling getv: key does not exist
```

**Comment by bacongobbler** [comment]
+1

**Comment by mboersma** [comment]
Would love to see this changed, it would make troubleshooting so much easier.

**Comment by kelseyhightower** [comment]
@carmstrong +1

**Comment by kelseyhightower** [comment]
@carmstrong Any plans to hack on this one?

**Comment by carmstrong** [comment]
@kelseyhightower Not sure where in the code to look - seems like this is a go template thing?

**Comment by kelseyhightower** [comment]
I'm hacking on this now.

**Comment by kelseyhightower** [comment]
This should be fixed on master.
