### ISSUE TITLE
Templating datetime unix format

### ISSUE THREAD

**Issue by battlecow** [kelseyhightower/confd#269]
Is there a way of either formatting the current date in unix/epoch format or could this be added as an alias as datetime has been?  

I have confd watching for a bind config and need to be able to update the serial number sequentially and thought that a datetime format in unix would work best.

**Comment by kelseyhightower** [comment]
@battlecow I'm happy to add another alias here. How would you like to see this work?

**Comment by battlecow** [comment]
@kelseyhightower 
I am just using the output of date +%s from terminal to always ensure a higher integer value for Bind zone serial number.  I don't have a particular opinion on its implementation, as I have not used Go I assume that the constant of UnixDate in the time package would suffice?

**Comment by kelseyhightower** [comment]
@battlecow Adding a new unixtimestamp function.

**Comment by kelseyhightower** [comment]
Looks like the datetime template function has been added, closing this out.
