### ISSUE TITLE
"if exists" doesn't work for directories in etcd

### ISSUE THREAD

**Issue by seanmcgary** [kelseyhightower/confd#273]
Im running confd to monitor etcd for changes to update my HAProxy config, and I noticed that when I try using ```{{if exists /some/dir}}}``` it seems to fail even though the directory exists. 

Here's a fuller example:

__values in etcd__

```
/apps/webapp/node-1
/apps/webapp/node-2
```

__/etc/confd/conf.d/haproxy.toml__

```
keys = [
    "/apps"
]
```

__/etcd/confd/templates/haproxy.cfg.toml__

```
{{if exists "/apps/webapp"}}
    {{range getvs "/apps/webapp/*"}}
        {{.}}
    {{end}}
{{end}}
```

So what Im wondering is, _should_ ```if exists``` work on etcd directories, or is it limited to keys only? If it _doesn't'_ currently work for directories, do you think it would make sense to add support for it? With this given use case, apps could register themselves under the ```/apps``` directory, making it so you don't have to update the list of keys. It also makes confd less prone to crashing when a specified key doesnt exist since everything will be nested under ```/app```, rather than explicitly specifying a key/path for each app.

**Comment by maccman** [comment]
:+1: for dir support

**Comment by bacongobbler** [comment]
IIRC the main reason why this won't work on all backends is because some do not have some form of discovering if a directory exists or not. We need a way to walk the tree like we did with 0.5.0 and earlier.

**Comment by duffqiu** [comment]
:+1:  for dir support because sometimes we only list some config parameter when the config section exist

**Comment by alirizakeles** [comment]
+1 

directory support is really important when we do not know about keys under dirs.

**Comment by scipetr** [comment]
+1

**Comment by gtonic** [comment]
+1

**Comment by hmatinho** [comment]
+1

**Comment by agalitsyn** [comment]
+1, it will be very useful for balancer configuration (as haproxy)

For example
toml
```
keys = [
    "/services/haproxy/backend",
]
```
tmpl
```
{{ if exists "/services/haproxy/backend/api-one" }}
    {{ range gets "/services/haproxy/backend/api-one/*" }}
        {{ $name := split (.Key) ":" }}
        {{ $endpoint := split (.Value) ":" }}
        server {{ index $name 1 }} {{ .Value }} check port {{ index $endpoint 1 }} inter 12000 rise 1 fall 1
    {{ end }}
{{end}}
```

**Comment by scipetr** [comment]
ping

**Comment by xFragger** [comment]
any news on this? can't complete my config without this or some kind of workaround

**Comment by mborho** [comment]
A possible workaround can be:

{{ range $i, $k := ls "/path/to/dir" }}
    {{ if not $i }}
        // dir exists, we're at index 0 (which is boolean false)
        // do something once
    {{ end }}
{{ end }}

**Comment by vangie** [comment]
+1

**Comment by streamnsight** [comment]
this workaround 
```
{{ range $i, $k := ls "/path/to/dir" }}
    {{ if not $i }}
        // dir exists, not empty, we're at index 0 (which is boolean false)
        // do something once
    {{ end }}
{{ end }}
```

seems to work at first level dir, but not in nested dirs... so it needs to be nested.
it becomes ugly quickly...

**Comment by streamnsight** [comment]
actually, it doesn't work when the key is meant to be watched in the TOML file, that's where it errors first with key not found even before getting to parsing the template.

**Comment by j-mcnally** [comment]
im having that issue too streamnsight

**Comment by streamnsight** [comment]
@j-mcnally  sorry, couldn't find a workaround. I ended up pre-populating the folders with mkdir function in etcd client so that the dir exists even if empty.

**Comment by kelseyhightower** [comment]
@streamnsight @j-mcnally I just cut 0.12.0 that uses the new etcd client, any chance one of you can retest?

**Comment by streamnsight** [comment]
Frankly i have moved on from there at this point, but will need to get back to it, just don't have time right now.

**Comment by kelseyhightower** [comment]
The right way to handle use case is to use the ls and lsdir commands. See this example: https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#create-the-template-1
