### ISSUE TITLE
after erroneous check (by check_cmd) the result file is not updated for next check

### ISSUE THREAD

**Issue by nixn** [kelseyhightower/confd#275]
I'm not completely sure about this, but it seems like when confd updates a file (result file) and runs `check_cmd`, which fails, then it won't replace it any more with neither the old version nor a new version (e.g. corrected template or corrected value). This leads to endless failing checks afterwards (once each interval). One must replace the result file with a "clean" (non-failing) version, then confd picks up the changes from the template or backend on the next check.

Is `check_cmd` possibly called before a new result file was written, resulting in the error?

**Comment by bacongobbler** [comment]
> Is check_cmd possibly called before a new result file was written, resulting in the error?

Yes. `check_cmd` is called before the template is written out to its destination.

**Comment by nixn** [comment]
Seems wrong to me, IMHO the check should check the new version, not the old.

**Comment by kelseyhightower** [comment]
@nixn Normally the check command is used like this:

```
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
```

`{{.src}}` refers to the proposed file, which allows us to be sure the generated config is validated before over writing the target.

**Comment by nixn** [comment]
Thanks for the hint, will check this. Perhaps it should be noted more clearly in the documentation? I missed it.

**Comment by nixn** [comment]
Now, while that works as you described, I still have a problem. I use the `sites-{available,enabled}` pattern for nginx, so the main configuration file (`nginx.conf`) includes `sites-enabled/*` which in turn has symlinks to `sites-available/...`. One of these files in `sites-available` is the dynamically updated configuration (`sites-available/http-proxy` with the according symlink in `sites-enabled`). Now when I change the proxy configuration in etcd, the `sites-available/http-proxy` shall be updated, with a check (by `check_cmd`). But I have no idea how to check the new configuration with `{{.src}}` as "the new `sites-available/http-proxy`", because I (or confd) would have to rewrite the main configuration file to include `{{.src}}`.

**Comment by akaspin** [comment]
`{{.src}}` not works in case of configs with templates. Result - dead loop.

**Comment by bacongobbler** [comment]
@akaspin that's the intent. However, its more like "write dest template to temp file. run `check_cmd`. if it success: move temp to dest; else `log.Error`". I'm not quite sure I understand your issue. If you can post a reproducible test case as a separate issue then I could take a look at it.

**Comment by kelseyhightower** [comment]
Unfortunately we cannot change the behavior on this one. confd writes configs to a temp file to ensure we don't change configs unless they pass any checks. Backend up the target file, then running the check runs the possibility of leaving the system in a broken state. The goal rename the proposed config file after ensuring it's ready to go.

confd does not support the slightly more complex use cases required by sites enabled, where a top level configuration file needs to import other files to complete the configuration. This is where I would say confd is the wrong tool for the job and maybe a more general configuration management tool like Puppet or Chef would be a better fit.

**Comment by dallaslu** [comment]
If your `dest` is not `/etc/nginx/nginx.conf`, such as `/etc/nginx/sites-available/some.conf`, the value of `{{.src}}` will be `/etc/nginx/sites-available/.some.conf899488104`. 

Then, `nginx -t -c /etc/nginx/sites-available/some.conf899488104` will return error, because of it is not a complete conf file of nginx.

So create wrapper file first, and delete it after check.

```conf
check_cmd = "TMP=/etc/nginx/$(basename {{.src}}).tmp && echo 'events{}http{' > $TMP && cat {{.src}} >> $TMP && echo '}' >> $TMP && (nginx -t -c $TMP; R=$?; rm -f $TMP; exit $R)"
```
If check failed:

> ERROR "nginx: [emerg] no servers in upstream \"backends\" in /etc/nginx/.backends.conf899488104.tmp:4\nnginx: configuration file /etc/nginx/.backends.conf899488104.tmp test failed\n"
> ERROR Config check failed: exit status 1
