### ISSUE TITLE
Support for pluggable "service" name in the SRV records

### ISSUE THREAD

**Issue by OskarKjellin** [kelseyhightower/confd#276]
If you follow this guide and set up SRV records for etcd:
https://github.com/coreos/etcd/blob/master/Documentation/clustering.md
They end up under _etcd-server._tcp.example.com.
But confd looks for it under _etcd._tcp.example.com. So confd and etcd does not really play well here. Would be nice with a way to configure what service to lookup the SRV record for.

**Comment by kelseyhightower** [comment]
@OskarKjellin +1 I wonder if we just add another flag for this?

**Comment by mborho** [comment]
+1 

Same problem here, can't use **-srv-domain** with etcd on CoreOS. Additional flag would be cool!

**Comment by r0j4z0** [comment]
+1

Any update about this? is a bit ugly maintain 2 similar records for etcd cluster configuration and for confd client access. I think the additional flag is the best option.

**Comment by kelseyhightower** [comment]
@r0j4z0 I'll be working on a solution for this today.

**Comment by kelseyhightower** [comment]
@r0j4z0 I'm thinking about introducing a new flag called `--srv-record` which would let you use anything you wanted to look up the SRV records. For example:

```
$ confd --srv-record="_etcd-client._tcp.confd.io." --log-level=debug
2016-02-20T15:46:04-08:00 confd[85031]: INFO SRV record set to _etcd-client._tcp.confd.io.
2016-02-20T15:46:04-08:00 confd[85031]: INFO Backend set to etcd
2016-02-20T15:46:04-08:00 confd[85031]: INFO Starting confd
2016-02-20T15:46:04-08:00 confd[85031]: INFO Backend nodes set to http://etcd0.confd.io:2379
```

**Comment by kelseyhightower** [comment]
@r0j4z0 This has been fixed on master. Please test and let me know.

**Comment by r0j4z0** [comment]
@kelseyhightower Tested, works like a charm! thank you!
