### ISSUE TITLE
Building confd on centos 7

### ISSUE THREAD

**Issue by schlitzered** [kelseyhightower/confd#277]
Hey, i would like to package confd for centos 7, and later for fedora.

But i am not even able to build confd without the packaging stuff. running ./build gives this error:

[rpmbuild@localhost confd-0.9.0]$ ./build 
Building confd...
can't load package: package github.com/kelseyhightower/confd: cannot find package "github.com/kelseyhightower/confd" in any of:
        /usr/lib/golang/src/pkg/github.com/kelseyhightower/confd (from $GOROOT)
        /home/rpmbuild/tmp/confd-0.9.0/Godeps/_workspace/src/github.com/kelseyhightower/confd (from $GOPATH)
godep: go exit status 1

any ideas?

**Comment by bacongobbler** [comment]
You have to clone confd at $GOPATH/src/github.com/kelseyhightower/confd.

**Comment by schlitzered** [comment]
thank you, it is compiling now, but why is it that i have to put it in this path? why cant i  just extract the source release tgz and compile?

**Comment by kelseyhightower** [comment]
@schlitzered It's a golang thing when using the default build tools. Many people set a custom GOPATH in their build scripts, but this is something I have avoided.

**Comment by kelseyhightower** [comment]
I'm closing this issue since this is a common build pattern in the Golang community. I'm happy to accept PRs against the docs to make it more clear how to build confd.
