### ISSUE TITLE
Make exists templating syntax work with environment backend

### ISSUE THREAD

**Issue by feniix** [kelseyhightower/confd#278]
Hi,

would it be too hard to make the following thing work?

```
{{if exists "VARIABLE"}}
    value: {{getenv "VARIABLE"}}
{{end}}
```

I tried it and could not make it work and it could come very handy when not using consul and other backends.

Regards

**Comment by bacongobbler** [comment]
`{{ if getenv "variable" }}` should do the same thing. `exists` determines if a key exists in the existing backend.

**Comment by feniix** [comment]
ah ok I did not see that in the docs :)

**Comment by bacongobbler** [comment]
From `text/template`'s if:

> If the value of the pipeline is empty, no output is generated; otherwise, T1 is executed.  The empty values are false, 0, any nil pointer or interface value, and any array, slice, map, or string of length zero. Dot is unaffected.

`getenv` is a call to `os.Getenv`, which returns an empty string if the envvar is not present, which is why this behaviour works that way.
