### ISSUE TITLE
Confd - out of sync - UID should be 0 and GID should be 0

### ISSUE THREAD

**Issue by karthikus** [kelseyhightower/confd#282]
I was using confd for all of my services and it was working perfectly fine. But when i templated a new service with 2 toml and 2 tmpl files, I got the following error due to which the file stays out of sync always:

```
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: time="2015-04-29T20:29:08Z" level="debug" msg="framesize: 80"
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: 2015-04-29T20:29:08Z 29e256488fb9 confd[7]: WARNING Skipping confd config file.
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: time="2015-04-29T20:29:08Z" level="debug" msg="framesize: 106"
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: 2015-04-29T20:29:08Z 29e256488fb9 confd[7]: INFO /usr/local/prism/etc/dbconn.conf has UID 495 should be 0
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: time="2015-04-29T20:29:08Z" level="debug" msg="framesize: 106"
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: 2015-04-29T20:29:08Z 29e256488fb9 confd[7]: INFO /usr/local/prism/etc/dbconn.conf has GID 496 should be 0
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: time="2015-04-29T20:29:08Z" level="debug" msg="framesize: 169"
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: 2015-04-29T20:29:08Z 29e256488fb9 confd[7]: INFO /usr/local/prism/etc/dbconn.conf has md5sum 421acfec43aef5763f9faaff276d4c98 should be c30a38096b6275fd8ec1d96b44ae50c0
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: time="2015-04-29T20:29:08Z" level="debug" msg="framesize: 108"
Apr 29 20:29:08 sc-stable-clustermachines-3zst3eveesta-5-iuyp4rp6icqo.novalocal docker[6433]: 2015-04-29T20:29:08Z 29e256488fb9 confd[7]: INFO Target config /usr/local/prism/etc/dbconn.conf out of sync
```

The toml corresponding to this error is as follows:

```

[template]

src = "dbconn.tmpl"

# The location to place the rendered configuration file
dest = "/usr/local/prism/etc/dbconn.conf"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys = [ "/app/database/postgresql"]

# File ownership and mode information
owner = "root"
mode = "0644"

uid = 0
gid = 0

reload_cmd = "service xyz restart"

```
P.S: Since it complained uid and gid as non-zero, I tried setting them manually but still I got the same error. Any help appreciated.

**Comment by karthikus** [comment]
I guess the problem was with the destination file already present. When i removed the file, I got the following log that does not indicate any error but clearly confd is not monitoring etcd for changes:

```
[root@e9d54bfdc6a9 /]# sh /usr/local/bin/confd-watch
[CDC] booting container. ETCD: 172.17.42.1:4001.
Initializing CDC Configuration
2015-04-29T22:43:50Z e9d54bfdc6a9 confd[17]: WARNING Skipping confd config file.
2015-04-29T22:43:50Z e9d54bfdc6a9 confd[17]: INFO Target config /usr/local/prism/etc/dbconn.conf out of sync
```

**Comment by kelseyhightower** [comment]
@karthikus What version of confd are you running? Also what command are you using to start confd?

**Comment by kelseyhightower** [comment]
We have a solution for this on master. https://github.com/kelseyhightower/confd/commit/6354ddd43eb8589fea16805e935ecdf9491fb7a6

The rules for this are as follows:

If the uid or gid is not set then use the effective uid or gid for the confd process owner. We will no longer default to uid or gid.

**Comment by mbuelte** [comment]
@kelseyhightower : Did I miss anything? I still have the same problem, even with the current master (confd 0.12.0-dev / golang 1.6.2). If I use the "owner/group" directives confd will 'correct' it to the process owner whatever is written into the toml configuration.

My configuration looks like this:
```
src   = "pg_hba.tmpl"
dest  = "/var/governor/data/postgres/pg_hba.conf"
owner = "xxx"
group = "governor"
mode  = "0660"
keys = [ "/services/postgresql/pg_hba" ]
reload_cmd = "kill -HUP $(head -1 /var/run/postgresql/9.5-main.pid)"
```

`$ ls -l /var/governor/data/postgres/pg_hba.conf`
> -rw-rw---- 1 xxx governor 325 10.10.2016-10:07 /var/governor/data/postgres/pg_hba.conf

`# confd -log-level debug -onetime -backend etcd -node http://127.0.0.1:2379`
> ...
> INFO /var/governor/data/postgres/pg_hba.conf has UID 1000 should be 0
> INFO /var/governor/data/postgres/pg_hba.conf has GID 997 should be 0
> ...
