### ISSUE TITLE
toml syntax error doesnt result in error

### ISSUE THREAD

**Issue by jon-shanks** [kelseyhightower/confd#286]
If there is an error within the toml it doesn't generate an error, there is no TOML parsing and error generation. 

[template]
mode = "0644"
src = "my.cnf.tmpl"
dest = "/etc/mysql/my.cnf"
prefix = "/common/services/percona"
keys = [
  "hosts",
  "config",
]
check_cmd = "/usr/sbin/mysqld --help >/dev/null 2>&1"
reload_cmd = "/etc/init.d/mysql reload

the missing " on the reload_cmd doesn't generate any errors on a confd run

**Comment by kelseyhightower** [comment]
@jon-shanks I'm taking a look at this now.
