### ISSUE TITLE
confd leaves behind temporary files after templating

### ISSUE THREAD

**Issue by carmstrong** [kelseyhightower/confd#288]
In at least come cases, confd fails to clean up the temporary files it uses when templating. See https://github.com/deis/deis/issues/3570 for details.

**Comment by kelseyhightower** [comment]
@carmstrong This must be new. Need to track this one down.

**Comment by bacongobbler** [comment]
I think it's because we just close the file instead of closing + removing the temp, unless I'm mistaken :) 

relevant: https://github.com/kelseyhightower/confd/blob/fed32feac4a18decf670ba30e3f7b77fae2af33f/resource/template/resource.go#L117

**Comment by bacongobbler** [comment]
Oh, that's because we have a `--keep-stage-file` flag now, so I guess it's choking before we call `sync()`: https://github.com/kelseyhightower/confd/blob/fed32feac4a18decf670ba30e3f7b77fae2af33f/resource/template/resource.go#L138-L142
