### ISSUE TITLE
(Question) Unexpected EOF

### ISSUE THREAD

**Issue by TelanJ** [kelseyhightower/confd#289]
Good day to Everyone,

I am a Junior Developer and I am trying to use confd to create a configuration file for ceph so that it will perform dynamic configuration. 

I am having trouble on implementing my confd. It displays `Unexpected EOF`

This is what I've done so far,

Template - https://github.com/TelanJ/consul-kv-ceph/blob/master/templates/ceph.conf.tmpl
Toml - https://github.com/TelanJ/consul-kv-ceph/blob/master/templates/ceph.conf.toml

Regards,
Julio Telan

**Comment by kelseyhightower** [comment]
@TelanJ I can try to reproduce this if you provide the output of confd with the debug flag.

**Comment by kelseyhightower** [comment]
I'm closing this due to a lack of response, but if this is still a problem I'm happy to help once you provide the requested info.
