### ISSUE TITLE
docs folder is gone

### ISSUE THREAD

**Issue by superpan** [kelseyhightower/confd#296]
Looks like all of the documentation are gone.  Can you replace the docs directory?

**Comment by bacongobbler** [comment]
looks like it was moved (accidentally on purpose) to https://github.com/kelseyhightower/confd/tree/master/src/github.com/kelseyhightower/confd/docs. It still exists but I guess was moved directly into the source. If you can PR the change to move docs/ back to the root, I'd be happy to review/merge :)

**Comment by bacongobbler** [comment]
fixed in #295
