### ISSUE TITLE
Passthrough service logs?

### ISSUE THREAD

**Issue by colebrumley** [kelseyhightower/confd#301]
**New feature idea:**
Add a flag that allows "passthrough" logs to be displayed in Confd's log .  This would be useful for containers in which confd is PID 1, because the normal stdout log would then show logs from both Confd and the app(s) confd is controlling.  This would make debugging/troubleshooting and log management much easier in many development use cases.

I am willing to code it, but wanted to get feedback on the idea before I start.

**Comment by bacongobbler** [comment]
I'm not too sure about this. Seems very specific to your use case. Can't you simply pipe your child processes' logs to /dev/stdout?

**Comment by kelseyhightower** [comment]
I agree with @bacongobbler that this is out of scope for confd.
