### ISSUE TITLE
Iterate over dynamic path in template

### ISSUE THREAD

**Issue by schlitzered** [kelseyhightower/confd#304]
Hey,

i would like to use etcd + confd to dynamically build configurations.

my data structure in etcd looks like this, if converted to json:

```
{ 
  "stage1": { 
    "activeVersion": { 
      "RSysLogReceiver": "v2015.04.02-16"
    },
    "endpoints": { 
      "RSysLogReceiver": { 
        "v2015.04.02-14": { 
          "inst1:port": { 
            "IP": "IPaddr1",
            "PORT": "PORTnum"
          },
          "inst2:port": { 
            "IP": "IPaddr2",
            "PORT": "PORTnum"
          } 
        },
        "v2015.04.02-16": { 
          "inst3:port": { 
            "IP": "IPaddr3",
            "PORT": "PORTnum"
          },
          "inst4:port": { 
            "IP": "IPaddr4",
            "PORT": "PORTnum"
          } 
        } 
      } 
    } 
  },
  "stage2": {}
} 
```
And the commands i used to populate the data to etcd:
```
etcdctl set /stage1/activeVersion/RSysLogReceiver v2015.06.16-1
etcdctl set /stage1/endpoints/RSysLogReceiver/v2015.06.16-1/inst1:12345 '{"IP": "host1","PORT": "12345"}'
etcdctl set /stage1/endpoints/RSysLogReceiver/v2015.06.16-1/inst2:12345 '{"IP": "host2","PORT": "12345"}'
etcdctl set /stage1/endpoints/RSysLogReceiver/v2015.06.16-1/inst3:12345 '{"IP": "host3","PORT": "12345"}'
```

I would like to use "activeVersion" to deploy multiple version of one application at the same time. All applications will register themself with there version number as prefix in "endpoints". "activeVersion" will contain the production version string, that should be used.

To create a config via confd with this pattern. i would need a template that looks something like this:

```
{{range gets "/endpoints/RSysLogReceiver/$(getv "/activeVersion/RSysLogReceiver")/*"}}
{{$data := json .Value}}
  port: {{$data.PORT}}
  ip: {{$data.IP}}
{{end}}

```

My current working version, with a static "activeVersion" looks like this
```
{{range gets "/endpoints/RSysLogReceiver/v2015.06.16-1/*"}}
{{$data := json .Value}}
  port: {{$data.PORT}}
  ip: {{$data.IP}}
{{end}}
```

Could you please give me a hint, how i have to modify the template to actually work with a dynamic path?

**Comment by bacongobbler** [comment]
Try `{{range gets (printf "/endpoints/RSysLogReceiver/%s/*" (getv "/activeVersion/RSysLogReceiver"))}}`. The idea is that the string passed to `gets` is a literal value, so any dynamic argument parsing needs to be done and returned as a string.

**Comment by schlitzered** [comment]
works, thank you!
