### ISSUE TITLE
Add support to update existing file instead of create-new and rename

### ISSUE THREAD

**Issue by diegomarangoni** [kelseyhightower/confd#308]
I'm running confd on the host machine and mounting the generated file as a volume in a docker container.
Once the container is running, the confd generated file is referenced thourgh the INODE at the disk.

The point is, when confd on the host machine recreates the file (removes the old one and replaces with a fresh file) I still have the old INODE referenced inside the container, resulting in a `Stale file handle` error.
So, instead of sending a reload signal to inside container, I have to restart the entire container, generating downtime and other bad side effects.

What if confd add support to just update a existing file?

**Comment by kelseyhightower** [comment]
@diegomarangoni Sorry for the late response here, but I'm not sure how to solve this problem. Right now we write to a tmp file to give us something we can compare. Then we do an atomic move to ensure we replace the target file in one shot. Most tools I know of do this to reduce the chance of an error during the write process leaving the target file in a broken state.

If you have a good example of how to update a file "in-place" and avoid the issues mentioned above feel free to let me know and reopen this issue.

**Comment by diegomarangoni** [comment]
@kelseyhightower What about replacing target file content within tmp file content?
And maybe to ensure the file is ok, compare their MD5 hash's?

Unfortunately I don't have any Go example.

Well, it's just a idea, I solved anyways by using a custom bash script set on `reload_cmd` that updates file content, it works, but it's ugly.

**Comment by baljanak** [comment]
+1
