### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by Sotorin** [kelseyhightower/confd#313]
I'm using CoreOS cluster and wanted to play with confd but how do install these binaries after the download? It just sits in my home dir. I installed GO (works fine) and wanted to compile from source but that's not working either. $HOME/confd is where I downloaded git repo to. I'm trying to follow the directions but I keep getting errors. 

```
core@core-01 ~/confd $ 
core@core-01 ~/confd $ GOPATH=$HOME/confd/vendor:$HOME/confd go build .
can't load package: package .: no buildable Go source files in /home/core/confd
```

**Comment by bacongobbler** [comment]
confd uses https://github.com/constabulary/gb. It would be best to take a look at the [integration tests](https://github.com/kelseyhightower/confd/blob/master/.travis.yml) next time, but the process to install is to use

```golang
go get github.com/constabulary/gb
./build
```

**Comment by Sotorin** [comment]
Thank you for such quick response but this doesn't work either. After setting GOPATH to $HOME/gocode and running:
```
$ go get github.com/constabulary/gb/...
```
now (under geocode) I have bin, pkg and src directories and when I try to run 
```
$ ./build
-bash: ./build: No such file or directory
```

This can't be that complicated. How can I use binaries I downloaded from the install page?

**Comment by bacongobbler** [comment]
`./build` is a script provided in the [root directory of confd](https://github.com/kelseyhightower/confd/blob/master/build). If you're building from source, the idea is that you clone confd, run `cd confd`, install `gb` and then run `./build`.

If you want to use the standalone binaries (on linux):

```
$ curl -Lo confd https://github.com/kelseyhightower/confd/releases/download/v0.10.0/confd-0.10.0-linux-amd64 && chmod 755 confd
$ ./confd --help
```

**Comment by Sotorin** [comment]
For those of you who may wish to compile from source. All of this on CoreOS.
1) Install GO - pretty straight forward. They tell you how you can test your install.
2) Set ```GOPATH```. If you don't do this then the next step will fail with "GOPATH not set".
```~$ mkdir nameOfYourDir``` [I named mine gocode] and then ```GOPATH=$HOME/gocode```
3) Install gb-tool ```~$ go get github.com/constabulary/gb/...```
4) In your ```$HOME/gocode``` dir you should now see ```/bin, /pkg and /src``` directories
5) Don't panic is you ```~/gocode/bin $ gb``` and you get ```-bash: gb: command not found```
6) Clone confd repo ```git clone https://github.com/kelseyhightower/confd.git```
7) ```cd``` into it ```cd confd```
8) Now ```gb build all``` won't work. Of course you will get ```-bash: gb: command not found```
9) But if you do this (assuming you are still in ~/confd dir) ```~/gocode/bin/gb build all```
then build should start and you should see output like this:
```
github.com/BurntSushi/toml
github.com/hashicorp/consul/api
github.com/awslabs/aws-sdk-go/aws/awserr
github.com/awslabs/aws-sdk-go/internal/apierr
github.com/vaughan0/go-ini
github.com/awslabs/aws-sdk-go/internal/endpoints
github.com/awslabs/aws-sdk-go/internal/protocol/json/jsonutil
github.com/Sirupsen/logrus
github.com/kelseyhightower/confd/backends/env
github.com/coreos/go-etcd/etcd
github.com/garyburd/redigo/internal
github.com/kelseyhightower/confd/backends/stackengine
github.com/samuel/go-zookeeper/zk
github.com/kelseyhightower/memkv
github.com/garyburd/redigo/redis
github.com/awslabs/aws-sdk-go/aws/credentials
github.com/awslabs/aws-sdk-go/aws
github.com/kelseyhightower/confd/log
github.com/kelseyhightower/confd/backends/redis
github.com/kelseyhightower/confd/backends/etcd
github.com/awslabs/aws-sdk-go/internal/protocol/jsonrpc
github.com/awslabs/aws-sdk-go/internal/protocol/rest
github.com/kelseyhightower/confd/backends/consul
github.com/kelseyhightower/confd/backends/zookeeper
github.com/awslabs/aws-sdk-go/internal/signer/v4
github.com/awslabs/aws-sdk-go/service/dynamodb
github.com/kelseyhightower/confd/backends/dynamodb
github.com/kelseyhightower/confd/backends
github.com/kelseyhightower/confd/resource/template
github.com/kelseyhightower/confd
```

You should now have compiled confd in your ~/confd/bin directory.

I tried running install but it failed with ```/usr/local/bin is read-only``` and that's by design. It's much easier to just download the executable just like @bacongobbler suggested. I would not even post this as an 'issue' if this was included in the installation instructions.
I think I'll enjoy working with the tool. Perhaps should be part of CoreOS distro. Thanks.

**Comment by qiaosangning** [comment]
thanks @Sotorin . I installed confd successfully as you said.

**Comment by bacongobbler** [comment]
FYI on master it's built using Godep so swap gb with godep and everything else is generally the same.
