### ISSUE TITLE
Importing confd code can create extremely long paths thanks to the gb src path

### ISSUE THREAD

**Issue by Ropes** [kelseyhightower/confd#316]
If attempting to import the etcd backend client code into another project, the import path becomes extremely long to the point of text wrap.
```
import "github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/backends/etcd"
```
This is thanks to gb requiring the project's nested source code to include the full github path effectively twice. For traditional GOPATH projects this is just an irritation, the code still compiles fine thankfully.

However @kelseyhightower mentioned that gb isn't really compatible with Go 1.5, and Godep looks to be the manager of choice going forward. 

I'd be happy to submit a PR to switch the project back to Godeps. `v0.9` was using Godeps so i can use that as an example, it shouldn't difficult.

**Comment by bacongobbler** [comment]
https://github.com/kelseyhightower/confd/commit/db867090afdfb4378dfa53073c5a9dcbe9fbb584 was the commit that switched over to `gb`.

**Comment by Ropes** [comment]
I'm making decent progress on the transtion back to Godeps. The `github.com/awslabs/aws-sdk-go` -> `github.com/aws/aws-sdk-go` causes some problems but I think they're solved. Haven't run integration test yet though :fearful:

**Comment by Ropes** [comment]
All integration tests run and pass with exception of DynamoDB. I need to get my AWS account setup for that.

**Comment by kelseyhightower** [comment]
@Ropes Just moved back to godeps, I'm going to mark this issue resolved.
