### ISSUE TITLE
Redis backend AUTH support

### ISSUE THREAD

**Issue by ilmerovingio** [kelseyhightower/confd#317]
Hello, 
As far as I can see in https://github.com/kelseyhightower/confd/blob/master/src/github.com/kelseyhightower/confd/backends/client.go#L42L43 there's no AUTH support for the REDIS backend (ref. http://redis.io/commands/AUTH)

This can be very useful with hosted Redis instances (Amazon ElastiCache, Azure Redis Cache etc...) or when is not possible to apply firewall rules.

Is there already a plan to implement it? 'redigo' package is already compatible but my Go is still too newbie for a pull request, I'm sorry :)

**Comment by ikoblik** [comment]
+1, that woud be great as it currently prevents us from using confd with publicly hosted redis.

**Comment by ilmerovingio** [comment]
Thanks @kelseyhightower @ericbarch and @israelchen!
