### ISSUE TITLE
confd bypasses local proxy, all instances connect directly to single cluster member

### ISSUE THREAD

**Issue by fasaxc** [kelseyhightower/confd#319]
I'm doing some scale testing of my application with a 5-node etcd cluster and 500+ client hosts.  I have an etcd proxy on each of my client hosts.  confd seems to initially connect to the local proxy but then, on subsequent requests, it connects directly to a node in the cluster.  Worse, all the confd instances seem to pick the same cluster node to talk to, which causes excessive load on that node and makes it unresponsive.

```
# /confd --version
confd 0.9.0
```

**Comment by bacongobbler** [comment]
sounds like an issue with go-etcd, as that is the library we are using to connect.

**Comment by xiang90** [comment]
try not to sync the cluster when you know you are reaching out a proxy.

**Comment by Lukasa** [comment]
As @xiang90 says, I think this is strictly an issue with the way confd *uses* go-etcd. On [L31 of backends/etcd/client.go](https://github.com/kelseyhightower/confd/blob/745cf2b8a17bc0ae29a26e81bb4b954f5eeb2890/src/github.com/kelseyhightower/confd/backends/etcd/client.go#L31) confd calls `Client.SetCluster`. This, behind the scenes, syncs the cluster.

This call causes go-etcd to query the etcd cluster and find all the machines in the cluster, and then sets the cluster information to that. I think simply removing this call would resolve the problem.

I'm going to try playing around with that change, to see what happens.

**Comment by Lukasa** [comment]
Ok, that appears to work, but we now encounter a problem when passing an authority without a scheme (i.e. just 'host:port', such as '127.0.0.1:4001'). Previously, the call to `SetCluster` would call go-etcd's `Client.createHttpPath` method, which can add a scheme to the front. This now doesn't happen. @kelseyhightower any objections to me bringing that method into `confd` so that I can use it here?

**Comment by geku** [comment]
For us this problem prevents an etcd cluster migration to new node. We have an etcd cluster and etcd-proxies, when etcd nodes get migrated to new nodes, the proxies still work and connect to the new etcd peers but confd stops working as it somehow misses the new etcd peers and returns a `ERROR 501: All the given peers are not reachable`.

In case the etcd would trust the proxy and not try to discover the peers itself, it would work.

**Comment by HeavyHorst** [comment]
This should be fixed in the latest master because of the switch to the new etcd client libs.

**Comment by kelseyhightower** [comment]
This should now be fixed on master now that we are using the new etcd client libs.
