### ISSUE TITLE
Improve logging, make it easy to enable/disable debug, warning, and info messages

### ISSUE THREAD

**Issue by kelseyhightower** [kelseyhightower/confd#32]

**Comment by bacongobbler** [comment]
Re-opening for a feature request to consolidate these flags into `--log-level`. At the moment we can show NOTICE errors with `--verbose` or show both NOTICE and DEBUG messages with `--debug`, but sometimes we want to suppress WARNING messages, or show just INFO messages. It'd probably be easier to set a log level and only display logs above and equal to the corresponding log level.

In terms of confd, that would mean the following hierarchy:

 - INFO
 - NOTICE
 - WARNING
 - ERROR
 - DEBUG

Does this seems reasonable?

**Comment by zytek** [comment]
ERROR should be on the top of hierarchy.

**Comment by bacongobbler** [comment]
Okay, I modified it to follow logrus's log level hierarchy which is implemented in #249.
