### ISSUE TITLE
Feature request: mustache templates

### ISSUE THREAD

**Issue by hookenz** [kelseyhightower/confd#321]
Maybe a pipe dream, but I wish confd supported an alternative template language like mustache, it's far easier to understand.  

https://github.com/hoisie/mustache

**Comment by bacongobbler** [comment]
related feature request: https://github.com/kelseyhightower/confd/issues/190

**Comment by tboerger** [comment]
[pongo2](https://github.com/flosch/pongo2) should be an awesome alternative as well :)

**Comment by bacongobbler** [comment]
For the same reasons as stated in #190 which proposed pongo2 support (<-- @tboerger), the text/template package works well enough. It's a breaking change to switch templating packages, so I'm going to close this, but please feel free to add your thoughts/opinions if there's something that text/template misses that mustache resolves which may be handy in a v1.0.
