### ISSUE TITLE
Watch support for zookeeper

### ISSUE THREAD

**Issue by PrFalken** [kelseyhightower/confd#341]
Why is the watch option not supported for zookeeper ?
Since you can subscribe to a node and get pushed as soon as there's a change.
Maybe it's just not implemented yet ?

**Comment by bacongobbler** [comment]
You are correct. It wasn't implemented when PR'd by a community member.

**Comment by sheepkiller** [comment]
watch option is not supported because zookeeper doesn't handle recursive watch. It's a little bit tricky to implement the watch behaviour you surely expect.

**Comment by johnbellone** [comment]
Is anyone working on this? What's the expected behavior?

**Comment by sheepkiller** [comment]
I plan  switching from "native" zookeeper client.go to docker/libkv

**Comment by jamescarr** [comment]
Cool let me know how this goes. How does this work without watch? I ran confd as a daemon and it never re-rendered templates until I restarted it. In the end I wound up just running it as a cron.

**Comment by HeavyHorst** [comment]
should work now: #405
