### ISSUE TITLE
Feature request: crypt values support

### ISSUE THREAD

**Issue by ludiazv** [kelseyhightower/confd#342]
It is planned to support the retrieval of key-values stored with crypt? As many .conf files usually involve the definition of certain passwords or secrets it would be nice to access to them directly from templates.

Thnx

**Comment by FreddyJones** [comment]
+1 Even if it is just a hash of some sort to keep it from the casual viewer, that would be a good beginning.

**Comment by odedlaz** [comment]
@ludiazv, have you considered using [vault](https://vaultproject.io)? It's supported now.

**Comment by ludiazv** [comment]
I will take a look to vault... many thanks.... but it could be an overkill.
I have reviewed #210 and it seem good enough for a the "minimal" approach i was looking for.. When it will be available in a stable release?

On the other hand I have requested a pull #412 with an even more minimal support via Decrypt function... could you consider also this one for improvement.

**Comment by okushchenko** [comment]
Fixed in #210
