### ISSUE TITLE
go-etcd is deprecated

### ISSUE THREAD

**Issue by balboah** [kelseyhightower/confd#345]
Might never be bugfixed for issues like [this](https://github.com/kelseyhightower/confd/issues/152#issuecomment-147958764). Maybe for future stability, confd needs to switch to the [other client lib](https://github.com/coreos/etcd/tree/master/client)

**Comment by kelseyhightower** [comment]
@balboah +1 I'll be working to port this in the coming weeks.

**Comment by streamnsight** [comment]
was this ever done?

**Comment by bacongobbler** [comment]
Nope, we still haven't ported over to go-etcd.

**Comment by maticmeznar** [comment]
@kelseyhightower Whats the ETA on this?

**Comment by kelseyhightower** [comment]
Just updated master to use the new etcd client. Please test.
