### ISSUE TITLE
reload_cmd freezes and blocks any further execution

### ISSUE THREAD

**Issue by ianbytchek** [kelseyhightower/confd#346]
Have the following configuration that sometimes gets stuck on running the reload command. Running the latest version, 0.10.0.

```toml
[template]

src = 'mongo-db.tmpl'
dest = '/var/confd/output/mongo-db/configuration.json'

keys = [ '/service/mongo-db/member' ]

reload_cmd = """sh -c \"\
    set -eu; \
    fleetctl stop mongo-db-cluster-node01@xxx || :; \
    fleetctl start mongo-db-cluster-node01@xxx; \
    \""""
```

When it gets stuck, I can open shell and enter the same command, or even only `fleetctl start mongo-db-cluster-node01@xxx` and it all gets going. The log below shows a two minute lag, after that I entered the command in a shell by hand and it unblocked confd.

```log
Oct 14 09:18:10 node01 confd-node01@[7190]: 2015-10-14T09:18:10Z node01 confd[10]: INFO Target config /var/confd/output/mongo-db/configuration.json out of sync
Oct 14 09:18:10 node01 confd-node01@[7190]: 2015-10-14T09:18:10Z node01 confd[10]: DEBUG Overwriting target config /var/confd/output/mongo-db/configuration.json
Oct 14 09:18:10 node01 confd-node01@[7190]: 2015-10-14T09:18:10Z node01 confd[10]: DEBUG Running sh -c "set -euo pipefail; fleetctl stop mongo-db-cluster-node01@xxx || :; fleetctl start mongo-db-cluster-node01@xxx; "
Oct 14 09:20:51 node01 confd-node01@[7190]: 2015-10-14T09:20:51Z node01 confd[10]: DEBUG "Unable to stop unit mongo-db-cluster-node01@xxx.service in state inactive\nUnit mongo-db-cluster-node01@xxx.service launched on e67d8bf1.../10.1.1.239\n"
Oct 14 09:20:51 node01 confd-node01@[7190]: 2015-10-14T09:20:51Z node01 confd[10]: INFO Target config /var/confd/output/mongo-db/configuration.json has been updated
```

While I found a workaround for fleet in particular by using `--no-block` option, this is concerning. What might be the difference between executing the same command via `reload_cmd` and directly in shell? How to make command executed via `reload_cmd` behave exactly like command executed directly in shell? Or is this a bug?

**Comment by kelseyhightower** [comment]
@ianbytchek I think we can use a timeout on the reload command, but we will need to make it configurable.

**Comment by ianbytchek** [comment]
Yep, that would be great. In the meanwhile, there's also a [timeout command](http://linux.die.net/man/1/timeout) that seems to be doing exactly that. While it covers cases like mine, I think it would be a good idea to have a long timeout in place by default, at least it would unblock confd eventually or produce some kind of warning in logs. Now, from a side it looks like everything's running fine and simply no reconfiguration is happening.

**Comment by rcadena** [comment]
fwiw, I found that this happens to me when the reload command launches a process and sends it to the background.  anything with `./some_executable_foo &`.  Looks like golang's exec and `CombinedOutput` stuff causes this behavior.  So, a timeout might not be the best solution because you'd kill the forked procs.  I think this is related (https://groups.google.com/forum/#!topic/golang-nuts/pJe7TVb-68w)

**Comment by ianbytchek** [comment]
True, true. But I guess you shouldn't invoke a forking process in this context or am I missing a point? The issue here is that a process may block the entire confd operation, a solution would be to kill and launch confd service again, that is the same outcome for the forked / blocking process either way.

**Comment by rcadena** [comment]
it's easy to go around, so I think maybe just mentioning it in the docs might be enough.  My service lifecycle was sort of split between two files, a run file and a reload script.  I couldn't reload my process with, say a signal, like nginx, for instance, so I was killing it and then relaunching it and sending it to the background. but, there's a straightforward fix, though, and  no need to kill confd.   If you can't reload the process, then loop in the entrypoint, and kill it in the reload script.

entrypoint.sh:
```
# ... setup stuff
confd -watch=true &

while true:
  /bin/run.sh
done;
```
I save the pid in `run.sh`

Then in `reload.sh`, called by `reload_cmd`:
```
# ... setup stuff
kill -$KILLSIG $PROC_PID
```

**Comment by kelseyhightower** [comment]
I've added a note regarding the reload cmd and blocking of configuration runs. When I clean up the docs I'll call this out in more places. Thanks for the feedback.
