### ISSUE TITLE
Next release plan?

### ISSUE THREAD

**Issue by cloudnautique** [kelseyhightower/confd#352]
Hi, is there a timeline for the 0.11.0 release?

**Comment by bacongobbler** [comment]
@cloudnautique there's no timeline. It's just maintained on our own free time. Do you have something in mind that you'd like to see in 0.11?

**Comment by cloudnautique** [comment]
Cool, not in a huge rush, we added the Rancher metadata backend and would like to point users to an official release. We have a binary/container available that we built thats working for now. 

Thanks.

**Comment by clescot** [comment]
+1 for a new release (interested by the rancher backend).

**Comment by markhowells** [comment]
Yep, I'm interested in the --no-sync option.

A new release would be appreciated (I'm running a fork)

**Comment by lc0** [comment]
Also seems like the last dynamodb fix is not in last release

https://github.com/kelseyhightower/confd/commit/1f7ec71cb2a9ba337f4e893ea99ebff6a05ede3d

would be cool if we can bring it up

**Comment by bacongobbler** [comment]
I'll see if I can whip up a new release some time today. I likely won't be able to until after regular work hours (17:00PST). Sorry!

**Comment by lc0** [comment]
@bacongobbler Thank you very much man! 

Just in case, I made a build from the current master - 
https://github.com/lc0/confd/releases/tag/v0.10.1

**Comment by bacongobbler** [comment]
Ok, I just cut [v0.11.0](https://github.com/kelseyhightower/confd/releases/tag/v0.11.0). Thanks for your patience!

**Comment by clescot** [comment]
Thanks for this release!
Charles.
