### ISSUE TITLE
DynamoDB invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lynxman** [kelseyhightower/confd#353]
Running on RHEL7
Using DynamoDB in AWS with profile credentials (inherited from IAM profile)
Just with one template for testing
Compiled with Golang version 1.4.2 from trunk as of today (10 Nov 2015 1pm GMT)

Here is the template config

    [template]
    prefix = "/test"
    src = "nginx_upstream.tmpl"
    dest = "/etc/nginx/conf.d/test.conf"
    owner = "nginx"
    mode = "0444"
    keys = [
      "/config",
    ]
    reload_cmd = "/usr/sbin/nginx -s reload"

Here is the template

    # Generated by confd with DynamoDB info
    # Schemaversion: {{$data.SchemaVersion}} EnvironmentName: {{$data.EnvironmentName}}
    upstream {{$data.UpstreamName}} {
        zone {{$data.UpstreamName}}{{if $data.PersistenceMethod}} {{$data.ZoneSize}}{{end}};
        {{if not (eq $data.LoadBalancingMethod $defaultPersistenceMethod)}}{{$data.LoadBalancingMethod}};{{end}}
        {{range $data.Hosts}}
        server {{.DnsName}}:{{.Port}} resolve {{if .FailTimeout}}fail_timeout={{.FailTimeout}}{{end}} {{if .MaxFails}}max_fails={{.MaxFails}}{{end}} {{if not (eq .State $defaultHostState )}}{{.State}}{{end}} {{if .Weight}}weight={{.Weight}}{{end}};
        {{end}}
        {{if $data.PersistenceMethod}}{{$data.PersistenceMethod}}{{end}};

Here is the startup config

    # AWS_REGION="eu-west-1" /usr/bin/confd -config-file /etc/confd/confd.toml -backend dynamodb -table DYNAMOTABLE -log-level debug

Here is the log output

    2015-11-10T12:51:40Z ip-10-249-137-3.test.local /usr/bin/confd[18258]: INFO Backend set to dynamodb
    2015-11-10T12:51:40Z ip-10-249-137-3.test.local /usr/bin/confd[18258]: INFO Starting confd
    2015-11-10T12:51:40Z ip-10-249-137-3.test.local /usr/bin/confd[18258]: INFO Backend nodes set to
    2015-11-10T12:51:40Z ip-10-249-137-3.test.local /usr/bin/confd[18258]: INFO DynamoDB table set to DYNAMOTABLE
    2015-11-10T12:51:40Z ip-10-249-137-3.test.local /usr/bin/confd[18258]: DEBUG Loading template resources from confdir /etc/confd
    2015-11-10T12:51:40Z ip-10-249-137-3.test.local /usr/bin/confd[18258]: DEBUG Loading template resource from /etc/confd/conf.d/test.toml
    2015-11-10T12:51:40Z ip-10-249-137-3.test.local /usr/bin/confd[18258]: DEBUG Retrieving keys from store
    2015-11-10T12:51:40Z ip-10-249-137-3.test.local /usr/bin/confd[18258]: DEBUG Key prefix set to /test
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x527355]

    goroutine 24 [running]:
    github.com/kelseyhightower/confd/backends/dynamodb.(*Client).GetValues(0xc2081b9020, 0xc2081b1f20, 0x1, 0x1, 0x1, 0x0, 0x0)
        /root/rpmbuild/BUILD/confd-master/src/github.com/kelseyhightower/confd/backends/dynamodb/client.go:65 +0x475
    github.com/kelseyhightower/confd/resource/template.(*TemplateResource).setVars(0xc208071200, 0x0, 0x0)
        /root/rpmbuild/BUILD/confd-master/src/github.com/kelseyhightower/confd/resource/template/resource.go:92 +0x171
    github.com/kelseyhightower/confd/resource/template.(*TemplateResource).process(0xc208071200, 0x0, 0x0)
        /root/rpmbuild/BUILD/confd-master/src/github.com/kelseyhightower/confd/resource/template/resource.go:255 +0x71
    github.com/kelseyhightower/confd/resource/template.process(0xc20802c258, 0x1, 0x1, 0x0, 0x0)
        /root/rpmbuild/BUILD/confd-master/src/github.com/kelseyhightower/confd/resource/template/processor.go:26 +0x99
    github.com/kelseyhightower/confd/resource/template.(*intervalProcessor).Process(0xc208072a80)
        /root/rpmbuild/BUILD/confd-master/src/github.com/kelseyhightower/confd/resource/template/processor.go:54 +0x10f
    created by main.main
        /root/rpmbuild/BUILD/confd-master/src/github.com/kelseyhightower/confd/confd.go:52 +0x594

    goroutine 1 [runnable]:
    main.main()
        /root/rpmbuild/BUILD/confd-master/src/github.com/kelseyhightower/confd/confd.go:57 +0x9dd

    goroutine 5 [syscall]:
    os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
    created by os/signal.init·1
        /usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

    goroutine 23 [select]:
    net/http.(*persistConn).writeLoop(0xc2080304d0)
        /usr/lib/golang/src/net/http/transport.go:945 +0x41d
    created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:661 +0xcbc

    goroutine 22 [runnable]:
    net/http.(*persistConn).readLoop(0xc2080304d0)
        /usr/lib/golang/src/net/http/transport.go:928 +0x9ce
    created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:660 +0xc9f

    goroutine 33 [syscall, locked to thread]:
    runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

**Comment by bracki** [comment]
Please make sure that the attribute values for `value` are of type string.
All other types will currently lead to said exception.
