### ISSUE TITLE
confd fails talking to etcd in proxy mode

### ISSUE THREAD

**Issue by markhowells** [kelseyhightower/confd#354]
I have a etcd proxy (2.2.1) doing TLS termination and exposing an endpoint on http://172.17.0.1:2379/
Using etcdctl I can read/write the cluster if I use --no-sync to force etcdctl to trust the proxy.

Confd (0.10.0) appears to exhibit similar behaviour to etcdctl without the no-sync flag

    confd -onetime -node http://172.17.0.1:2379

returns the following (I've redacted the external IP address below)

    ERROR 501: All the given peers are not reachable (failed to propose on members [https://1.2.3.4:2379]

Is there a no-sync equivalent to force confd to trust the proxy?  Otherwise I don;t see how I can use confd with a TLS proxy...

**Comment by bacongobbler** [comment]
sounds like a dupe of #319. Try out #329 and see if that helps solve your issue :)

**Comment by markhowells** [comment]
Yep. That fix works fine. Hope it makes it into a release soon. :)
