### ISSUE TITLE
renew confd.io (pending deletion)

### ISSUE THREAD

**Issue by anapsix** [kelseyhightower/confd#355]
@kelseyhightower, you might want to renew it (?)
```
$ whois confd.io

Domain : confd.io
Status : pendingDelete
Expiry : 2015-10-26
Delete : 2016-01-25 00:30
Domain reserved
```

[whois via nic.io](http://nic.io/go/whois/confd.io):
```
The domain is unavailable for use
Domain Status:	pendingDelete / Final Phase
Expiry :	2015-10-26
 
Reserved by Back-Order :	No

Unless it is renewed it will be deleted in a batch run started at 2016-01-25 00:30 (UTC) 
Purchase a Back-Order ... (What is a back-order?)
```

**Comment by josegonzalez** [comment]
Friendly *bump* :)

**Comment by kelseyhightower** [comment]
@josegonzalez @anapsix Both issues regarding the domain have been fixed. The domain name registration was renewed just in time so it was not delete. I'm now delegating DNS to Google Compute Engine so everything should be working now. Thanks for the ping and friendly reminders.
