### ISSUE TITLE
prefix key is not used when in watch mode

### ISSUE THREAD

**Issue by markhowells** [kelseyhightower/confd#358]
using confd 0.10.0, it seems that watch doesn;t respect the prefix key.  Without it (and with longhand keys) all is well. -onetime (forcing the processing) works. But with a prefix and shorthand keys, watches are never fired

**Comment by elsonrodriguez** [comment]
Couldn't reproduce this issue on the latest confd, Tried to reproduce as follows (I assumed etcd for the back end)
#### etcd version
```
$ etcd -version
etcd Version: 2.3.0-alpha.0+git
Git SHA: 40d3e0d
Go Version: go1.5.3
Go OS/Arch: darwin/amd64
```

#### confd version
```
$ ./bin/confd -version
confd 0.12.0-dev
```

#### Confd configuration
```
[myconfig]
database_url = {{ getv "/database/url" }}
database_user = {{ getv "/database/user" }}
```

```
[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
keys = [
   "/database/url",
   "/database/user",
    ]

owner = "root"
mode = "0600"
```

#### confd command line
```
./bin/confd -watch -prefix /myapp
```

#### etcd data structure
```
etcdctl set /myapp/database/user user1
etcdctl set /myapp/database/url url1
```

#### Confd logs on etcd value change
```
2016-02-22T21:05:55-08:00 ireul.local ./bin/confd[7447]: INFO /tmp/myconfig.conf has md5sum da58eb73a3733704ea19a3f9b4a3d5bd should be 67c8785d3d975bb0d4a9f150f0d678bd
2016-02-22T21:05:55-08:00 ireul.local ./bin/confd[7447]: INFO Target config /tmp/myconfig.conf out of sync
2016-02-22T21:05:55-08:00 ireul.local ./bin/confd[7447]: INFO Target config /tmp/myconfig.conf has been updated
```
Could you try to reproduce on the latest versions of confd/etcd and see if it solves the problem?

**Comment by markhowells** [comment]
Using the latest confd/etcd I can't reproduce it now either.  Your test represents the environment I had (I think - it was some time ago now...).  I _was_ using confd 0.10.0 (and I don't know what version of etcd).  

I think it's probably best to close this issue..
