### ISSUE TITLE
Exit code 0 when cannot load template resources: confdir

### ISSUE THREAD

**Issue by moshe0076** [kelseyhightower/confd#359]
confd should return exit code non-zero when it fails to find the template resources so scripts or Jenkins jobs will break.

**Comment by tduchateau** [comment]
+1

**Comment by kelseyhightower** [comment]
I'm assuming this happens when there are no templates to process? Right now it's totally valid to have no template resources to process.

**Comment by kelseyhightower** [comment]
Today confd allows you to have 0 templates to process. I'm working on a feature to add support for running a single template-resource using a specific template. 

In the near future you will be able to do something like:
```
$ confd --template-resource=/myconfig.toml --template=myconfig.tmpl
```
