### ISSUE TITLE
Add file based(json and/or yaml) backend

### ISSUE THREAD

**Issue by mingfang** [kelseyhightower/confd#361]
Currently we use confd with the etcd backend for dynamic Nginx configuration.
We want to standardize on confd for all configuration templating.
For some simple one time templating we want to avoid using etcd but rather keep configurations inside a simple json and/or yaml file.

**Comment by bacongobbler** [comment]
see #201

**Comment by mingfang** [comment]
@bacongobbler Thanks for the link.
After reading #201 I not sure if this feature was actually implemented or not.
The issue was closed yet the feature is not documented.

**Comment by bacongobbler** [comment]
Sorry, yeah I was just trying to point out that this has been a requested feature before but there were some issues with the implementation which we never got around to fixing. It was eventually closed but not merged.

**Comment by sfussenegger** [comment]
@bacongobbler sounds like a very interesting feature. #201 was about using a filesystem as backend (i.e. multiple files and directories). Shouldn't a single JSON/YAML file backend be much easier to implement? The use case I have in mind is using a cron job with curl and an (arbitrary) REST service or other JSON-based tools to update a file that is watched by confd. e.g. to maintain a list of EC2 instances: `aws ec2 describe-instances > /tmp/instances.json`

Compared to the filesystem backend a simple file backend would allow a whole lot of input sources. There could be non-polling-based inputs too, e.g. a process that listens to a message queue and updates a file.

**Comment by kelseyhightower** [comment]
@sfussenegger @bacongobbler I'm happy to see a simple json or yaml backend. Ideally it would work like the env backend. We can add support for watches on files as well.

**Comment by rodlogic** [comment]
Yes, this would be quite useful!
