### ISSUE TITLE
Sentry error reporting on missing keys

### ISSUE THREAD

**Issue by BradWhittington** [kelseyhightower/confd#362]
I'm not sure if this would be possible / desirable for other people, but it would be a huge help if we could configure confd to report missing keys / trouble generating configs into Sentry (or I'm sure, airbrake, etc.)

**Comment by kelseyhightower** [comment]
@BradWhittington Sorry for getting to this so late, but I wonder if it would be better to have something like fluentd or some other log aggregator managing logs so we don't end up having to support so many tools for this.

I would like to keep confd simple as possible for the moment and that means logging to stderr and stdout.

**Comment by BradWhittington** [comment]
That's the approach we took in the end. Thanks.
