### ISSUE TITLE
Error not logged with -onetime

### ISSUE THREAD

**Issue by benluddyatwork** [kelseyhightower/confd#366]
In order to find out what was causing confd to exit 1 (a typo in a template resource), I had to remove -onetime. It would be nice to log err here: https://github.com/kelseyhightower/confd/blob/46d3c69d05c29f0842472df44354d1023917b833/src/github.com/kelseyhightower/confd/confd.go#L35

**Comment by bacongobbler** [comment]
Good catch. We certainly should log that error rather than failing silently.

**Comment by kelseyhightower** [comment]
This is fixed on master
