### ISSUE TITLE
Release URL scheme changed with v0.11.0

### ISSUE THREAD

**Issue by llarsson** [kelseyhightower/confd#368]
As commented by @ChineduUzoka over in [#365](https://github.com/kelseyhightower/confd/issues/365#issuecomment-161570076), the release URL scheme changed with v0.11.0

Is this new scheme what will be used henceforth, or was it a mistake?

**Comment by bacongobbler** [comment]
This was a mistake. I'll rectify it. Thanks!

**Comment by bacongobbler** [comment]
fixed.
