### ISSUE TITLE
Support for a (HashiCorp) Vault backend

### ISSUE THREAD

**Issue by nickithewatt** [kelseyhightower/confd#372]
Any plans to add support for the HashiCorp Vault backend?

**Comment by sporkmonger** [comment]
I too would be very interested in seeing this.

**Comment by odedlaz** [comment]
I'm working on it right now. I actually have a working prototype that supports token authentication, github authentication and userpass authentication. The only "problem" I'm facing is how to actually extract the data. When accessing a specific key in vault it returns a map of keys and values. To make the templating engine work, I need to pick a specific value. currently, I'm extracting a key called "value". any ideas?

**Comment by bacongobbler** [comment]
@odedlaz if you can encapsulate that map into a struct, we could template that out. I'd imagine that those keys and values are important to the user. What exactly does the map look like when it's returned? Haven't worked with Vault before.

**Comment by odedlaz** [comment]
@bacongobbler, confd expects a key-value store and the value lookup method signature is 
``` go
func (c *Client) GetValues(keys []string) (map[string]string, error) 
```
 which means that for each key, the backends needs to find a string value. 
Changing the method signature would be a big change in the way confd works.
I can do that, but I think it's an over-kill now. 
take a look at my pull request: https://github.com/kelseyhightower/confd/pull/383

**Comment by odedlaz** [comment]
@bacongobbler , I've made the proper adjustments to make it work. please take a look at my pull request and tell me what you think: https://github.com/kelseyhightower/confd/pull/383

**Comment by kelseyhightower** [comment]
Vault support has been added via #383

**Comment by jacklei** [comment]
@odedlaz This is exactly the functionality that I am looking for. Were you able to use confd template to get user:pass from vault's secrets engine?
