### ISSUE TITLE
dynamodb errors

### ISSUE THREAD

**Issue by jbkc85** [kelseyhightower/confd#375]
Hi all,

I have added a bit of code to make the basics of the new Etcd library work, but had to comment out all the dynamodb configurations due to issues with their library.  I am not in the position to work on dynamodb at this time, and was wondering how to handle this situation.  I could easily move the dynamodb out, but fear that would result in some not noticing that the code was commented out.

Any ideas on how to handle the pull request and get some feedback on the Etcd code?

-> https://github.com/jbkc85/confd/commit/d863548a01bb80850df5440751501c424bdcc2bf

Please be gentle, first time coding in Go and committing back to the community :-)

**Comment by kelseyhightower** [comment]
Looks like we got the new etcd stuff merged and I've fixed the issues around dynamodb so all should be good now. Testing what we have on master would be awesome.

**Comment by jbkc85** [comment]
Sure thing, I will see if i can write out some unit testing and just share it in a repository for others to test whenever you build new versions of Confd in case things change.

out of curiosity, did my code help at all?  I wasn't sure as I didn't make a pull request, but would be happy if it helped :-)

**Comment by jbkc85** [comment]
Etcd works great.  Tested with TLS encryption on our dev cluster.

**Comment by bacongobbler** [comment]
@jbkc85 FYI we do have [integration tests for dynamodb](https://github.com/kelseyhightower/confd/blob/master/integration/dynamodb/test.sh) as well, so hopefully in the future these bugs shouldn't come up. :)
