### ISSUE TITLE
reload_cmd prevent standard log output

### ISSUE THREAD

**Issue by arthur-c** [kelseyhightower/confd#376]
Hi,

I start a jetty application in a docker with the reload_cmd option in my toml and it prevents the jetty logs to be sent to the standard output. I'm able to see the confd logs on the standard output and systemd (coreos).
I stopped to use the reload_cmd and now I start jetty directly after confd in my docker bootscript, and my logs are back. I don't need to reload once the app is configured with confd and started, but it's convenient to handle the start from confd. It might be a normal behaviour but is there a workaround ?

I still use 0.10.

**Comment by kelseyhightower** [comment]
@arthur-c The reload_cmd should only be used to restart an application. It should not be used to start your application server. confd should not be used to start another process, it's only job is to generate configuration files, then optionally run a check and/or reload command.

**Comment by arthur-c** [comment]
I understand but it was very convenient to use. But after that I found your great article "12 Fractured Apps" and I migrated to environment variable config. No need to confd  anymore for this app, thanks !
