### ISSUE TITLE
RFE: support for LDAP

### ISSUE THREAD

**Issue by muayyad-alsadi** [kelseyhightower/confd#381]
example use case is collect public keys from LDAP (for example FreeIPA) and generate authorized keys

**Comment by kelseyhightower** [comment]
@muayyad-alsadi I guess a LDAP backend would do it, but it might be easier to have an external tool fetch the public keys from LDAP and drop them into something like etcd or consul.

**Comment by muayyad-alsadi** [comment]
But don't you think that having a cron that fetches public keys over and
over from ldap and publish then to etcd every so and so is not ideal and
can be said to any backend like zookeeper or redis.

**Comment by bacongobbler** [comment]
I think the point @kelseyhightower is trying to make is that redis/zookeeper/etcd are key/value stores. LDAP is not. It would make sense if LDAP is a key/value store which we could watch certain keysets or perform operations on them, but LDAP does not have that kind of functionality. I'm personally in favour of @kelseyhightower's suggestion here.

**Comment by muayyad-alsadi** [comment]
LDAP is short for lightweight director which is a hierarchal database of
entries each entry has a key or uid and values. In my example use case user
entries have corresponding ssh public keys. In away similar to env backend
we can look to ldap as key value.

Of course we are going to limit it to something that makes sense.

http://linux.die.net/man/1/ldapsearch
http://www.freeipa.org/page/V4/Directory_Browsing

ldapsearch -x -D "cn=Directory Manager" -w Secret123 -b
"cn=users,cn=accounts,dc=example,dc=com" "(objectclass=*)" dn givenName sn

And in confd "cn=users,cn=accounts" would be /accounts/users/

{{ range ls  /accounts/users/* }}
Name= {{.givenName}}
{{end}}

The question here does it make sense to pass all those parameters of
ldapsearch to confd or is that over engineering.

**Comment by muayyad-alsadi** [comment]
> The question here does it make sense to pass all those parameters of ldapsearch to confd or is that over engineering like we do with dynamodb `--table`

maybe we need a more general way of passing parameters for example instead of `-node consul1.service`  or `-table mytable` for example `-backend-option node=consul1.service -backend-option node=consul2.service` which such generic way passing required parameters to ldap would be easy.

@kelseyhightower  @bacongobbler  do you think the above method is over-engineering over-generalization or is this a good feature?

**Comment by kelseyhightower** [comment]
@muayyad-alsadi While I agree we need a way to specify backend specific options, I'm not sure LDAP integration is the path I want to go down.

**Comment by kelseyhightower** [comment]
At this point I rather see a proposal on how to handle metadata such as this and give backends the ability to process it. I'm closing this issue because I don't believe LDAP is the right way to go about this.

**Comment by Mic92** [comment]
Is anyone aware of a similar tool that can generate configuration based on ldap data?
