### ISSUE TITLE
Plans for next release 0.12.0

### ISSUE THREAD

**Issue by sylus** [kelseyhightower/confd#391]
Hi, I was wondering what are the plans for the next release as alot has made its way in since 0.11.0. 

Of primary interest to myself is the new vault addition :)

**Comment by kelseyhightower** [comment]
@sylus I'm in the process of cleaning up all the backends and adding more test. I plant to cut a 1.0.0 RC in the next few weeks.

**Comment by kelseyhightower** [comment]
@sylus I'm going to cut some binaries of what I have on master so people can start testing things out.

**Comment by kelseyhightower** [comment]
@sylus I've cut some new binaries for testing here: https://github.com/kelseyhightower/confd/releases/tag/0.12.0-alpha1

**Comment by sylus** [comment]
Thank you so much! ^_^

Also many thanks for confd in general! It has really been of great help to me.
