### ISSUE TITLE
Documentation for Installing from Source

### ISSUE THREAD

**Issue by jbkc85** [kelseyhightower/confd#402]
Though the documentation says just run ```go build```, the following packages are still telling me I need to use ```go get``` prior to the build.  Am I doing something wrong here or is this in fact the necessary steps?

```bash
[/repositories/git/opensource/confd]$ go build
config.go:14:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/BurntSushi/toml (from $GOPATH)
confd.go:10:2: cannot find package "github.com/kelseyhightower/confd/backends" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/backends (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/backends (from $GOPATH)
confd.go:11:2: cannot find package "github.com/kelseyhightower/confd/log" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/log (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/log (from $GOPATH)
confd.go:12:2: cannot find package "github.com/kelseyhightower/confd/resource/template" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/resource/template (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/resource/template (from $GOPATH)
```

```bash
[/repositories/git/opensource/confd]$ ./build
Building confd...
config.go:14:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/BurntSushi/toml (from $GOPATH)
confd.go:10:2: cannot find package "github.com/kelseyhightower/confd/backends" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/backends (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/backends (from $GOPATH)
confd.go:11:2: cannot find package "github.com/kelseyhightower/confd/log" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/log (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/log (from $GOPATH)
confd.go:12:2: cannot find package "github.com/kelseyhightower/confd/resource/template" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/resource/template (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/resource/template (from $GOPATH)
```

If this is in fact the correct approach, could we add it to the documentation, the ./build script and/or perhaps the new Vendor subdirectory?  I know its pretty obvious on how to get the packages updated, but not having it in the build from source documentation lead me to think I was doing something wrong at first....might help others avoid the same suspicion (unless I am doing something wrong!).

**Comment by bacongobbler** [comment]
It doesn't look like you have `GO15VENDOREXPERIMENT=1` set. Which version of Go are you using?

**Comment by bacongobbler** [comment]
after that `./build` is the way to go.

**Comment by jbkc85** [comment]
Doh, I forgot to include that...

```
[/repositories/git/opensource/confd]$ go version
go version go1.6 darwin/amd64
```

**Comment by bacongobbler** [comment]
Try this:

```
GO15VENDOREXPERIMENT=1 ./build
```

That should get you started :)

**Comment by jbkc85** [comment]
```
[/repositories/git/opensource/confd]$ export GOPATH=`pwd`
[/repositories/git/opensource/confd]$ GO15VENDOREXPERIMENT=1 ./build
Building confd...
config.go:14:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/BurntSushi/toml (from $GOPATH)
confd.go:10:2: cannot find package "github.com/kelseyhightower/confd/backends" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/backends (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/backends (from $GOPATH)
confd.go:11:2: cannot find package "github.com/kelseyhightower/confd/log" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/log (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/log (from $GOPATH)
confd.go:12:2: cannot find package "github.com/kelseyhightower/confd/resource/template" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/resource/template (from $GOROOT)
	/repositories/git/opensource/confd/src/github.com/kelseyhightower/confd/resource/template (from $GOPATH)
```

**Comment by bacongobbler** [comment]
huh. I wasn't able to reproduce this.

```
$ git status | head -n 1
On branch master
$ docker run -itv $PWD:/go/src/github.com/kelseyhightower/confd -w /go/src/github.com/kelseyhightower/confd golang:1.6 bash
Unable to find image 'golang:1.6' locally
1.6: Pulling from library/golang

Digest: sha256:bf9c6e96109d5b6db3789f5a2e93305481fb50485e34fac97eb28867aeaa8605
Status: Downloaded newer image for golang:1.6
root@b1ae684e5678:/go/src/github.com/kelseyhightower/confd# ./build 
Building confd...
root@b1ae684e5678:/go/src/github.com/kelseyhightower/confd# ./bin/confd --version
confd 0.12.0-dev
```

**Comment by jbkc85** [comment]
```
[~/repositories]$ docker run -itv /Users/jbkc85/repositories/confd:/go/src/github.com/kelseyhightower/confd -w /go/src/github.com/kelseyhightower/confd golang:1.6 bash
root@ac2f813505ac:/go/src/github.com/kelseyhightower/confd# ls
CHANGELOG		 Godeps       README.md  clean	    config_test.go  install	 node_var.go  vendor
CONTRIBUTING.md		 LICENSE      backends	 confd.go   contrib	    integration  resource     version.go
Dockerfile.build.alpine  MAINTAINERS  build	 config.go  docs	    log		 test
root@ac2f813505ac:/go/src/github.com/kelseyhightower/confd# export GOPATH=`pwd`
root@ac2f813505ac:/go/src/github.com/kelseyhightower/confd# ./build
Building confd...
config.go:14:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
	/go/src/github.com/kelseyhightower/confd/src/github.com/BurntSushi/toml (from $GOPATH)
confd.go:10:2: cannot find package "github.com/kelseyhightower/confd/backends" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/backends (from $GOROOT)
	/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/backends (from $GOPATH)
confd.go:11:2: cannot find package "github.com/kelseyhightower/confd/log" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/log (from $GOROOT)
	/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/log (from $GOPATH)
confd.go:12:2: cannot find package "github.com/kelseyhightower/confd/resource/template" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/resource/template (from $GOROOT)
	/go/src/github.com/kelseyhightower/confd/src/github.com/kelseyhightower/confd/resource/template (from $GOPATH
```

**Comment by jbkc85** [comment]
I made sure to do it through Docker to have the same environment :-)

**Comment by jbkc85** [comment]
oh, wow.  This was due to the fact i was running ```export GOPATH=`pwd````.  Why on earth would that happen?

**Comment by jbkc85** [comment]
Still doesn't work on basic MacOSX though:

```
[~/repositories/confd]$ git status | head -n1
# On branch master
[~/repositories/confd]$ go version
go version go1.6 darwin/amd64
[~/repositories/confd]$ echo $GOPATH

[~/repositories/confd]$ ./build
Building confd...
config.go:14:2: cannot find package "github.com/BurntSushi/toml" in any of:
	/usr/local/go/src/github.com/BurntSushi/toml (from $GOROOT)
	($GOPATH not set)
confd.go:10:2: cannot find package "github.com/kelseyhightower/confd/backends" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/backends (from $GOROOT)
	($GOPATH not set)
confd.go:11:2: cannot find package "github.com/kelseyhightower/confd/log" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/log (from $GOROOT)
	($GOPATH not set)
confd.go:12:2: cannot find package "github.com/kelseyhightower/confd/resource/template" in any of:
	/usr/local/go/src/github.com/kelseyhightower/confd/resource/template (from $GOROOT)
	($GOPATH not set)
```

And here through Docker, it works fine...

```
[~/repositories/confd]$ docker run -itv /Users/jbkc85/repositories/confd:/go/src/github.com/kelseyhightower/confd -w /go/src/github.com/kelseyhightower/confd golang:1.6 ./build
Building confd...
[~/repositories/confd]$ ls ./bin/
confd
```

**Comment by kelseyhightower** [comment]
@jbkc85 Sorry for the friction and it seems we need to clearly mark that confd require Go 1.6 to build from source. We are using the new support for the vendor directory and now that Go 1.6 has been released I want to target it.

**Comment by jbkc85** [comment]
@kelseyhightower no worries, but you actually already have it clearly marked that confd requires Go 1.6.  I have Go 1.6 installed on my Mac (freshly installed) and still got the issues from above...however when I use the Docker container that @bacongobbler used, it works perfectly fine.  It was very confusing to me (not to mention that also, when you use GOPATH=`pwd` in the Docker container, it messes it up too).  This might be a Go issue versus something of just Confd...I just wanted to point it out as I only have Confd to test against currently :-)

**Comment by HeavyHorst** [comment]
You need a directory structure like this: 
```
$GOPATH
|	src/
|	|	github.com/kelseyhightower/confd/
|	|	|	vendor/
|	|	|	|	...
```

It doesn't work if you have the confd folder elsewhere in your filesystem.
Thats also the reaseon why

```
root@ac2f813505ac:/go/src/github.com/kelseyhightower/confd# export GOPATH=`pwd`
```
doesn't work.

**Comment by jbkc85** [comment]
@HeavyHorst that would do it.  Thank you for the explanation!

I guess i was just thrown off by:

```
git clone https://github.com/kelseyhightower/confd.git
cd confd
go build
```

Which causes errors as seen above...Versus it being something like:

```
[~/go]$ go get github.com/kelseyhightower/confd
[~/go]$ go build github.com/kelseyhightower/confd
```

Once again, I am not sure if this is due to a setup with Go, but given I had the issues I wanted to raise them with you guys just in case.  Thank you for your patience and help walking me through it!

**Comment by jbkc85** [comment]
thanks everyone for helping on this one :-)

**Comment by nfantone** [comment]
@kelseyhightower  Why is this issue closed? This should _totally_ replace the misleading instructions on the `README.md` (which still end up in failure if you follow them).

If it weren't for this issue, I'd never have been able to install confd from source.

**Comment by bacongobbler** [comment]
@nfantone please feel free to open a PR with any proposed changes to the README.

**Comment by nfantone** [comment]
@bacongobbler Was afraid of this answer. As much as I'd like to, I am sorry, but I won't be doing that. For a variety of reasons:

1) I have absolutely no idea of `go`.  This is my first time running the tool. Ever.
2) I just found this thread and copy-paste my way out of installing.
3) I can't really say if this actually _are_ the real steps I should follow. As I said, I just run them as is.
4) No idea why they work or why they need to be like that.
5) No idea why instructions on the `README.md` don't work in the first place, either.

Please, correct me if I'm wrong, but you, on the other hand, being a collaborator, could just corroborate and write the proper instructions with _much_ less effort. And they would be much better written, I am sure. 

I'm sure you understand.

**Comment by jbkc85** [comment]
I actually closed this ticket because I figured that it was just a 'me' thing.  I went ahead and adjusted the README where I thought it needed to be adjusted, at least to what I had experienced while cloning/installing confd for myself.  Please feel free to adjust or ask questions where needed, otherwise im happy to contribute.

@nfantone - though I am sure you already know this, based on your last comment I would just like to share something.  I am also quite new when it comes to Go, and haven't really contributed to any Open Source project before.  That being said, this should never make you think that you can't contribute.  There are as you mentioned collaborators assigned to this project, who of course are writing the code and initial documentation, but people like you and I can easily come in and contribute to things like the README - in which they can review, adjust, and push to the master repo when they feel it is ready.  Never feel bad about a PR being rejected, edited, and feel fantastic about a 4 line commit that gets accepted.  Its all about the community and collaboration, and the more we have the better project we get :-).

**Comment by bacongobbler** [comment]
I just pushed https://github.com/kelseyhightower/confd/commit/6386163046ddad465498d6e002bd8e5ab3748365 which should help clarify things. Thanks @jbkc85 for your help!

**Comment by nfantone** [comment]
>  That being said, this should never make you think that you can't contribute.

@jbkc85 Don't misunderstand me: I'm with you on the sharing bit. I've contributed my fair share to open source projects in the past. I manage some of them myself, that are even published to `npm`. This is not bragging: anyone with an internet connection can do that. The thing is, I believe you mistook "open source" with "anyone can change things". Even you and I, by coming here and posting our comments in this issue are collaborating. Heck, it even ended in a PR and a change to the official docs! 

> Its all about the community and collaboration, and the more we have the better project we get :-).

This is part of the confusion. **More** does _not_ mean **better**. So you found out some `go` commands that worked for you. And you _did_ share it. That's awesome. Do you know what they imply? Do you know if those were the _right_ commands to type? Which versions were you using? What other system packages you had installed? How do you know if they just worked on _your environment_? If you _do_ know all of this, then great! Feel free to PR the confd guys. But, if not (which is my case, at least), I'd limit to opening and issue and/or write a comment. There are more qualified people out there who can write that piece of documentation far better than me.
