### ISSUE TITLE
children keys in toml files

### ISSUE THREAD

**Issue by muenchhausen** [kelseyhightower/confd#406]
I am trying gliderlabs/registrator with confd. I would like to clarify a detail for a CoreOS Meetup in Munich:

**Given:**
gliderlabs/registrator is writing all running Docker containers into etcd in the following structure:
`<prefix>/<containerName>/<serviceNameWithPort> : Value `

This list of running Containers is really cool and useful. We want to use it e.g. for a reverse proxy configuration :)

**When:**
I use the list of running containers in Template file - here a Apache httpd config file:
```
<Proxy balancer://examples>
{{range gets "/docker-services/docker_tomcatservice*-8080/*"}}
    {{$tomHost := index (split (base .Key) "_") 1}} 
	BalancerMember ajp://{{$tomHost}}:8009/examples route={{$tomHost}}
{{end}}
</Proxy>
```

**Then:**
I need to define all possible keys in the toml file:
```
keys = [
  "docker-services/docker_tomcatservice1-8080/registratorservice:docker_tomcatservice1_1:8080",
  "docker-services/docker_tomcatservice2-8080/registratorservice:docker_tomcatservice2_1:8080"
]
```

Which is not really beautiful, because I want to write a toml file that is independend of the count of registered containers.

Is there a better solution? Is it possible to track not just keys and values, but also children of keys? e.g.

```
keys = [
   "docker-services/*"
]
```

**Comment by HeavyHorst** [comment]
@muenchhausen

keys = [
   "docker-services"
]

will work.

**Comment by bacongobbler** [comment]
@HeavyHorst is right and this has been the case for a long time (probably since inception of the project IIRC). It's probably not made clear enough in the documentation, however.

See [this doc](https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md#create-template-resources) for an example.

**Comment by muenchhausen** [comment]
Simple. Cool. My thoughts were too complicated ;) 
Thanks for the quick reply!

**Comment by RichardBronosky** [comment]
Notice: You must know the first key to reach children!

That is to say, this works:
```
keys = [
"docker-services"
]
```

But this does not:
```
keys = [
"*"
]
```

Unfortunately, this forces you to wrap in a known parent, an otherwise top level object you want to iterate over. If anyone know an alternative, I'd love to hear it!
