### ISSUE TITLE
Multiple Backend Sources for same template?

### ISSUE THREAD

**Issue by fbrbovic** [kelseyhightower/confd#414]
Is it possible to have access to multiple backend sources for the same template?

For example  we have both Rancher metadata and vault, so in our configuration file we need access to both to be able to build the config file.

**Comment by bacongobbler** [comment]
there's no way to enable two backends at once, unfortunately.

**Comment by fbrbovic** [comment]
Having such capability is something that's definitely needed, especially when dealing with passwords, which you just don't want to be passing around unencrypted inside normal discovery service tools or as environment vars.

**Comment by michaellopez** [comment]
We have the same use case, Rancher + env or Rancher + vault. So +1 here :)

**Comment by bacongobbler** [comment]
@michaellopez would `{{ getenv "MY_ENVVAR" }}` work for you in tandem with the rancher backend? 

Having to support multiple backends on a single template is not something we'd likely implement as it would require an entire project re-architecture and quite a few backwards-incompatible changes for a single feature. confd currently works on a single backend for all templates, configured by a runtime option flag.

**Comment by michaellopez** [comment]
@bacongobbler Thanks for the info, I'll try it out and get back to you. I don't see how I missed that, I've read the docs a million times :)

Is there a possibility to run two instances of confd or two passes or similar to get around the need for multiple backends? Is there a recommended way to solve this?

**Comment by bacongobbler** [comment]
Running two instances of confd would just make one template overwrite the other. The recommended way to solve this would be to import all the keys from one backend to the other and just use that as the backend.

**Comment by fbrbovic** [comment]
Importing keys from one backend to another would not work in case of a Vault backend, since we are dealing with encrypted data, it would defeat the whole purpose if we had to expose the secrets.

**Comment by fbrbovic** [comment]
One option is to switch to Consul from Rancher meta data service and use Consul-Templates https://github.com/hashicorp/consul-template. It works similar to confd but reads from both consul and vault.   The only problem is now we need some kind of sync tool to sync up Rancher metadata to consul. 

There is also an open ticket in rancher for it's own secret management. Not sure if its moving anywhere.

**Comment by bacongobbler** [comment]
Yes, if you're consuming the entire hashicorp stack then it makes sense to use consul-template because it has intimate knowledge of those two backends. confd is backend-agnostic so it only works against a single backend at a time and uses it as a key/value store rather than a secret management tool.

**Comment by fbrbovic** [comment]
I really needed this feature for my own purposes so I ended up extending confd to support a 2nd backend of choice

Here is a pull request : https://github.com/kelseyhightower/confd/pull/417

**Comment by bacongobbler** [comment]
This is not something we are going to support due to the reasons stated [above](https://github.com/kelseyhightower/confd/issues/414#issuecomment-196913387). Closing!

**Comment by HeavyHorst** [comment]
I also needed this feature and came up with this: https://github.com/HeavyHorst/remco

**Comment by mellowplace** [comment]
In terms of configuration changes how about only allowing one backend to be configured via command line options but for multiple backends enable the following sort of toml config...

```TOML
confdir = "/etc/confd"
log-level = "debug"
interval = 600
noop = false

[[backend]]
type = "etcd"
client_cert = "/etc/confd/ssl/client.crt"
client_key = "/etc/confd/ssl/client.key"
nodes = [
  "http://127.0.0.1:4001",
]
prefix = "/production"
scheme = "https"
srv_domain = "etcd.example.com"

[[backend]]
type = "env"
prefix = "/production"
```

So basically move all the backend specific options into toml table array's

In terms of key collisions how about simply using a last key wins strategy?  So in the case of the above example environment vars override etcd values.

I'm not sure it would require huge amounts of rearchitecting that way as the backends can all still write into the same template store.

**Comment by hamza-tumturk** [comment]
If you want multiple backend feature, I recommend stop using confd, as they are not willing to change the way it works anyway. Just use [`remco`](https://github.com/HeavyHorst/remco) instead.

> remco is a lightweight configuration management tool. It's highly influenced by confd

> Multiple backends per template resource - get normal config values from etcd and secrets from vault

This is what we actually want, isn't it.
