### ISSUE TITLE
'ls' missed some keys

### ISSUE THREAD

**Issue by hex108** [kelseyhightower/confd#418]
I tested with etcd v2.3.0 and confd v0.11.0

Reproduce the problem with following steps:

**1.create some dirs in etcd**
   ./etcdctl setdir /test1
  ./etcdctl setdir /test2
  ./etcdctl setdir /test3

  ./etcdctl ls /
  /test1
  /test2
  /test3

**2.create config and templates**
$ cat conf.d/myconfig.toml
[template]
src = "myconfig.conf.tmpl"
dest = "/test/confd.out"
keys = [
    "/",
]

$ cat templates/myconfig.conf.tmpl
{{range ls "/"}}
{{.}}
{{end}}

**3.run confd**
$ ./confd-0.11.0-darwin-amd64 -onetime -confdir=$(pwd)/test_confd -log-level=debug
However there is no output in dest file confd.out

Could anyone help solve it please? Thanks!

**Comment by bacongobbler** [comment]
You need to set keys in those directories. confd only fetches keys from the backend, and the paths are interpreted from there. See https://github.com/kelseyhightower/confd/blob/6bb3c21a63459c3be340d53c4d3463397c8324c6/backends/etcd/client.go#L83-L101

**Comment by hex108** [comment]
Thanks @bacongobbler for explanation. I get it now.
