### ISSUE TITLE
Add support for whitespace trimming

### ISSUE THREAD

**Issue by pdelre** [kelseyhightower/confd#420]
While being new to confd and go templates, I've come across golang documentation regarding trailing (and preceding) whitespace. Most noticeably this comes in the form of new lines. The 0.11 release doesn't seem to support this feature and it leads to less readable templates as some configuration formats are whitespace sensitive.

> By default, all text between actions is copied verbatim when the template is executed. For example, the string " items are made of " in the example above appears on standard output when the program is run.

> However, to aid in formatting template source code, if an action's left delimiter (by default "{{") is followed immediately by a minus sign and ASCII space character ("{{- "), all trailing white space is trimmed from the immediately preceding text. Similarly, if the right delimiter ("}}") is preceded by a space and minus sign (" -}}"), all leading white space is trimmed from the immediately following text. In these trim markers, the ASCII space must be present; "{{-3}}" parses as an action containing the number -3.

<https://golang.org/pkg/text/template/#hdr-Text_and_spaces>

**Comment by HeavyHorst** [comment]
@pdelre You have to compile the source with go 1.6 or use one of the 0.12 pre-releases to use these feature. 

https://github.com/kelseyhightower/confd/releases

**Comment by pdelre** [comment]
Thank you for answering.
