### ISSUE TITLE
Suggestion: move to docker's libkv

### ISSUE THREAD

**Issue by odedlaz** [kelseyhightower/confd#426]
I stumbled upon a very cool library called [libkv](https://github.com/docker/libkv).
If we move to libkv, and donate our backend code to libkv, we can drop support to all the backends and make confd slimmer.

`libkv` provides a `Go` native library to store metadata.

The goal of `libkv` is to abstract common store operations for multiple distributed and/or local Key/Value store backends.

For example, you can use it to store your metadata or for service discovery to register machines and endpoints inside your cluster.

...

As of now, `libkv` offers support for `Consul`, `Etcd`, `Zookeeper` (**Distributed** store) and `BoltDB` (**Local** store).

**Comment by bacongobbler** [comment]
As long as we can make it all backwards compatible, I'm all for it.

**Comment by fruch** [comment]
:+1:
Does libkv also handle environment variables?

**Comment by okushchenko** [comment]
It looks like an unnecessary level of abstraction and is just not generic enough. Closing this one for now.
