### ISSUE TITLE
populate keys from environment variable

### ISSUE THREAD

**Issue by redr0bin** [kelseyhightower/confd#429]
Hi,
I'm trying to add a bit of dynamics to my confd configuration. I have n+1 environments where confd lives and reads conf values from etcd with prefix /conf/$ENV. I wanted to pass $ENV to confd conf and template to iterate over items, is it possible ?

**Comment by bacongobbler** [comment]
You can use a combination of `printf` and  `getenv` function to retrieve environment variables in your templates. See https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#getenv

**Comment by Linuxing** [comment]
@redr0bin 
this may help you: 
confd --confdir=/root/confd --onetime --backend etcd -node http://10.8.100.202:2379 --prefix=**$environment**
