### ISSUE TITLE
-configdir and -config-file not working as expected

### ISSUE THREAD

**Issue by micahlmartin** [kelseyhightower/confd#433]
I have a set of configuration files and templates in the following folder structure:

`/etc/confd/conf.d/<mode>/<*.toml>` - Confd configuration files only for the specific <mode> I'm running in.
`/etc/confd/templates/<*.tmpl>` - Shared template files

I have different configs I want to write based on different modes that my container is starting in (this is logstash btw). Some of the templates are shared between modes so I have them all in a common folder `/etc/conf.d/templates`. What I want to be able to do is this:

```
confd -onetime -backend env -confdir /etc/confd/conf.d/${MODE}
```

I would expect it to write build the files based on all of the configurations specified in `/etc/confd/conf.d/${MODE}` using the templates. This does not appear to be the case. This all of the output I get:

```
2016-04-13T12:13:34Z 29618e86e44e confd[51]: INFO Backend set to env
2016-04-13T12:13:34Z 29618e86e44e confd[51]: INFO Starting confd
2016-04-13T12:13:34Z 29618e86e44e confd[51]: INFO Backend nodes set to
2016-04-13T12:13:34Z 29618e86e44e confd[51]: DEBUG Loading template resources from confdir /etc/confd/conf.d/templates
```

Any ideas on what I'm doing wrong? Thanks!

**Comment by bacongobbler** [comment]
`confdir` is where the `conf.d` and `templates` directories exist. By default this is `/etc/confd`. If you want to set it up by environment, try something along this approach:

`/etc/confd/<mode>/conf.d/<*.toml>` - Confd configuration files only for the specific I'm running in.
`/etc/confd/templates/<*.tmpl>` - Shared template files

and to accomplish this:

```
mkdir -p /etc/confd/${MODE}
ln -sf /etc/confd/templates /etc/confd/${MODE}/templates
confd -onetime -backend env -confdir /etc/confd/${mode}
```

**Comment by micahlmartin** [comment]
That worked! Thanks.
