### ISSUE TITLE
Question, is there a way to have a condition on a variable?

### ISSUE THREAD

**Issue by tomer-ben-david** [kelseyhightower/confd#437]
I'm looking for something like:

```
{{ if eq getv "/datacenter" "mydc" }}
    {{ "we are in our dc!" }}
{{ else }}
    {{ "some default value" }}
{{ end }}
```

but its not working i'm just guessing here the syntax... is there a syntax for conditioning?

thanks

**Comment by bacongobbler** [comment]
Try separating it in parentheses like `{{ if eq (getv "/datacenter") "mydc" }}`

**Comment by tomer-ben-david** [comment]
thanks indeed!
