### ISSUE TITLE
How to specify a default value to ```getenv```

### ISSUE THREAD

**Issue by rodlogic** [kelseyhightower/confd#441]

**Comment by bacongobbler** [comment]
`{{ or (getenv "HOSTNAME") "localhost" }}`

**Comment by mauricios** [comment]
For those who land here,  according to the documentation https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#getenv you can give a default value that will be returned if the key is not present:

```
{{ getenv "HOST_IP" "127.0.0.1" }}
```
