### ISSUE TITLE
How to compare env var with a string in Go tmpl

### ISSUE THREAD

**Issue by PavelPrischepa** [kelseyhightower/confd#444]
Is there any way to implement an expression like that
```
{{ if getenv "APP_ENV_TYPE" eq "dev" }}
        X-Robots-Tag: noindex, nofollow    
{{ end }}
```
So I need to compare env var with some string. Is it possible?

**Comment by bacongobbler** [comment]
`{{if (getenv "APP_ENV_TYPE") == " dev" }}`

**Comment by PavelPrischepa** [comment]
@bacongobbler Thank you very much!
