### ISSUE TITLE
High Network I/O

### ISSUE THREAD

**Issue by osterman** [kelseyhightower/confd#448]
Running `confd` 0.11.0, we've observed that in the span of about 2 days, the daemon has moved 3.5GB. On another server, in the span of 10 days it's moved 10GB. We see this across all machines in the cluster, so in aggregate it adds up to a lot of traffic for an insignificantly small  dataset.

This strange because:
- The keyspace (`/secrets/`) is seldom modified (only when we provision the cluster)
- The keys in `/secrets` are tiny (e.g. passwords) - about 1850 bytes, ~15 keys
- The poll `-interval` is set to `60` seconds
- The `-watch /secrets` flag is passed 

Here's our invocation of confd:

```
/usr/bin/confd -prefix=/secrets -interval=60 -node=http://10.21.100.206:2379 -watch
```

(10.21.100.206 is the `etcd` proxy running on container host)

Is this behavior normal?

Thanks!

**Comment by bacongobbler** [comment]
FYI specifying -interval with -watch is ignored: -interval is only uses for polling.

Considering that you're using -watch, I'd first check if that is what's causing high network i/o. It's a constantly open client connection to etcd, watching the entire keyspace vs. a polling interval where a client connection is established every 60 seconds.

**Comment by osterman** [comment]
ok, will try that and see if it makes a difference.
