### ISSUE TITLE
merge getv and getenv

### ISSUE THREAD

**Issue by yossipr** [kelseyhightower/confd#450]
why there is two type of "functions" getv and getenv. i like the idea that i can use single config file and change the backend to any kind of store. but what if i want to use env for my development and etcd or other kind of store for my production then i need to have two templates file and two .toml files one for env var and one for the other store. this is annoying and miss the beauty of templating mechanism.

**Comment by bacongobbler** [comment]
Just use `getv` with the env backend and you can use the same config file for both environments. Is there something wrong with that approach?

**Comment by bacongobbler** [comment]
`getenv` is used more formally as a way to reach certain environment variables not exposed in your backend like $HOST or $USER.

**Comment by yossipr** [comment]
getv doesnt work with env backend. i have config file with

command:
confd -onetime -backend env

{{ getv SRV_PORT }} dosnt work. error calling getv: key does not exist
{{ getenv SRV_PORT }} working good

**Comment by bacongobbler** [comment]
Use it as you would any other backend. `{{ getv "/srv/port" }}` should get you the value of $SRV_PORT.

See [the quick start guide](https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md) for more info.
