### ISSUE TITLE
Create only mode (no update)

### ISSUE THREAD

**Issue by rodlogic** [kelseyhightower/confd#451]
When using confd in a Docker image, it would be nice to use confd to generate the config files if the file(s) don't exist, but don't update them if they already exist.

This enables a couple of additional use cases. Say I have a Tomcat `server.xml` that is managed by confd:
1. as a sysadmin, I would like to provide my own custom `server.xml`. In this case, the sysadmin doesn't want confd to update `server.xml`.
2. as a sysadmin, I would like to have confd generate only the initial `server.xml` since I will be making further modifications and will be managing it on my own.

In both cases above, the sysadmin will launch the Docker container mapping `/my/own/server.xml` to `/tomcat/conf/server.xml` (`-v /my/own/server.xml:/tomcat/conf/server.xml`).

**Comment by bacongobbler** [comment]
You could just write this logic into your `check_cmd`. Would that work for you?
