### ISSUE TITLE
how to install after download

### ISSUE THREAD

**Issue by wbwangk** [kelseyhightower/confd#455]
sudo wget https://github.com/kelseyhightower/confd/releases/download/v0.11.0/confd-0.11.0-linux-amd64

and i get a file, file name is "confd-0.11.0-linux-amd64".  how to install ?

**Comment by bacongobbler** [comment]
Run `sudo mv confd-0.11.0-linux-amd64 /bin/confd` to move it to /bin, where it'll be available in your PATH.

**Comment by wbwangk** [comment]
@bacongobbler thank you.  i run comand: chmod a+x confd,  and it work.
