### ISSUE TITLE
start confd with two dest configure files

### ISSUE THREAD

**Issue by openxxs** [kelseyhightower/confd#461]
In general, Nginx configure is separate into two parts: nginx.conf with `include       /etc/nginx/conf.d/*`; some configure files in  /etc/nginx/conf.d/ to describe upstream and server. But we can only set one dest in toml file. I have to start two confd processes to generate two configure files.
Is there a plan to support more dest configure file in one confd process?

**Comment by bacongobbler** [comment]
hey there! This specific feature has been requested before in https://github.com/kelseyhightower/confd/issues/256 and has been shut down. I am closing this as a duplicate issue, but please feel free to voice your opinion on why this is necessary in #256. Thanks!
