### ISSUE TITLE
getv with empty default value ("") results in key does not exist error

### ISSUE THREAD

**Issue by jbye** [kelseyhightower/confd#466]
Example

`{{ getv "/newrelic/backend/license_key" "" }}`

> 2016-07-25T11:30:48Z 43ec477158f3 confd[11]: ERROR template: newrelic.yml.tmpl:16:19: executing "newrelic.yml.tmpl" at <getv "/newrelic/back...>: error calling getv: key does not exist: /newrelic/backend/license_key

**Comment by jbye** [comment]
See https://github.com/kelseyhightower/confd/blob/6bb3c21a63459c3be340d53c4d3463397c8324c6/vendor/github.com/kelseyhightower/memkv/store.go#L90

If the key was not found, an error is returned even if a default value was set to an empty string.

**Comment by koolay** [comment]
I have the same problem.

**Comment by bacongobbler** [comment]
clsoing in favour of https://github.com/kelseyhightower/confd/issues/219

**Comment by brandonto** [comment]
Your problem may be related to the answer I left here: https://github.com/kelseyhightower/confd/issues/464
