### ISSUE TITLE
Updates to Etcd String values don't trigger a watch

### ISSUE THREAD

**Issue by Mauricevanree** [kelseyhightower/confd#467]
Tried this in both 0.11.0 and 0.12.0-alpha3 and run into the same problem.

I set this key/value pair in Etcd:

`etcdctl --endpoint http://192.168.99.1:2379 set /proxy/backends/backend1/192.168.99.1 '{"Port":8082,"CompressionEnabled":"true"}'`

When I update the port as following, a watch is triggered:

`etcdctl --endpoint http://192.168.99.1:2379 set /proxy/backends/backend1/192.168.99.1 '{"Port":8083,"CompressionEnabled":"true"}'`

But when I update CompressionEnabled, no watch is triggered:

`etcdctl --endpoint http://192.168.99.1:2379 set /proxy/backends/backend1/192.168.99.1 '{"Port":8082,"CompressionEnabled":"false"}'`

**Comment by okushchenko** [comment]
I can't reproduce this issue with the latest release of confd. Closing it for now. Please, reopen if it's still present for you.
