### ISSUE TITLE
[Feature Request] {{if isvalue "/key" "value"}} {{if containsvalue "/key/*" "value"}}

### ISSUE THREAD

**Issue by blaggacao** [kelseyhightower/confd#469]
Situation:
Deploying host-specific config scripts for example for a metric gatherer, I'd like to make some code conditional on a flag's value. Well, querying it's existence is already possible with `{{if exists}}`, yet this feels somewhat incomplete.

Take:
- Rancher Server
- Service Type Labels: `io.rancher.appname=nginx` , `io.rancher.appname=postgres`

Want:
- conditional deploy of a metrics gatherer like:

```
{{ if containsvalue "/self/host/containers/*/services/*/labels/io.rancher.appname" "postgres"}}
# Read metrics from one or many postgresql servers
[[inputs.postgresql]]
  address = "host=localhost user= password= sslmode=disable dbname="
  # databases = ["app_production", "testing"]
{{ end }}
```

**Comment by okushchenko** [comment]
You can use builtin conditionals from Go text/template, e.g.
```
{{ if (eq (getv "/key") "value") }}
exists
{{ end }}
```
