### ISSUE TITLE
QUESTION: env backend key format

### ISSUE THREAD

**Issue by jwaldrip** [kelseyhightower/confd#473]
What is the key format for the `env` backend. I cannot get `getv` or `exists` to pick them up using the path format, or the actual key name.

**Comment by bacongobbler** [comment]
https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md#environment-variables

**Comment by jwaldrip** [comment]
@bacongobbler that's not suitable answer. Please try to better understand the question.

**Comment by bacongobbler** [comment]
@jwaldrip see https://github.com/kelseyhightower/confd/pull/474 for an example on the `env` backend format. Essentially where you'd have slashes for path delimiters, the `env` backend uses underscores.
