### ISSUE TITLE
Does template support to assign an array variable?

### ISSUE THREAD

**Issue by peixinchen** [kelseyhightower/confd#475]
I seek the document and the text/template, didn't get the solution.

**Comment by HeavyHorst** [comment]
Is jsonArray what you looking for ?



peixinchen <notifications@github.com> schrieb am Do., 18. Aug. 2016, 14:19:

**Comment by peixinchen** [comment]
Sorry, it didn't help me, I look for a template function like "Map" but its behavior more likes an array. I want to assign a array variable in the template, not get from the ectd or other backends.

However, give my appreciate completely.
