### ISSUE TITLE
getenv with defaults

### ISSUE THREAD

**Issue by geeknam** [kelseyhightower/confd#476]
According to this issue: https://github.com/kelseyhightower/confd/issues/441
The answer is: `{{ or (getenv "HOSTNAME") "localhost" }}`

According to the docs: https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#getenv
It should be `{{getenv "HOSTNAME" "localhost"}}`  --> this doesn't work

The error thrown is:`ERROR template: foo.conf.tmpl:87:9: executing "foo.conf.tmpl" at <getenv>: wrong number of args for getenv: want 1 got 2`

**Comment by HeavyHorst** [comment]
{{getenv "HOSTNAME" "localhost"}} should work. Which version of confd do
you use ?

Nam Ngo <notifications@github.com> schrieb am Mo., 22. Aug. 2016, 06:49:

**Comment by geeknam** [comment]
`[root@0daa3a805e08 /]# confd --version
confd 0.11.0
`

**Comment by HeavyHorst** [comment]
Can you try one of the 0.12 releases ? Should work then.

Nam Ngo <notifications@github.com> schrieb am Mo., 22. Aug. 2016, 07:01:

**Comment by Xall** [comment]
does not work with `confd 0.12.0-dev` (same error as above)

As a workaround I use 
```
{{ or (getenv "VAR") "defaultvalue" }}
```

**Comment by antoniobeyah** [comment]
Still an issue:

> [root@a34dd0107702 work]# confd -onetime -backend env
> 2017-06-05T16:59:09Z a34dd0107702 confd[99]: INFO Backend set to env
> 2017-06-05T16:59:09Z a34dd0107702 confd[99]: INFO Starting confd
> 2017-06-05T16:59:09Z a34dd0107702 confd[99]: INFO Backend nodes set to
> 2017-06-05T16:59:09Z a34dd0107702 confd[99]: ERROR template: BoxConfig.properties.tmpl:18:23: executing "BoxConfig.properties.tmpl" at <getenv>: wrong number of args for getenv: want 1 got 2
> [root@a34dd0107702 work]# vi /etc/confd/templates/BoxConfig.properties.tmpl
> [root@a34dd0107702 work]# confd --version
> confd 0.11.0

`BoxConfig:18`
> internalAudit={{ getenv "BOX_ENABLE_INTERNAL_AUDIT" "true" }}

Still an issue with `v0.12.0-alpha3`:

> [root@a34dd0107702 work]# curl -L -o /usr/local/bin/confd https://github.com/kelseyhightower/confd/releases/download/v0.12.0-alpha3/confd-0.12.0-alpha3-linux-amd64
> [root@a34dd0107702 work]# confd --version
> confd 0.12.0-dev
> [root@a34dd0107702 work]# confd -onetime -backend env
> 2017-06-05T17:09:18Z a34dd0107702 confd[122]: INFO Backend set to env
> 2017-06-05T17:09:18Z a34dd0107702 confd[122]: INFO Starting confd
> 2017-06-05T17:09:18Z a34dd0107702 confd[122]: INFO Backend nodes set to
> 2017-06-05T17:09:18Z a34dd0107702 confd[122]: ERROR template: BoxConfig.properties.tmpl:18:23: executing "BoxConfig.properties.tmpl" at <getenv>: wrong number of args for getenv: want 1 got 2
> 2017-06-05T17:09:18Z a34dd0107702 confd[122]: FATAL template: BoxConfig.properties.tmpl:18:23: executing "BoxConfig.properties.tmpl" at <getenv>: wrong number of args for getenv: want 1 got 2

**Comment by marcbachmann** [comment]
Defaults are working with v0.14.0. Thanks for your work.
