### ISSUE TITLE
How set cluster etcd config 

### ISSUE THREAD

**Issue by fjzhuozl** [kelseyhightower/confd#477]
how set cluster etcd config 
1.confd -interval 5 -node 192.168.14.215:2379,192.168.14.84:2379
2.confd -interval 5 -node 192.168.14.215:2379 -node 192.168.14.84:2379

`/usr/local/bin/confd[19]: FATAL cannot connect to etcd cluster: 192.168.14.215:2379;192.168.14.84:2379
`

**Comment by HeavyHorst** [comment]
confd -interval 5 -node http://192.168.14.215:2379 -node
http://192.168.14.84:2379

fjzhuozl <notifications@github.com> schrieb am Do., 25. Aug. 2016, 10:38:

**Comment by fjzhuozl** [comment]
@HeavyHorst  thanks
