### ISSUE TITLE
rethinkdb backend

### ISSUE THREAD

**Issue by vikstrous** [kelseyhightower/confd#483]
I'm considering using confd with rethinkdb and I might try to implement a rethinkdb backend. Has anyone done this already? If I do this, would it be accepted upstream?

**Comment by bacongobbler** [comment]
closing as a duplicate of #414

**Comment by bacongobbler** [comment]
oops sorry meant a different issue :)

**Comment by bacongobbler** [comment]
yes this would be an accepted feature, however kelsey has been away from the helm for some time (see #460).
