### ISSUE TITLE
[Feature request] confd onetime forced reload

### ISSUE THREAD

**Issue by brandonto** [kelseyhightower/confd#490]
I'd like to request a 'forced' reload flag for onetime confd that ignores the watch list and reload the file, regardless of any changes to the data in the back end. If nobody has time, I can attempt to implement this feature... but I'd like to know if this is possible without any major refactor of the code base. I have no experience in writing Go however.

**Comment by bacongobbler** [comment]
how would one implement this while the process is running? By sending a signal to the process?

**Comment by brandonto** [comment]
Forgive my lack of understanding... I am not too familiar with now confd works. I need some clarification on your comment about the process that is running.

If you are referring to running processes that use the generated configuration files, I was under the impression that the infrastructure to reload such processes is already there, via 'reload_cmd' in the toml files.

If you are referring to the confd process itself. I may have a fundamental misunderstanding of confd. I thought that running confd as a onetime does not daemonize it.


It occurred to me that my initial request may not be clear on what behaviour I need. Here is my use case:

I would like to 'force' confd running as a onetime process to generate the configuration files regardless of the list of keys watched for in the toml file. Meaning that even if a key is not listed in the toml file, I would like a flag to tell confd to generate the configuration file regardless (pulling the required data from the backend).

After this initial configuration file generation, I would then like to run confd as a daemonized process to watch for changes to the keys in the toml file, and reload the configuration files as required. Here is an example template file:

`
hostname = {{getv '/hostname'}}
data = {{getv '/foo/bar'}}
`

Currently, I can accomplish this by having two toml files, one watching all keys that I would use when running confd as a onetime process. i.e.

`
keys = [
    "/"
]
`

Then replacing the toml file with one that is watching only one key (in this case, only '/foo/bar') and running confd as a daemonized process. i.e.

`
keys = [
    "/foo/bar"
]
`

The idea is the only watch for changes in the key '/foo/bar' (ignoring changes in '/hostname' after the initial generation of configuration file.

I would like to accomplish this without the swapping of toml files in between running confd as a onetime and as a daemon because it seems like an ugly and hacky solution.

Does the currently architecture make this an easy task to implement?

**Comment by bacongobbler** [comment]
> It occurred to me that my initial request may not be clear on what behaviour I need. Here is my use case:

This is what I was looking for. Thanks!

At this point, there is no way to perform that function. The only solution I can think of is to have two separate confd processes: one that is a --onetime process that writes out the daemon's template file reading in from `/hostname`. For example:

`hostname = {{getv '/hostname'}} data = {{"{{"}}getv '/foo/bar'{{"}}"}}`

Then, point your daemon process to use this as the template file. You can then run the --onetime process at any point to update the hostname field and make the daemon process only listen on the `/foo/bar` keyspace for changes.

**Comment by brandonto** [comment]
Thanks Matthew!

Your solution is what I needed!

:)
