### ISSUE TITLE
nested range with different path is not possible

### ISSUE THREAD

**Issue by kiich** [kelseyhightower/confd#491]
Using confd 0.12.0-dev with template file like this (it's a crude and useless example i know):

```
{{range $firstloop := ls "/registry/namespaces"}}
{{range $secondloop := ls "/registry/services/spaces"}}
"found it"
{{end}}
{{end}}
```

I never see the message "found it" in the resulting file.
If i change the secondloop ls path to be the same/sub of firstloop path i.e.

```
{{range $firstloop := ls "/registry/namespaces"}}
{{range $secondloop := ls "/registry/namespaces/something"}}
"found it"
{{end}}
{{end}}
```

i do see the message "found it"
safe to say all the keys in paths involved exist. also note that using just "/registry" in secondloop ls also seems to work. i.e.

```
{{range $secondloop := ls "/registry"}}
```

So it's as if while we are in firstloop range, you can not do range on different path.

To put it in context, i wanted to use the above logic to first look for namespaces and then check if a service exist for that given namespace (for kubernetes related work i am doing)

**Comment by okushchenko** [comment]
You can't read Kubernetes data from Etcd since 1.6, closing this for now.
