### ISSUE TITLE
Possible bug in regards to Vault and Standby Redirect

### ISSUE THREAD

**Issue by cqcwillard** [kelseyhightower/confd#492]
So, I'm using the vault backend, and when I hit the primary vault node, everything works.  However, if confd hits the node that is in "standby mode" confd is reporting the error, "FATAL EOF" when attempting token authentication.  It appears to be a result of the 307 redirect that the standby uses to redirect the request to the active vault node.

**Comment by cpoole** [comment]
@cqcwillard update to the latest version of vault. It does request forwarding instead of the stupid 307 behavior. Much easier

**Comment by okushchenko** [comment]
This issue is not present with the latest version of Vault, closing.
