### ISSUE TITLE
how to specify multiple etcd nodes on command line

### ISSUE THREAD

**Issue by kiich** [kelseyhightower/confd#493]
Using confd 0.12.0-dev and i see that it looks like i can specify multiple nodes in the config file but i can not seem to be able to do the same from command line option of --node

this obviously works:
```
/opt/bin/confd -interval 5 -backend etcd -node=http://xxx.xxx.xxx.xxx:2379
```

i have tried:
```
/opt/bin/confd -interval 5 -backend etcd -node=http://xxx.xxx.xxx.xxx:2379,http://yyy.yyy.yyy.yyy:2379
/opt/bin/confd -interval 5 -backend etcd -node="http://xxx.xxx.xxx.xxx:2379,http://yyy.yyy.yyy.yyy:2379"
/opt/bin/confd -interval 5 -backend etcd -node=[http://xxx.xxx.xxx.xxx:2379,http://yyy.yyy.yyy.yyy:2379]
/opt/bin/confd -interval 5 -backend etcd -node="[http://xxx.xxx.xxx.xxx:2379,http://yyy.yyy.yyy.yyy:2379]"
```

all of which gives me:
```
ERROR client: etcd cluster is unavailable or misconfigured
```

i didn't see anything in the doc but wanted to check i am doing something that is possible.

**Comment by HeavyHorst** [comment]
The following should work:

/opt/bin/confd -interval 5 -backend etcd -node http://xxx.xxx.xxx.xxx:2379
-node http://yyy.yyy.yyy.yyy:2379

kiich <notifications@github.com> schrieb am Fr., 14. Okt. 2016, 14:02:

**Comment by kiich** [comment]
@HeavyHorst Ah nice one! So simple when you know how :-)
Working great. thanks for the quick help.
