### ISSUE TITLE
Vault backend is not recursive

### ISSUE THREAD

**Issue by bmitch3020** [kelseyhightower/confd#494]
The vault backend calls `c.client.Logical().Read(key)` which will return items at that specific key, but not child keys. For that, I believe we need to also process the output of `c.client.Logical().List(key)`. Without the List, the conf.d/*.toml needs to identify each key you want to use in Vault and you can only iterate over multiple values of a single key, rather than multiple nested keys.

**Comment by bacongobbler** [comment]
@bmitch3020 if you wouldn't mind PR'ing the change along with relevant changes to the integration tests, that would be wonderful. :)

**Comment by bmitch3020** [comment]
I claim no expertise on on golang, but I'll take a swing at it.

**Comment by bmitch3020** [comment]
@bacongobbler I'm running out of time to put together some proper tests, and I'm rather far from a decent go coder (but it looks like it's worth learning when things slow down). Below is a commit that I got to work in my own lab. If it's far enough along to deserve a PR, I'm happy to send that over.

https://github.com/kelseyhightower/confd/compare/master...bmitch3020:master
