### ISSUE TITLE
lookupIP doesn't distinguish between ipv4 and ipv6 addresses

### ISSUE THREAD

**Issue by mrkurt** [kelseyhightower/confd#501]
This is for an nginx config like this:

```
{{ range lookupIP "hostnamewithipv6.com" }}
server {{.}}:8080
{{end}}
```

ipv6 addresses blow it up because they're not wrapped in `[]`, and getting around it means checking the length of the returned IP, which is kind of gross.

**Comment by okushchenko** [comment]
Fixed in #684
