### ISSUE TITLE
confd don't support zookeeper cluster?

### ISSUE THREAD

**Issue by yinsl** [kelseyhightower/confd#503]
I have a three nodes zookeeper cluster. If the node that confd connected shutdown.confd will display:
Failed to connect to ip:port: dial tcp ip:port: connection refused
ip:port is the node what confd connected.

**Comment by okushchenko** [comment]
confd does support connecting to multiple nodes in Zookeeper. The issue you are experiencing looks like a failure to reconnect.

**Comment by okushchenko** [comment]
Closing it for now. Please, reopen if this issue is still present for you in the latest release of confd.
