### ISSUE TITLE
confd work with redis, and how to set a specify database?

### ISSUE THREAD

**Issue by ouewqa** [kelseyhightower/confd#504]
I can't  find a example of the confd config file that work with redis.

who can give me a example?

how to set redis auth
how to set redis db
more...

**Comment by bacongobbler** [comment]
Take a look at the [integration tests](https://github.com/kelseyhightower/confd/blob/master/integration/redis/test.sh) for redis. Let me know if you have any specific questions.

**Comment by koolay** [comment]
Is it supported to connect special db?

**Comment by bacongobbler** [comment]
I'm not sure what you mean by that. Can you provide a link or elaborate more on what you mean by "special db"?

**Comment by koolay** [comment]
127.0.0.1:6379/8

**Comment by HeavyHorst** [comment]
I looked at the redis code. Its not possible at the moment to specify a specific redis db.
But the redis client lib we are using supports it:
  - https://github.com/garyburd/redigo/blob/master/redis/conn.go#L112

To support this we may need to create a new flag. We could also add the database to the connection string (localhost:6379/4) for example.

**Comment by HeavyHorst** [comment]
@koolay I have created a pull request (#505).
Feel free to test it !
