### ISSUE TITLE
Accessing the "index" in a range

### ISSUE THREAD

**Issue by Synapse791** [kelseyhightower/confd#506]
I've had a look the docs and I can't find anything about accessing the index or count when in a range. Obviously you can access the Key but what about the index?

Template example (haproxy):
```
backend myapp
  {{range getvs "/myapp/servers/*"}}
  server myapp_{{$index}} {{.}}:80
  {{end}}
```

Desired output:
```
backend myapp
  server myapp_1 10.100.0.1:80
  server myapp_2 10.100.0.2:80
  server myapp_3 10.100.0.3:80
```

**Comment by bacongobbler** [comment]
Use `{{ range $idx, $server := getvs "/myapp/servers/*" }}`. It's defined in text/template

**Comment by Synapse791** [comment]
Thanks @bacongobbler, I must've been being blind!
