### ISSUE TITLE
handle several config files with one toml

### ISSUE THREAD

**Issue by yossipr** [kelseyhightower/confd#507]
I have several config files that has the same definition in toml file. For now i need to copy the same toml for each file.

toml:
[template]
src = config1.json.tmpl
dest = config1.json
keys= [/server/host]

it will be nice if i can use wildcard in the toml. it allow to use one toml for all configuration files.

toml:
[template]
src = config*.tmpl
dest = *.json
keys= [/server/host]

**Comment by roberterdin** [comment]
+1

**Comment by websitesca** [comment]
+1

**Comment by okushchenko** [comment]
Are these files always named with an incremented number? Otherwise, it would be really hard to match `src` to `dst` using a wildcard.

**Comment by siddarth7** [comment]
+1

**Comment by jmervine** [comment]
@okushchenko I know this is closed, but a suggestion that might make this work would be to only allow source and destination directories where source file name and destination file name must be identical, e.g.
```
[template]
src = path/to/src/
dest = path/to/dest/
key = [ "/server/host" ]
```

So this
```
path/to/src/foo.conf
path/to/src/bar.conf
```

Becomes a transformed 
```
path/to/dest/foo.conf
path/to/dest/bar.conf
```
