### ISSUE TITLE
bad character while parsing json

### ISSUE THREAD

**Issue by dmkorolcrt** [kelseyhightower/confd#509]
I have faced trouble when I was trying to get value from json.
When I am trying to get value from json  key with dash I get ERROR:  bad character U+002D '-'.
```
my json stored in etcd as testdata key:
{
  "Release": {
    "version": "1.0.0",
    "my_components": {
      "some-component": {
        "images": [
          "registry/myimage:baseline"
        ],
        "annotation": {}
      }
}
```
`{{$data := json (getv "/testdata")}} {{ (index $data.Release.my_components.some-component.images 0 ) }}`
With underscore symbol everything works fine.

**Comment by HeavyHorst** [comment]
This seems to be an restriction of the Go template parser/lexer. 

See also: https://github.com/spf13/hugo/issues/1474
 https://github.com/golang/go/issues/9685

**Comment by okushchenko** [comment]
Please, reopen if you'll find a way to fix this in confd.
