### ISSUE TITLE
Filesystem backend

### ISSUE THREAD

**Issue by chris-kolenko** [kelseyhightower/confd#510]
I noticed a PR which added the Filesystem backend. It's now gone?? 

Will this be coming back in the future? or has been removed permanently? 

Ta.

**Comment by bacongobbler** [comment]
It's available on my fork but not in master. Please feel free to re-PR the filesystem backend. See https://github.com/bacongobbler/confd/commit/0ee6a8eff3074ced5634b19d00b974e2812a1a68

**Comment by bacongobbler** [comment]
also https://github.com/bacongobbler/confd/commit/809b562149e8d472557b1a706c897cd2b15a03bb

closing as there's nothing actionable to do here; the question has been answered.
