### ISSUE TITLE
Question: security code review

### ISSUE THREAD

**Issue by chiel1980** [kelseyhightower/confd#512]
Hi,

Did you guys ever did a security review on your code by an external party?
And if yes, are you willing to share these results or can we find it back in some specifc commits?
We are scheduling a code review by an external security company and if you want, we would like to share these results with you/the community as feedback to improve the product (if anything has been found) :)

Michiel

**Comment by bacongobbler** [comment]
We have not performed an external security review on this project. If you're willing to foot the bill then that sounds great!
