### ISSUE TITLE
[Feature] Support to generate .env  from  template file ".env.example"

### ISSUE THREAD

**Issue by koolay** [kelseyhightower/confd#518]
To follow `twelve-factor` created by Heroku,  a lots of app using config file like (dotenv)  [https://github.com/bkeepers/dotenv] . 

Maybe **confd**  can also support generate file `.env` from template  `.env.example` or `.env.local`  .

**Comment by bacongobbler** [comment]
Not sure I fully understand the use case here. Would you mind explaining your use case and why this is necessary?

**Comment by koolay** [comment]
**example:**


file `.env.example`

```
DB_HOST=localhost
DB_USERNAME=root
DB_PASSWORD=prod
```

I  want just to  replace all values in file `.env.example`  from configuration source,  then save as a new file `.env`.


file `.env`:

```
DB_HOST=xx.xx.xx.xx
DB_USERNAME=root
DB_PASSWORD=dev
```


So don't need to write another complex resource file `.env.toml`,  template file `.env.tmpl`.

**Comment by okushchenko** [comment]
Why is it not practical for you to use a `.tmpl` template file to generate a config?
