### ISSUE TITLE
-watch flag doesn't work when using Vault backend

### ISSUE THREAD

**Issue by bikerdan** [kelseyhightower/confd#521]
I'm using Vault as my backend.  I have everything setup and it seems to work fine with the onetime flag.  When I switch it to -watch, it starts but just sits there...   I've let it sit for an hour and I've made changes to the key in the Vault.  As I said, it works fine with the onetime flag so I'm sure the template and config are not a problem.  I'm running Confd on MacOS Sierra and the Vault server is a remote server.  

Here is my command and the output:

confd -watch -backend vault -interval 5 -log-level debug -node http://xxx.xxx.xxx.xxx:8200 -auth-type token -auth-token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2017-01-09T17:30:33-07:00 dans-mbp.ad.mycompany.com confd[9289]: INFO Backend set to vault
2017-01-09T17:30:33-07:00 dans-mbp.ad.mycompany.com confd[9289]: INFO Starting confd
2017-01-09T17:30:33-07:00 dans-mbp.ad.mycompany.com confd[9289]: INFO Backend nodes set to http://xxx.xxx.xxx.xxx:8200
2017-01-09T17:30:33-07:00 dans-mbp.ad.mycompany.com confd[9289]: INFO Vault authentication backend set to token
2017-01-09T17:30:33-07:00 dans-mbp.ad.mycompany.com confd[9289]: DEBUG Loading template resources from confdir /etc/confd
2017-01-09T17:30:33-07:00 dans-mbp.ad.mycompany.com confd[9289]: DEBUG Found template: /etc/confd/conf.d/application.conf.toml
2017-01-09T17:30:33-07:00 dans-mbp.ad.mycompany.com confd[9289]: DEBUG Loading template resource from /etc/confd/conf.d/application.conf.toml

**Comment by criloz** [comment]
@bikerdan  vault it self dont support this kind of watch operation, you should store your secrets in vault, and your observable settings on consul or etcd.

from the hashicorp docs

> Please note that Vault does not support blocking queries. As a result, Consul Template will not immediately reload in the event a secret is changed as it does with Consul's key-value store. Consul Template will fetch a new secret at half the lease duration of the original secret. For example, most items in Vault's generic secret backend have a default 30 day lease. This means Consul Template will renew the secret every 15 days. As such, it is recommended that a smaller lease duration be used when generating the initial secret to force Consul Template to renew more often.

**Comment by bikerdan** [comment]
Does that really matter?  All that is needed is that Confd does a periodic check.  Some interval based frequency.  It doesn't have to be a real time update...

**Comment by bacongobbler** [comment]
If you want poll looping use the -interval flag.

**Comment by bikerdan** [comment]
Read the original post.  I did use the interval flag and it doesn't work.  Is the problem that I used the watch flag and the interval flag?

**Comment by bacongobbler** [comment]
Use one or the other. Can you point to which doc so we can update it?

**Comment by bacongobbler** [comment]
When I mean by "use one or the other", the first is for poll looping, and -watch is for watching. The -watch flag supersedes -interval. Watch is not supported for vault as @criloz mentioned, but on other backends it's an either/or.

**Comment by bikerdan** [comment]
I don't see it in the documentation here.  I may have seen it somewhere else.  I will comment if I find it.  I appreciate the help and will give it a try without the -watch flag.  Thanks for your help!
