### ISSUE TITLE
confd use only the first node of the nodes array with etcd backend

### ISSUE THREAD

**Issue by tuxalex** [kelseyhightower/confd#526]
Hi,
I would to use tow etcd nodes for one template so I have this confd.toml : 

```
backend = "etcd"
confdir = "/etc/confd"
nodes = [
    "http://192.168.8.95:4001", 
    "http://192.168.8.91:4001"
]
sheme = "http"
sync-only = true
log-level = "info"
interval = 10
debug = false
verbose = true
```

When I run confd, the output is :
```
2017-01-25T10:59:23Z 36d083eec58d /usr/sbin/confd[426]: INFO Backend set to etcd
2017-01-25T10:59:23Z 36d083eec58d /usr/sbin/confd[426]: INFO Starting confd
2017-01-25T10:59:23Z 36d083eec58d /usr/sbin/confd[426]: INFO Backend nodes set to http://192.168.8.91:4001, http://192.168.8.95:4001
```

But in my template, only the first one is used (192.168.8.91).

My template is correct because if I invert the IP address in the toml files only part of 192.168.8.95 are modified.

**Comment by HeavyHorst** [comment]
Are you trying to use 2 etcd nodes with different data and want all that data to be available in your template ?
That is not possible.

The nodes are only used by the etcd client for automatic failover. If one node dies the client automatically connects to the second node, which should store exactly the same data (same etcd cluster).

**Comment by tuxalex** [comment]
Yes it's 2 etcd nodes with different data for one templates. 
Ok thanks for this answer. I hadn't thought the nodes array it was for failover.
