### ISSUE TITLE
Project appears to be dead.. serious bugs with PRs that don't get merged..

### ISSUE THREAD

**Issue by colinmollenhour** [kelseyhightower/confd#529]
Maybe time to hand the project over to another maintainer or use the new approval system to let others merge some much-needed PRs and tag a new release with bug fixes?

**Comment by brandonto** [comment]
I second this. Kelsey seems to be actively working on other projects while ignoring this one. I think giving maintainers more rights to the repository will allow this project to flourish.

**Comment by mellowplace** [comment]
+1 - It's a great project but it's not had a release in a long time - I've been waiting for a getv with a default for ages https://github.com/kelseyhightower/confd/issues/219

**Comment by ValFadeev** [comment]
@mellowplace `getv` with default was actually released in https://github.com/kelseyhightower/confd/releases/tag/v0.12.0-alpha3

**Comment by martinbaillie** [comment]
I would also like to know the status on this project. I use it a lot with Rancher. I've also just added a PR to implement `-wait` option for the Rancher backend.

**Comment by okushchenko** [comment]
0.12.0 release is already here:
https://github.com/kelseyhightower/confd/releases/tag/v0.12.0
More PRs will be merged in the coming months.

**Comment by colinmollenhour** [comment]
Thanks, @okushchenko !
