### ISSUE TITLE
Add support for local dynamodb implementation (endpoint URL)

### ISSUE THREAD

**Issue by johnt337** [kelseyhightower/confd#530]
Recently while attempting to do some offline development with confd using http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html I realized it did not seem to be a supported option.

Is this something people would find useful?

**Comment by bacongobbler** [comment]
Set DYNAMODB_LOCAL in your environment and it'll use localhost.

PRs to improve this would be accepted, though keep in mind of #529.

**Comment by bacongobbler** [comment]
link: https://github.com/kelseyhightower/confd/blob/7ac1091ca77699f898d17a0680e5ed22c9bcfa17/backends/dynamodb/client.go#L24-L29

**Comment by johnt337** [comment]
Sweet! Thanks for pointing this out!!
