### ISSUE TITLE
Create multiple config rest files 

### ISSUE THREAD

**Issue by edagarli** [kelseyhightower/confd#534]
dest = "/etc/nginx/conf.d/{{radom}}.conf"  

{{radom}} that is a random value. 

e.g ：date or time

**Comment by edagarli** [comment]
dest = "/etc/nginx/conf.d/{{domain}}.conf"  

i have this need

**Comment by HeavyHorst** [comment]
Where should the value ```{{domain}}``` come from ? From the environment ?
