### ISSUE TITLE
it does not support etcdctl v3 ?

### ISSUE THREAD

**Issue by snipercy** [kelseyhightower/confd#536]
when i `export ETCDCTL_API=3`
i got errors: `ERROR 100: Key not found (/myapp) [16]`

and i set ETCDCTL_API=2 ，it works

**Comment by HeavyHorst** [comment]
There is a pull request open: #468

I suggest you to use the fork from @bacongobbler (https://github.com/bacongobbler/confd).
Etcdv3 support is included there.

**Comment by snipercy** [comment]
Thank you for the prompt reply
