### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by briandeheus** [kelseyhightower/confd#548]
Hello,

Is this project still actively developed? The last release was *one* year ago.

Thanks!

**Comment by HeavyHorst** [comment]
#529 No it's not actively developed anymore.

There is a fork where some of the open pull requests are merged: github.com/bacongobbler/confd

**Comment by briandeheus** [comment]
Thanks @HeavyHorst!

**Comment by andmos** [comment]
If the project is not actively developed, would it be an idea to write so in the `README`, alternatively link to the active fork? I am having some thoughts about using it - the parts I need are all in place but with the status of the project it becomes a gamble at the end of the day..
