### ISSUE TITLE
exists function failed

### ISSUE THREAD

**Issue by sylvainmouquet** [kelseyhightower/confd#554]
With confd version confd-0.11.0-linux-amd64

I push a key and in the toml file i add :
```
{{if exists "/app"}}
    value: {{getv "/app"}}
{{end}}
```
The condition "exists" fails even if the key exists

**Comment by HeavyHorst** [comment]
Which baking do you use?

**Comment by sylvainmouquet** [comment]
I use etcd backend

**Comment by HeavyHorst** [comment]
hm, I'm using this all the time and can't find a way to reproduce this.
Could you illustrate the precise steps leading to this error?

**Comment by sylvainmouquet** [comment]
Found! It was the keys variable in the toml file.
One question, if the .cfg.tmpl is updated without updates of etcd keys, confd dont regenerate the destination file. It's possible to force an update of confd or adding a check condition (last update time of the source file by example) ?

**Comment by HeavyHorst** [comment]
Unfortunately there is no possibility to reload confd unless through a complete restart. You can use the interval mode to re-generate all configuration files in a certain interval, and not just when changes to the data in the backend are discovered through an watch event.

But you can't use the watch mode if you use interval.

You could try: https://github.com/HeavyHorst/remco
With remco you could use interval and watch at the same time.
You can also reload remco with an SIGHUP signal.

**Comment by sylvainmouquet** [comment]
I have created a loop with a sleep and i call confd in the loop.

I close this post
