### ISSUE TITLE
[BUG] Confd could not update file against key/value changed in etcd(confd[25]: INFO Target config /etc/nginx/conf.d/default.conf out of sync)

### ISSUE THREAD

**Issue by regardfs** [kelseyhightower/confd#561]
I have a nginx config file: **default.conf** which is managed by **etcd** and **confd**, Normal access.log when sth was changed shows below: 
> confd[991]: INFO /etc/nginx/conf.d/default.conf has md5sum 85ccd17c5e41f19e148bd11e02ac7c82 should be 1c120b15e37a7f72acb8bffe91730344
confd[991]: INFO Target config /etc/nginx/conf.d/default.conf out of sync
confd[991]: INFO Target config /etc/nginx/conf.d/default.conf has been updated

but today i had met very a strange problem, confd could not update key from etcd, but  get " "(" " : empty character),thus **http:// ;**,  it should be **http://192.168.10.139:8080**, **path** in **getv {{getv "path"}}** is correct!
error logs:

> confd[677]: INFO Target config /etc/nginx/conf.d/default.conf out of sync
confd[677]: ERROR "2017/05/25 09:43:15 [emerg] 683#683: no host in upstream \"\" in /etc/nginx/conf.d/default.conf:58\nnginx: [emerg] no host in upstream \"\" in /etc/nginx/conf.d/default.conf:58\nnginx: configuration file /etc/nginx/nginx.conf test failed\n"
confd[677]: ERROR Config check failed: exit status 1
[nginx] waiting for confd to create initial [nginx] configuration...

so, I changed default.conf file, switch  " " to the right one by hand, then problem solved and never happen again.

I want to know how to trace this problem when happen again and what is the potential reason for this problem? Thanks a lot for all your effort that will make for this issue.

**Comment by regardfs** [comment]
@HeavyHorst :)

**Comment by regardfs** [comment]
Might anyone help me?
It happened again. : (

**Comment by regardfs** [comment]
@HeavyHorst, I found the bug!!!!
If i set nginx default.conf proxy to "proxy_pass http://;", it never update file and report error:

> 2017-05-26T04:35:38Z 39e7805e3c78 confd[25]: INFO /etc/nginx/conf.d/default.conf has md5sum b74d1108b3a9c87cab7faa8f2ab8782f should be ea53ad0b08c6f34667363a0d2569c262
2017-05-26T04:35:38Z 39e7805e3c78 confd[25]: INFO Target config /etc/nginx/conf.d/default.conf out of sync
2017-05-26T04:35:38Z 39e7805e3c78 confd[25]: ERROR "2017/05/26 04:35:38 [emerg] 584#584: invalid number of arguments in \"proxy_pass\" directive in /etc/nginx/conf.d/default.conf:14\nnginx: [emerg] invalid number of arguments in \"proxy_pass\" directive in /etc/nginx/conf.d/default.conf:14\nnginx: configuration file /etc/nginx/nginx.conf test failed\n"
2017-05-26T04:35:38Z 39e7805e3c78 confd[25]: ERROR Config check failed: exit status 1

**Comment by HeavyHorst** [comment]
@regardfs did you run the check command against your real destination config? 

Try to use {{.src}} instead of the final destination of the config to use the staged config file.

**Comment by HeavyHorst** [comment]
check_cmd = "nginx -t -c {{.src}}"  should work.

**Comment by regardfs** [comment]
@HeavyHorst 
It does not work in my scenario, cause I use nginx.conf and conf.d/default.conf, only check {{.src}} would fail cause it only have **server {}** content.

**Comment by regardfs** [comment]
@HeavyHorst For temp solution
I add a nginx.conf in /usr/local/etc/ and only include "/etc/nginx/conf.d/.default.conf*"
and check_cmd: nginx -t -c /usr/local/etc/nginx.conf for temp source file check
