### ISSUE TITLE
[Error] FATAL empty src template with Consul as backend

### ISSUE THREAD

**Issue by ChuckNg** [kelseyhightower/confd#573]
Hi, guys:
I met the following issue when i use consul as confd's backend.
the dir tree listed below:
./
|-conf.d
|     |-confd.toml
|     |-hosts.toml
|-templates
         |-hosts.conf.tmpl

the confd is configuration file for confd:

`backend = "consul"
confdir = "/home/confd/etc"
log-level = "debug"
onetime = false
interval = 15
nodes = [
    "http://ip1:8500",
    "http://ip2:8500",
]`

the hosts.toml:
`[template]
src = "hosts.conf.tmpl"
dest = "/tmp/hosts"
user = "confd"
keys = ["/test/master/hosts"]`

the template file:hosts.conf.tmpl
`[hosts]
{{getv "/test/master/hosts"}}`

Starting commandline:
confd -config-file="/home/confd/etc/conf.d/confd.toml"

I can get the key directly from consul webpage and api, but information remains "empty src template" after starting with confd commandline, is there syntax error in conf file or somewhere else went wrong?

**Comment by okushchenko** [comment]
It looks like your `hosts.conf.tmpl` file is located in `./` directory instead of `./templates` directory. Try moving it to `./templates` directory instead.

**Comment by ChuckNg** [comment]
Formatting mistake，has been put under templates, also try move to /etc/confd, use default config file setting, seems still doesn't work. @okushchenko

**Comment by okushchenko** [comment]
@ChuckNg I noticed that you have 2 config files (`confd.toml` and `hosts.toml`), but only 1 template file (`hosts.conf.tmpl`). This may be the source of your error, as confd expects each config to have a corresponding template.
