### ISSUE TITLE
Does the confd support Go1.8.1?

### ISSUE THREAD

**Issue by driftluo** [kelseyhightower/confd#575]
When i try to compile confd on Go1.8.1, the error is  as follows:
```
$ go build
# github.com/kelseyhightower/confd/resource/template
resource\template\util.go:49: undefined: syscall.Stat_t
resource\template\util.go:50: undefined: syscall.Stat_t
```

and I found the source code syscall found that the standard library did not release the Stat_t state.

So does it support 1.8.1?

**Comment by HeavyHorst** [comment]
Go 1.8 is supported but Windows is not.

漂流 <notifications@github.com> schrieb am Di., 4. Juli 2017, 05:18:

**Comment by driftluo** [comment]
@HeavyHorst I have seen # 434 branch support for the win platform, this branch has a merger plan? If I now want to use under the win confd, how can I to do it?

**Comment by HeavyHorst** [comment]
You can try this fork of confd: https://github.com/bacongobbler/confd

**Comment by driftluo** [comment]
So cool, I have compiled it successfully, thanks
