### ISSUE TITLE
Add template functions for the basic arithmetic operations

### ISSUE THREAD

**Issue by coder-hugo** [kelseyhightower/confd#576]
I'd like to be able to do some lightweight calculations within confd templates. This would be useful for my confd template for elasticsearch. The elasticsearch guys recommend to configure the option for the minimum amount of masters based on the rule: `(master_eligible_nodes / 2) + 1`
As I need a list of all master hosts anyway within the template it would be nice if I could use the length of this to calculate the value for the minimum amount of masters instead of passing an additional value to the template.
Especially for this case it's necessary to have a function for the integer division.

**Comment by slavniyteo** [comment]
There is a [Pull Request](https://github.com/kelseyhightower/confd/pull/515/files)
And [one more](https://github.com/kelseyhightower/confd/pull/564)
