### ISSUE TITLE
support for etcd3

### ISSUE THREAD

**Issue by xueyihan** [kelseyhightower/confd#586]
Does the latest version support etcd3? I always got "key not found".

**Comment by okushchenko** [comment]
No, it doesn't support etcdv3 at the moment. The support should be merged in the coming months. Feel free to follow #468 to be updated on the PR status.

**Comment by xueyihan** [comment]
thanks! i got a fork that supported it. waiting the update...

**Comment by okushchenko** [comment]
The 0.13.0 release of confd has support for etcdv3, as well as other fixes and improvements. You can download it here: https://github.com/kelseyhightower/confd/releases/tag/v0.13.0
