### ISSUE TITLE
Please support watching specific key

### ISSUE THREAD

**Issue by zyf0330** [kelseyhightower/confd#593]
When update multi key, I want to set a version and make confd watch it to apply change.

**Comment by zyf0330** [comment]
Thanks.
Because when I update many keys once, I don't want that server applies change before I finish.
But now I think I can do this with `check_cmd`.
At the same time, I have another question. Does `keys` in template mean those being watched or those can be accessed in template?

**Comment by okushchenko** [comment]
etcd backend will watch for all changes on a specified prefix via `--prefix`, but all changes, besides for these specified in `keys`, will be filtered out.

**Comment by zyf0330** [comment]
Will `prefix` in toml be applied as `--prefix` in confd command line option

**Comment by zyf0330** [comment]
And please see #592, I think it is a problem

**Comment by okushchenko** [comment]
yes, it will

**Comment by zyf0330** [comment]
Has another question.
If I want to set `keys` to all subkeys in `--prefix`, can I set a pattern like `*` to match?
I just don't want to set every key in `--prefix`

**Comment by okushchenko** [comment]
Use 
```
keys = [
  "/",
]
```

**Comment by zyf0330** [comment]
No, I cannot. Because I have close auto slash in my fork confd. 😂

**Comment by okushchenko** [comment]
You can prefix all of your keys with an additional prefix and then get that pefix in keys. But yeah, you are in a bad position 🙂

**Comment by zyf0330** [comment]
Of course I am. I must do like this temporally.
I think `keys` should be optional, and in this situation, all keys with `--prefix` are accepted.
And twice ask for put an eye on #592. Please

**Comment by okushchenko** [comment]
Sure, it's a bit tricky to correctly do the etcd package upgrade without affecting other dependencies, but I'll manage.

**Comment by zyf0330** [comment]
Actually that is the same experience as when I want to upgrade etcd, so I ask for your help. I am in trouble about how to manage Go dependency as a beginner.
Thanks.
