### ISSUE TITLE
Fatal error when missing parameters with SSM Parameter Store backend

### ISSUE THREAD

**Issue by gdw2** [kelseyhightower/confd#606]
I have a template that has defaults defined for each variable.  When I run confd with the 'env' backend, missing parameters are replaced with the defaults.  When I run with the ssm backend, I get the following fatal error:

```
2017-09-26T17:03:57Z eb75bd4829e5 confd[91]: FATAL ParameterNotFound: Parameter /prefix/test/host not found.
        status code: 400, request id: af3f5ecf-a2dc-11e7-a6ef-1d6619482473
```

I would expect no error and the parameters to be replaced with the defaults.

**Comment by okushchenko** [comment]
Can you share this template?

**Comment by gdw2** [comment]
Template:
```
[FOO]
host:       {{getv "/test/host"     "default"}}
```

Run with: `confd -onetime -prefix "prefix" -backend ssm`

**Comment by PeteE** [comment]
Any chance of this getting fixed?

**Comment by okushchenko** [comment]
I can only reproduce the error in case when there is no such prefix in the store at all, in which case it's expected to throw an error. Try extending the `keys` part of the confd config to a prefix with at least 1 key in it.
Should we change this behavior?

**Comment by gdw2** [comment]
I created the PR (referenced above).
