### ISSUE TITLE
build failed in alpine

### ISSUE THREAD

**Issue by vipcxj** [kelseyhightower/confd#609]
this is the error
Building confd...

/usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lpthread
/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared
collect2: error: ld returned 1 exit status

**Comment by okushchenko** [comment]
Looks like a linking error. Try building with CGO_ENABLED=0.

**Comment by nseyvet** [comment]
Same pb

> /usr/lib/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
> /usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
> /usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
> /usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lpthread
> /usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared
> collect2: error: ld returned 1 exit status

Using:
```
FROM alpine:3.6 as confd

ENV GOPATH /go

ENV CGO_ENABLED=0

RUN mkdir -p "$GOPATH/src/" "$GOPATH/bin" && chmod -R 777 "$GOPATH" && \
    mkdir -p /go/src/github.com/kelseyhightower/confd

RUN apk --update add unzip curl go bash && \
    ln -s /go/src/github.com/kelseyhightower/confd /app

WORKDIR /app

RUN curl -L https://github.com/kelseyhightower/confd/archive/v0.13.0.zip --output /tmp/confd.zip && \
    unzip -d /tmp/confd /tmp/confd.zip && \
    cp -r /tmp/confd/*/* /app && \
    rm -rf /tmp/confd* && \
    ./build

```
And 
`docker build -t confd .`

**Comment by okushchenko** [comment]
There is a knows problem with building Go code using a vanilla Alpine image. Try using this:
```
FROM golang:1.9-alpine

RUN mkdir -p /go/src/github.com/kelseyhightower/confd && \
  ln -s /go/src/github.com/kelseyhightower/confd /app

WORKDIR /app
```

```sh
docker build -t confd-build .
docker run -it --rm -v (PWD):/app -e "GOOS=linux" -e "GOARCH=amd64" -e "CGO_ENABLED=0" confd-build go build -ldflags="-s -w" -o bin/confd
```

**Comment by vipcxj** [comment]
@okushchenko I use golang:1.9.1-alpine3.6 instead, and success. It seems that the guide should be changed.

**Comment by okushchenko** [comment]
Yep, will fix soon. Thanks for reporting it!

**Comment by andy5995** [comment]
I had the same problem when compiling a C program with a vanilla Alpine image. Configure bailed with an error that the compiler couldn't create executables. Installing the `musl-dev` package fixed it.
