### ISSUE TITLE
v0.14 etcdv3 support for json fails

### ISSUE THREAD

**Issue by purefield** [kelseyhightower/confd#612]
When trying to extract node specs for templating using json fails.
The result is not JSON for ETCDv3. 
"The base server interface uses gRPC instead of JSON for increased efficiency."

To create a consul service entry from a kubernetes service spec one could do following on etcd v2:

```
{
"services": [ {{range $index, $ns := ls "/registry/services/specs"}}{{$servicePath := (print "/registry/services/specs/" $ns) }}{{range $index2, $name := ls $servicePath}}{{$nodePath := (print $servicePath "/" $name)}}{{$kv := json (getv $nodePath) }}{{$nodePort := (index $kv.spec.ports 0).nodePort }}{{if $nodePort}}
...
{{end}} ]
}
```
Here ```$kv := json (getv $nodePath) ``` will fail with ```confd[32686]: ERROR template: kube-services.json.tmpl:2:231: executing "kube-services.json.tmpl" at <json (getv $nodePath...>: error calling json: invalid character 'k' looking for beginning of value``` as the registry will return gRPC responses not JSON.

**Comment by felskrone** [comment]
A fix for this would be great :-)

Trying to do the same thing as @purefield 

```python
...
 29 {{ range $spec := getvs "/registry/services/endpoints/*/*" }}
 30 {{ $data := json $spec }}
 31 {{ if eq $data.apiVersion "v1" }}
...
```

But confd says nono:

```bash
2017-10-11T21:11:30+02:00 k8sproxy01 ./confd-0.13.0-linux-amd64[1825]: ERROR template: haproxy.tmpl:30:12: executing "haproxy.tmpl" at <json $spec>: error calling json: invalid character 'k' looking for beginning of value
```

**Comment by AndrewChubatiuk** [comment]
I've tested with etcd 3.3.1 and confd v0.15 
1. Added key-value pair to etcd
`ETCDCTL_API="3" ./etcdctl put /services/zookeeper/host2 '{"Id":"host2", "IP":"192.168.10.12", "attributes": [{"first": "whatever", "second": "same"}]}'`

2. Template
`
{{ range $hosts := getvs "/services/zookeeper/*" }}
   {{ $host := json $hosts }}
   {{ if eq $host.Id "host2" }}
      {{range $attribute := $host.attributes }}
         {{ print $attribute.first  }}
      {{ end }}
   {{ end }}
{{ end }}
`

3. Template configuration
`
[template]
mode = "0644"
src = "basic.conf.tmpl"
dest = "/tmp/confd-basic-test.conf"
keys = [
  "/",
]
`
4. `./confd --onetime --log-level debug --confdir ./integration/confdir --backend etcdv3 --node http://127.0.0.1:2379 --watch`
Everything works as expected

@purefield @felskrone 
Can you please share your steps to reproduce this issue?

**Comment by felskrone** [comment]
Unfortunately i can not. I "fixed" that problem by writing my own confd in python (for education purposes) and i dont have the old configuration available.

I can tell you the versions i had trouble with though:

etcd 3.2.6
confd 0.14

Hope that helps!

**Comment by hubo1016** [comment]
Is it a kubernetes change? Maybe kubernetes change the backend store format from JSON to protobuf when using etcdv3?

**Comment by okushchenko** [comment]
@hubo1016 nice one pointing it out. As per https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.6.md#warning-etcd-backup-strongly-recommended it's indeed a change in Kubrenetes that caused this regression. Starting from v1.6 data that is being stored in Etcd by Kubernetes is being encoded using Protobuf. It might be a good idea to add a template function, which will decode Protobuf encoded data, but that's out of the scope of this issue.

Closing the issue.

**Comment by mingfang** [comment]
I use confd to watch kubernetes resources in etcd.  
Is there a solution to this problem?

**Comment by okushchenko** [comment]
@mingfang the only solution that Is there is #649 you can check it out to see if it fits your use-case.
