### ISSUE TITLE
v0.14 consul runtime error

### ISSUE THREAD

**Issue by arstercz** [kelseyhightower/confd#620]
when I run confd v0.14 with consul, runtime error occurs:
```
# confd -onetime -backend consul -node localhost:8500 --log-level debug -watch                                      
2017-10-16T15:09:42+08:00 cz-test1 confd[11304]: INFO Backend set to consul
2017-10-16T15:09:42+08:00 cz-test1 confd[11304]: INFO Starting confd
2017-10-16T15:09:42+08:00 cz-test1 confd[11304]: INFO Backend source(s) set to localhost:8500
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c9230]

goroutine 1 [running]:
github.com/kelseyhightower/confd/backends/consul.New(0xc42020c790, 0x1, 0x1, 0xee85da, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kelseyhightower/confd/backends/consul/client.go:47 +0x130
github.com/kelseyhightower/confd/backends.New(0x0, 0x0, 0x0, 0x0, 0x7fffde91b834, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kelseyhightower/confd/backends/client.go:43 +0x805
main.main()
        /go/src/github.com/kelseyhightower/confd/confd.go:28 +0xb3
```
my system env:
```
DELL R720
    Hostname | cz-test1
      Uptime | 175 days,  4:55,  1 user,  load average: 0.00, 0.01, 0.00
    Platform | Linux
     Release | CentOS release 6.5 (Final)
      Kernel | 2.6.32-431.3.1.el6.x86_64
Architecture | CPU = 64-bit, OS = 64-bit
   Threading | NPTL 2.12
    Compiler | GNU CC version 4.4.7 20120313 (Red Hat 4.4.7-16).
     SELinux | Disabled
```
v0.13 is ok.

**Comment by sheb-gregor** [comment]
On ubuntu 16.04 a similar problem:

```
> $ ./confd -onetime -backend consul -node 127.0.0.1:8500
2017-10-18T17:45:41Z ubuntu-4gb-sgp1 ./confd[25953]: INFO Backend set to consul
2017-10-18T17:45:41Z ubuntu-4gb-sgp1 ./confd[25953]: INFO Starting confd
2017-10-18T17:45:41Z ubuntu-4gb-sgp1 ./confd[25953]: INFO Backend source(s) set to 127.0.0.1:8500
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c9230]

goroutine 1 [running]:
github.com/kelseyhightower/confd/backends/consul.New(0xc42018cc70, 0x1, 0x1, 0xee85da, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kelseyhightower/confd/backends/consul/client.go:47 +0x130
github.com/kelseyhightower/confd/backends.New(0x0, 0x0, 0x0, 0x0, 0x7fff4053d183, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kelseyhightower/confd/backends/client.go:43 +0x805
main.main()
        /go/src/github.com/kelseyhightower/confd/confd.go:28 +0xb3
```

**Comment by sseide** [comment]
Same problem on Ubuntu 14.04:
<pre>
2017-10-26T13:32:59Z dev /opt/confd/confd[15318]: INFO Backend set to consul
2017-10-26T13:32:59Z dev /opt/confd/confd[15318]: INFO Starting confd
2017-10-26T13:32:59Z dev /opt/confd/confd[15318]: INFO Backend source(s) set to 127.0.0.1:8500
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c9230]

goroutine 1 [running]:
github.com/kelseyhightower/confd/backends/consul.New(0xc4201c2ed0, 0x1, 0x1, 0xc420015120, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kelseyhightower/confd/backends/consul/client.go:47 +0x130
github.com/kelseyhightower/confd/backends.New(0xc42005a7b0, 0x22, 0x0, 0x0, 0xc420015100, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/kelseyhightower/confd/backends/client.go:43 +0x805
main.main()
        /go/src/github.com/kelseyhightower/confd/confd.go:28 +0xb3
</pre>

**Comment by errnoh** [comment]
Consul backend (client.go) tries to assign to `conf.HttpClient.Transport` while `conf.HttpClient` is nil.

`client, err := api.NewClient(conf)` call that happens after that assignment would populate `TLSClientConfig` for the transport, but only using `conf.TLSConfig` which is type `api.TLSConfig` and not `tls.Config` that consul backend is using.

Proper solution probably is to just change the whole tlsconfig population logic to:

```
        if cert != "" && key != "" {
                conf.TLSConfig.CertFile = cert
                conf.TLSConfig.KeyFile = key
        }
        if caCert != "" {
                conf.TLSConfig.CAFile = caCert
        }
```

And make sure that the TLS configuration work after that change as it should.

**Comment by okushchenko** [comment]
@errnoh feel free to open a PR with these changes.
