### ISSUE TITLE
[SOLVED] AWS SSM ParameterNotFound error

### ISSUE THREAD

**Issue by watsonta** [kelseyhightower/confd#621]
When using confd with the ssm backend, String parameters are found while SecureString parameters are not.

TOML file:
[template]
src = "security.properties.tmpl"
dest = "/usr/share/conf/security.properties"
keys = [
  "/mycompany.internal.encryption.key"
]

TMPL file (security.properties.tmpl):
mycompany.internal.encryption.key={{getv "/mycompany.internal.encryption.key"}}

SSM "SecureString" parameter:
/common/mycompany.internal.encryption.key (encrypted with "alias/ssm-micro-services" key)

KMS key "alias/ssm-micro-services":
Key Users => MicroServiceTaskRole

Docker container:
Alpine 3.6 with confd v0.14.0 running on ECS (Docker v17.03) with MicroServiceTaskRole

confd invocation:
confd -confdir /etc/confd/common -prefix /common -onetime -backend ssm

Result:
2017-10-18T20:38:40Z ab8660aa9fce confd[301]: ERROR ParameterNotFound: Parameter /common/mycompany.internal.encryption.key not found.

Alternative result:
When the parameter is switched to "String" (instead of SecureString), confd finds it just fine.

**Comment by watsonta** [comment]
Finally identified the problem. Confd does not seem to acquire the IAM role with the policy that grants access to ssm GetParameter action. Only got it to work after adding credentials in the .aws directory.

**Comment by watsonta** [comment]
So, it works on the base ECS instance without .aws credentials (by using the assigned IAM role), but not in an ECS task (with a comparable role). I think that would qualify as a bug.

**Comment by okushchenko** [comment]
@watsonta I'm using it with IAM role in AWS ECS just fine. Have you tried debugging the communication with AWS API from inside the container?

**Comment by watsonta** [comment]
Thanks for responding. It was entirely my fault. I had embedded AWS in the example project while I worked toward using an IAM role, and the I forgot about them. As soon as I removed them, it began working.

Tom
---

**Comment by okushchenko** [comment]
Glad it worked out for you. I'm closing this, for now, feel free to reopen.
