### ISSUE TITLE
Watch is not supported for backend redis

### ISSUE THREAD

**Issue by rhubard** [kelseyhightower/confd#626]
INFO Watch is not supported for backend redis. Exiting...

How can i solve it?

**Comment by okushchenko** [comment]
There is a PR to add watch support for Redis - #604. I expect it to be merged in the next version of confd. You can try using a forked version from that PR for now.

**Comment by rhubard** [comment]
OK，thank you！

When will the next version of confd be released?

**Comment by okushchenko** [comment]
I expect it to be released by the end of November, maybe sooner.

**Comment by rhubard** [comment]
I am looking forward to it ~
