### ISSUE TITLE
confd cannot watch change from etcdv3 when change kv one by one quickly 

### ISSUE THREAD

**Issue by zyf0330** [kelseyhightower/confd#629]
If I change etcdv3 kv one by one quickly, then confd won't get second change by watching, so won't execute reload_cmd.

**Comment by zyf0330** [comment]
My suggestion is, when watch a event, wait a few seconds and then start do changes. If there is new event, reset this timer.

**Comment by okushchenko** [comment]
Sounds good. Can you try yourself at implementing it?

**Comment by zyf0330** [comment]
Ok, I will try.

**Comment by zyf0330** [comment]
Because of change about reusing previous watch, this problem is fixed at the same time. But this feature can avoid frequent reloading in other hand.

**Comment by okushchenko** [comment]
Some people might actually want frequent reloading. Let's close this issue and have a discussion about whether the delay is actually needed in #634
