### ISSUE TITLE
Any suggestions on how to use confd as library

### ISSUE THREAD

**Issue by cyc115** [kelseyhightower/confd#632]
Would it be possible to embed confd and use it as a library to use some of it features? It would be nice to leverage some of the configuration templating features without having to ship a separate confd binary.

**Comment by okushchenko** [comment]
You could try but it wasn't made for that use case. I don't even know where you should start if you want to make it a library. You can start looking from here 
https://github.com/kelseyhightower/confd/blob/f288e72608e4916dee0a24cd544521f84d968bc2/resource/template/resource.go#L336-L355 and analyze the codebase along the way.
