### ISSUE TITLE
Add digests of releases

### ISSUE THREAD

**Issue by autostatic** [kelseyhightower/confd#633]
Dear all,

Would it be possible to add digests of the releases on the releases page for basic file verification? Preferably SHA256 digests. Thanks in advance!

Best,

Jeremy

**Comment by okushchenko** [comment]
I've added the checksums to the latest release https://github.com/kelseyhightower/confd/releases/tag/v0.14.0

**Comment by autostatic** [comment]
Awesome, thanks!!
