### ISSUE TITLE
arm64 binary distribution for confd

### ISSUE THREAD

**Issue by vielmetti** [kelseyhightower/confd#641]
what I saw: confd 0.14.0 ships with amd64 binaries for Darwin, Linux, Windows.

what I expected to see: confd also ships with arm64 binaries for Linux.

impact: a Packet customer noted this missing artifact last night, and inquired about it.

Happy to provide test infra as part of the Works on Arm cluster project.

**Comment by vielmetti** [comment]
By inspection this looks like it would take a couple more lines in the Makefile at https://github.com/kelseyhightower/confd/blob/master/Makefile#L34

**Comment by okushchenko** [comment]
@vielmetti  Can you try to build it and test it on ARM hardware? I'll extend the Makefile and include the binary in the next release if everything works fine.

**Comment by vielmetti** [comment]
Will do @okushchenko !

**Comment by ErwanAliasr1** [comment]
We lack of confd on arm64 for ceph-container, can you build them please ?

**Comment by ErwanAliasr1** [comment]
@okushchenko This how we do the cross compilation on ceph-cn : https://github.com/ceph/cn/blob/master/Makefile

**Comment by okushchenko** [comment]
@ErwanAliasr1 I can build the binary, but I can't test if it actually works. Do you have some spare ARM hardware to test Confd on? I'll add the binaries in the next release if someone can confirm it actually works on arm64.
