### ISSUE TITLE
How to build confd.exe on win32 platform?

### ISSUE THREAD

**Issue by HeathKang** [kelseyhightower/confd#646]
I built confd.exe on win10 platform by 0.13.0 source code. But the reload function didn't work well. And showed error:
```ERROR exec  "/bin/sh": does not exist```
I thought maybe I made some mistakes on build configurations. 
Really need help to build confd.exe on win32 system without Docker.

**Comment by HeavyHorst** [comment]
The reload and check command is wrapped with /bin/sh to make command
substitution and such things work.

This doesn't work well on Windows.
You could try to run confd with cygwin until there is a better fix.

Heath Kang <notifications@github.com> schrieb am Di., 19. Dez. 2017, 08:30:

**Comment by okushchenko** [comment]
Fixed in #651
