### ISSUE TITLE
ERROR ParameterNotFound when using an ssm backend when parameter is only referenced in an "if exists" statement

### ISSUE THREAD

**Issue by lchisholmfp** [kelseyhightower/confd#652]
This behaviour is different from using backend env. I would expect the mentioned error to happen if you called getv and it doesn't exist, but if the getv is wrapped in an if exists I don't think this behavior is desiarable.

**Comment by gdw2** [comment]
@lchisholmfp , I'm not seeing this in 0.15.0 which was recently release.  Please try again...?

**Comment by okushchenko** [comment]
@lchisholmfp closing the issue for now. Please, reopen if the issue is still present for you.
