### ISSUE TITLE
What does the keys declaration do in the toml file?

### ISSUE THREAD

**Issue by grantcurell** [kelseyhightower/confd#659]
I'm working through my first confd-based container and I'm wrapping my head around everything. What does the keys declaration do as seen [here](https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#create-the-template-resource)?

In my case, I'm working through a Suricata configuration. In my suricata.yaml.tmpl file I have `{{getv "/home/net"}}`. Do I need to put:

```
keys = [
  "/home/net",
]
```

in my toml file?

**Comment by okushchenko** [comment]
`keys` specify what keys should be taken from the configured backend to render a template. Each key gets concatenated with a global prefix and fetched from a backend. Please, reopen if the answer is not clear enough.

**Comment by stolendog** [comment]
why do you need to list it in toml config file? why you can't get a list of keys from templates which you rendering?

**Comment by okushchenko** [comment]
@stolendog that's a valid point. The explicit declaration of keys is there to simplify the process of keys retrieval. It would be nice to implement an auto gathering of keys from templates, but it's out of scope for now.

**Comment by ehudkaldor** [comment]
what if  the key list is unknown before runtime?

**Comment by mhuisman** [comment]
Giving this a 👍 -- our keys are namespaced based on a number of deployment time specific variables (environment, customer, etc).  Creating a toml file for each template requires us to consider the toml file itself a template and build strange substitution scripts for those variables.  It seems like a re-implementation of what confd is for ☹️
