### ISSUE TITLE
Pass keys (from resource definition) to template

### ISSUE THREAD

**Issue by godefroi** [kelseyhightower/confd#666]
I have a set of configuration files that I need to write out. Each file uses an identical template, except for the key that is used to retrieve the data from Consul. Currently, I have to not only have a separate resource definition per output file (#256 would be super nice to have), I must have a separate template for each output file, even though they differ only in a single gets call. If instead, the value(s) of the `keys = [...]` from the resource was passed into the template, each of my output files could share a template.

**Comment by okushchenko** [comment]
Can you describe your use case in more details in #256. Closing this one for now, as the discussion will be held in #256
