### ISSUE TITLE
Maybe here stopChan is the correct thing to close

### ISSUE THREAD

**Issue by dunixd** [kelseyhightower/confd#679]
https://github.com/kelseyhightower/confd/blob/9b0ce8e6bb49eb46f27df33271e5edcc36a09746/confd.go#L63

**Comment by dunixd** [comment]
https://github.com/kelseyhightower/confd/blob/9b0ce8e6bb49eb46f27df33271e5edcc36a09746/confd.go#L41-L67

**Comment by okushchenko** [comment]
No, closing `doneChan` makes the last part of the select statement to trigger and `os.Exit(0)` to happen.
