### ISSUE TITLE
Why not return while err accord? Anything on purpose？

### ISSUE THREAD

**Issue by dunixd** [kelseyhightower/confd#680]
https://github.com/kelseyhightower/confd/blob/9b0ce8e6bb49eb46f27df33271e5edcc36a09746/resource/template/resource.go#L248

**Comment by dunixd** [comment]
https://github.com/kelseyhightower/confd/blob/9b0ce8e6bb49eb46f27df33271e5edcc36a09746/resource/template/resource.go#L237-L253

**Comment by okushchenko** [comment]
Sometimes the destination file doesn't exist, so `sameConfig` will return an error, but we still want to create and template a destination file afterward.
