### ISSUE TITLE
username/password authentication can't be supported by etcdv3 backend  

### ISSUE THREAD

**Issue by likeheng0519** [kelseyhightower/confd#695]
When I use etcd role based authentication at version3, I can access etcd with ectdctl like: ./etcdctl get --user root:rootpwd foo

but in confd when I start like: ./confd -onetime -backend etcdv3 -node http://127.0.0.1:2379 -username root -password rootpwd
there is a error below:
INFO Backend set to etcdv3
INFO Starting confd
ERROR etcdserver: user name is empty
FATAL etcdserver: user name is empty

Seems the username not take affect,
So my question is does confd support the etcdv3 user authentication? my confd version is confd-0.15.0

**Comment by hubo1016** [comment]
Looks like you must also specify `-basic-auth`, or the username and password do not take effect. Weird but that is how it works...

**Comment by hubo1016** [comment]
It works for me...  What is the exact configuration you are using (confd version, etcd version, options)?

If you are using TLS to connect to etcdv3, it is not possible to use username and password for authentication. You must put the username in Common Name of your client certification.

**Comment by likeheng0519** [comment]
Thanks, I use the latest verison confd and add -basic-auth, now it works. I will close this issue

**Comment by marcohelmerich** [comment]
> It works for me... What is the exact configuration you are using (confd version, etcd version, options)?
> 
> If you are using TLS to connect to etcdv3, it is not possible to use username and password for authentication. You must put the username in Common Name of your client certification.

This works fine. But why would one want such a strange behaviour and not give the user bei the username parameter?
