### ISSUE TITLE
thanks for this awesonme project , how cat  I  get the the values of prefix in etcd3 backend。

### ISSUE THREAD

**Issue by watersoona** [kelseyhightower/confd#698]
I  want to get  if  the values's count with prefix in etcdv3 .
I just learning go few days.  thanks .

**Comment by hubo1016** [comment]
If you are a beginner of GoTemplate, maybe you also need this document

https://golang.org/pkg/text/template/

There is a internal function "len" in GoTemplate, so you can use it like this:

```
{{ gets /myprefix/* | len }}
```

**Comment by yy-yangshengzhi** [comment]
does confd now support etcd v3?

**Comment by okushchenko** [comment]
@yy-yangshengzhi yes it does support etcdv3 as a separate backend. Just use a `-backend=etcdv3` option. Please, go and check it out.

**Comment by fengqieer1988** [comment]
> @yy-yangshengzhi yes it does support etcdv3 as a separate backend. Just use a `-backend=etcdv3` option. Please, go and check it out.

it works，thanks
