### ISSUE TITLE
Can confd work as j2 template?

### ISSUE THREAD

**Issue by ozbillwang** [kelseyhightower/confd#701]
I used to run j2 cli to convert some environment variables in a j2 template

    j2 config.j2 > /etc/nginx/nginx.conf

can we have similar feature in confd that I needn't take care of `/etc/confd/conf.d/myconfig.toml`?

    confd  -onetime -backend secretsmanager -input config.toml  -output /etc/nginx/nginx.conf

**Comment by okushchenko** [comment]
No, I don't think it would be a good idea to embed a jinja template processor in Confd. It's a deliberate design choice to keep the tool limited in features (e.g. only support Go's native text/template based templating language) to make it more robust.

**Comment by ozbillwang** [comment]
Thanks @hubo1016 

Are there any easy way in `confd` I can convert a template and output to nominate path directly with read secrets?
