### ISSUE TITLE
[question] Are there any ways to build "confd" with particular backends.

### ISSUE THREAD

**Issue by ozbillwang** [kelseyhightower/confd#706]
Normally I only use 2~3 backends, so I prefer to build confd with nominate backends only, such as

```
confd-ssm
confd-vault
confd-env
```

So are there any easy ways to do that?

or build and generate binary for each backend.

**Comment by okushchenko** [comment]
@ozbillwang no, it's not possible to do that at the moment. Why would you want to do that? Is the binary size your primary concern?

**Comment by ozbillwang** [comment]
binary size is about 32MB, it is fine.

When I run this small tool with `--help`, too many options, especially some options are only for particular backends. I am looking for a way to simplify it. 

Seems it is not a simple job to do that. Closed.
