### ISSUE TITLE
v0.16.0 issue

### ISSUE THREAD

**Issue by ro0p** [kelseyhightower/confd#712]
After upgrading to v0.16.0 I get "empty src template" error for my configs. v0.15.0 works fine.
In releases v0.15.0 size is 15Mb versus v0.16.0 size is 5Mb... Is it correct?

Thanks

**Comment by okushchenko** [comment]
@ro0p the size has changed because I've used the UPX to archive the executables, so it's not a problem. Can you share your config and exact steps to reproduce your issue?

**Comment by ro0p** [comment]
@okushchenko thank you for your answer and the clarification about the size.
Sorry about this, we had an error in our environment when I upgraded confd, and the template files were generated with wrong filenames.
My bad.

Thank you.

**Comment by okushchenko** [comment]
@ro0p I'm glad to hear that it worked for you in the end!
