### ISSUE TITLE
Does the backend "dynamodb" support credstash?

### ISSUE THREAD

**Issue by ozbillwang** [kelseyhightower/confd#714]
I am looking for the lookup tool for [credstash](https://github.com/fugue/credstash), and found `confd` do support to use backend `dynamodb`, similar as `credstash`.

But when run `confd -backend dynamodb`, it doesn't work directly.

Anyone can help?

By the way, does backend `dynamodb` support `secure string` by aws kms key currently?

**Comment by okushchenko** [comment]
In order for dynamodb backend to work, you will need to create a table of a specific format and then put key/value pairs in there. You can use this section of the dynamodb related integration script as a tutorial. https://github.com/kelseyhightower/confd/blob/master/integration/dynamodb/test.sh#L10-L19
