### ISSUE TITLE
macOS release 0.16.0 being flagged by VirusTotal

### ISSUE THREAD

**Issue by xdhmoore** [kelseyhightower/confd#721]
Maybe a false positive, but thought it was worth bringing up:

https://www.virustotal.com/#/file/2f919dc4c33eac98faf165226a5a5381ce8dc8445d0925ccd61f9cb1c01d4932/detection

**Comment by okushchenko** [comment]
@xdhmoore it looks like a false positive, considering the fact that only a single source suggests that it's infected. What do you think?

**Comment by xdhmoore** [comment]
I feel wary to offer an uninformed opinion, but I know these false positives are not uncommon. Just looking for some verification, I guess. Making sure someone's machine isn't compromised or trying to make an extra buck with adware or something.

Different genre of applications, but I used to be a heavy PortableApps user and I know they would see false positives sometimes. I think some antivirus vendors have a way to report false positives but idk about "Ikarus". Idk, maybe not worth the trouble.

Just thought I'd check.

**Comment by okushchenko** [comment]
@xdhmoore I've reported a false positive to Ikarus. Will keep this issue updated.

**Comment by okushchenko** [comment]
I received a reply from Ikarus Security Software:
> The false positive was removed and should not occur any more after our next database update.
> 
> This is an automatic generated e-mail, please do not reply.

Virus Total considers this file clean now. https://www.virustotal.com/#/file/2f919dc4c33eac98faf165226a5a5381ce8dc8445d0925ccd61f9cb1c01d4932/detection
