### ISSUE TITLE
Does confd  support multiple [template] configuration

### ISSUE THREAD

**Issue by sunsky-cn** [kelseyhightower/confd#723]
Does confd  support multiple [template] configuration
like :
[template]
src = "config.conf.tmpl"
dest = "/usr/local/nginx/conf/conf.d/upstream.conf"
keys = [
    "/nginx",
]
#check_cmd = "/usr/local/nginx/sbin/nginx -t -c /usr/local/nginx/conf/nginx.conf"
reload_cmd = "/local/nginx/sbin/nginx -s reload -c /usr/local/nginx/conf/nginx.conf"
[template2]
src = "config.conf22.tmpl"
dest = "/usr/local/nginx/conf/conf.d/upstream.conf-2"
keys = [
    "/nginx",
]
#check_cmd = "/usr/local/nginx/sbin/nginx -t -c /usr/local/nginx/conf/nginx.conf"
reload_cmd = "/local/nginx/sbin/nginx -s reload -c /usr/local/nginx/conf/nginx.conf"

**Comment by okushchenko** [comment]
@sunsky-cn no, not at the moment. You need to create a separate config file for each template.
