### ISSUE TITLE
【BUG】 bus error bug for confd-0.16-amd64

### ISSUE THREAD

**Issue by AIJIJI** [kelseyhightower/confd#729]
Hi, 
I've downloaded `confd-0.16.0-linux-amd64` and when I run `confd` it prints `Bus error (core dumped)` and I have no I idea how this happens because I cannot find log file anywhere. But after I download version `confd-0.15.0-linux-amd64`, it works properly so I guess it's a bug in the new version.
I'm using `Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.4.1708-Core`.
So where can I see the log file or what else can I do so I can get more informations of this bug?

**Comment by okushchenko** [comment]
@AIJIJI thanks for opening an issue! Can you share a docker image that I can run to reproduce this bug?

**Comment by AIJIJI** [comment]
@okushchenko  
Docker image at

`https://hub.docker.com/r/aiji/confd16_bug_report/`

Docker file at

`https://gist.github.com/AIJIJI/bdc7183aa488e98fe8137d4cfc898911`

Use 

`docker run -it aiji/confd16_bug_report /bin/bash`

to start the docker and run 

`/bin/confd`

then it returns

`Bus error (core dumped)`

**Comment by okushchenko** [comment]
The hash sums are different for the release binary and the binary in your docker image. The one in you docker image has a hash sum of `255d2559f3824dd64df059bdc533fd6b697c070db603c76aaf8d1d5e6b0cc334`, while the release one has a hash sum of `255d2559f3824dd64df059bdc533fd6b697c070db603c76aaf8d1d5e6b0cc334 `. Try redownloading the binary.

I've tested the release binary on `centos:centos7.4.1708` docker image and it works just fine.
