### ISSUE TITLE
Support for environment variables when processing templates

### ISSUE THREAD

**Issue by mentalblock** [kelseyhightower/confd#73]
It would be convenient if confd supported interpolation of templates by using values from environment variables. The following use cases would take advantage of this feature.
- Local development on a workstation which does not have a local etcd or consul available can make use of the confd templates. When a configuration service is available, one can switch to a confd configuration that will make use of it.
- Less time needed for setup and configuration if we just want testing of configuration templates. Iterating configuration templates will only require setting environment variables.

**Comment by bilalaslam** [comment]
:+1: on docs

**Comment by bacongobbler** [comment]
There's simple documentation at https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md#environment-variables

**Comment by linbynd** [comment]
In the documentation the example is using the "getv". For pulling Environment variables. use getenv.

Ex:
```sh
[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
keys = [
    "USER",
    "HOME",
]

[myconfig]
USER = {{getenv "USER"}}
HOME = {{getenv "HOME"}}
```
info in https://github.com/kelseyhightower/confd/blob/master/docs/templates.md

**Comment by duffqiu** [comment]
Can I use environment together with etcd something like fleet? because I wan to set etcd keys dynamically.

for example

[template]
src = "haproxy.cfg.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
keys = [
        "/${haproxy1}/apps/www/app1"
]
reload_cmd = "echo haproxy soft restarting"

**Comment by bacongobbler** [comment]
AFAIK you can't use environment variables in the toml files.

**Comment by duffqiu** [comment]
Can add this as a new feature?

**Comment by bacongobbler** [comment]
Sure :)

**Comment by duffqiu** [comment]
I am not a developer for go. But I try another workaround solution for that. First, I write a bash to support environment to generate the template in the folder of confd. and the confd can generate the configuration file for the applications such as haproxy. you can have a look at [confd-init](https://github.com/duffqiu/confd-init) if you are interesting in it.

**Comment by knepperjm** [comment]
Just found this.  <3 u Kelsey Hightower.
