### ISSUE TITLE
Could confd handle SIGCHLD signal to avoid zombies inside a Docker container?

### ISSUE THREAD

**Issue by budikaka** [kelseyhightower/confd#742]
Could confd handle SIGCHLD signal to avoid zombies inside a Docker container?

UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 02:28 ?        00:00:00 confd -config-file /usr/local/etc/confd/confd.toml -confdir /usr/local/etc/confd/
root        15     1  0 02:28 ?        00:00:00 /usr/sbin/rsyslogd
**root        27     1  0 02:28 ?        00:00:00 [haproxy]  < defunct>**
root        46     1  0 02:28 ?        00:00:00 haproxy -f /usr/local/etc/haproxy/haproxy.cfg -D -p /usr/local/etc/haproxy/pid -sf 27 -x /usr/local/etc/haproxy/socket
root        47     0  0 02:48 ?        00:00:00 bash
root        52    47  0 02:48 ?        00:00:00 ps -ef

**Comment by okushchenko** [comment]
@budikaka try using the `--init` command while running you containers, like this `docker run --init nginx`. It will start the init process inside of the container, which will perform all the necessary bookkeeping reserved to pid 1.
https://docs.docker.com/engine/reference/run/#specify-an-init-process

**Comment by budikaka** [comment]
@okushchenko That's work! Thanks!
