### ISSUE TITLE
Simple nested loop example

### ISSUE THREAD

**Issue by maxlock** [kelseyhightower/confd#746]
I'm trying to render data from the ssm backend. parameters are structured like this:

    /sensu/check/metrics_cpu/command "/opt/sensu/embedded/bin/metrics-cpu.rb"
    /sensu/check/metrics_cpu/handler "metrics"
    /sensu/check/metrics_cpu/interval 60
    /sensu/check/metrics_cpu/subscribers ["instance","container"]
    /sensu/check/metrics_cpu/type "metric"
    /sensu/check/metrics_disk/command "/opt/sensu/embedded/bin/metrics-disk.rb"
    /sensu/check/metrics_disk/handler "metrics"
    /sensu/check/metrics_disk/interval 300
    /sensu/check/metrics_disk/subscribers ["instance","container"]
    /sensu/check/metrics_disk/type "metric"

I'm trying to render something like this:

    check:
      metrics_cpu:
        command "/opt/sensu/embedded/bin/metrics-cpu.rb"
        handler "metrics"
    
I've got this far with the template:

    {{range $check := gets "/sensu/check/*/*" }}{{base (dir $check.Key)}}
    {{range $parm := gets $check.Key }}{{base $parm.Key}}: {{$parm.Value}}
    {{end}}
    {{end}}

but it doesn't seem to nest properly as the result is like this:

    metrics_cpu:
    command: "/opt/sensu/embedded/bin/metrics-cpu.rb"
    metrics_cpu:
    handler: "metrics"
    metrics_cpu:
    interval: 60

Are there any simple documented approaches to nested looping? I've found issue #62 but it doesn't help

Thanks.

**Comment by maxlock** [comment]
additionally issue #739 is possibly a dupe, I've looked at lsdir etc, but how can I concatenate a string from lsdir into a path to pass to range?
    {{range $check := lsdir "/sensu/check" }}
    {{range $parm := gets "/sensu/check/$check"}}
    {{.}}
    {{end}}
    {{end}}

**Comment by okushchenko** [comment]
First of all, are you using a StringList type for your list values? If so, confd's ssm backend doesn't fetch these from AWS SSM Parameter Store. You should convert these to strings, it might be the same thing just stored as a String type in AWS SSM Parameter Store.

As for the template, there are a couple of things you can do here:
1. Try to store the check name from the first loop in a variable and only render it in the second loop during the first iteration.
2. Store the whole set of key/values as a JSON object and use the [json](https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#json) templating function to decode and render them.

**Comment by maxlock** [comment]
Thanks @okushchenko I believe that the parameters are being sucessfully pulled from the parameter store as I'm able to see them all displayed in the debug output, additionally they are rendered by the template. I have initially stored the values as JSON, but there's a limit in ssm of 4096 characters which I could easily hit with the full amount of configuration I'm planning to store.

What really confused my, is that despite not being inside the inner loop, {{base (dir $check.Key)} is rendered every iteration. Additionally do you know how I can concatenate a string successfully?
Thanks! :)

**Comment by maxlock** [comment]
ok, I've figured out how to join strings with print

    {{range $check := lsdir "/sensu/check" }}{{ $check }}
    {{range $parm := gets (print "/sensu/check/" $check "/*" )}}{{ base $parm.Key }}: {{ $parm.Value }}
    {{end}}
    {{end}}

This works :)

    metrics_cpu
    command: "/opt/sensu/embedded/bin/metrics-cpu.rb"
    handler: "metrics"
    interval: 60
    subscribers: ["instance","container"]
    type: "metric"

    metrics_disk
    command: "/opt/sensu/embedded/bin/metrics-disk.rb"
    handler: "metrics"
    interval: 300
    subscribers: ["instance","container"]
    type: "metric"
