### ISSUE TITLE
redis with ip+port dial tcp: address redis://127.0.0.1:6379: too many colons in address

### ISSUE THREAD

**Issue by Zeg0** [kelseyhightower/confd#760]
This bug refers to https://github.com/hellofresh/janus/issues/86

When using redis backend with ip+port the Go-Language Dial function adds a trailing semicolon to the url causing the programm to shutdown. 

With new Go-Versions DialURL should be used instead.

$$ confd -onetime -backend redis -node 127.0.0.1:6379
confd[5893]: INFO Backend set to redis
confd[5893]: INFO Starting confd
confd[5893]: INFO Backend source(s) set to redis://127.0.0.1:6379
confd[5893]: DEBUG Redis Separator: "/"
confd[5893]: DEBUG Trying to connect to redis node redis://127.0.0.1:6379
confd[5893]: **FATAL dial tcp: address redis://127.0.0.1:6379: too many colons in address**

**Comment by d0ms0n** [comment]
try 
```
nodes = [
  "127.0.0.1:6379"
] 
```
instead of
```
nodes = [
  "redis://127.0.0.1:6379"
]
```
and it should work

**Comment by Zeg0** [comment]
> try
> 
> ```
> nodes = [
>   "127.0.0.1:6379"
> ] 
> ```
> 
> instead of
> 
> ```
> nodes = [
>   "redis://127.0.0.1:6379"
> ]
> ```
> 
> and it should work

It fixed the issue - thank you!
