### ISSUE TITLE
does `getvs` work with yaml list ???

### ISSUE THREAD

**Issue by pmunshi007** [kelseyhightower/confd#786]
I have set a yml file as confd backend. I have a yaml list to process something as below. 
    
     otherargs:
     - "-Xmx256m"
    -"-Xmn128m"

and trying to read the value from the list below.  As this is a list I am using getvs to get all values in string[] and join those with ',' .  Referring [join](https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#join).

      values : [ {{$args := getvs "/otherargs"}}
                     {{join $args ","}}]

Output I received is as below

     values : []

Here I am not getting the values from the yaml list via `getvs` .
As it is a list, the data should be collected via `getvs` but why I am receiving empty string I am not even getting single value here. so Does `getvs` work with yaml list? If yest then what am I missing here?

any help would be appreciated ?

**Comment by pmunshi007** [comment]
I also tried `range` functionality to get values received via `getvs` as below referring [getvs](https://github.com/kelseyhightower/confd/blob/master/docs/templates.md#getvs) 

   values :  [{{range getvs "/otherargs"}}
                      {{.}},
                      {{end}}]

but received same empty array as result. :(

**Comment by pmunshi007** [comment]
I found the solution from [here][1] I was trying to use `getvs` but the solution to this issue was `ls` command. Now I am able to populate this list from yml with below code.

     values :  [{{ $otherargs := ls "/otherargs" }}
                 "{{join $otherargs "\",\""}}"]

so final result, I received as below 

     values : ["-Xmx256m", "-Xmn128m"]

  [1]: https://github.com/kelseyhightower/confd/pull/397#issuecomment-188616839

**Comment by jinsiang2008** [comment]
Hey, which version are you using? looks like in 0.16.0, there is a but to use `ls` with yaml list. It will only return the index instead of the value.

**Comment by Albus** [comment]
```toml
[org/gnome/shell]
favorite-apps=['{{ join (getvs "/panel/apps/*") "','"}}']
```
