### ISSUE TITLE
confd should err instead of writing '<no value>' to templates when a key doesn't exist

### ISSUE THREAD

**Issue by carmstrong** [kelseyhightower/confd#82]
Currently, confd will write `<no value>` to a template in all places where a key is templated but there is no value in the store. This makes it hard to use confd in some cases - for example, [in Deis](https://github.com/deis/deis/blob/master/controller/bin/boot#L44-L49), we have to loop over the template file and wait until there are no instances of `<no value>`. Then, we continue standing up services because we know the file has been templated properly.

In my eyes, templating a key which doesn't exist is an error. Writing `<no value>` instead is too "nice" of a behavior. When confd returns 0, I expect to have a file that is fully templated. It is easy to conditionalize using an `if` statement for an optional key anyhow, so the user already has a method for making keys more or less optional.

I propose that the default behavior change to instead err and return a non-zero value when a template contains keys that don't exist in the store.

**Comment by sunfmin** [comment]
There is a option in Golang template for allowing this or not:

https://golang.org/pkg/text/template/#Template.Option
