### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mccricardo** [kelseyhightower/confd#833]
Judging for the lack of recent activity I would guess it's not being actively maintained. Is this the case? In case of an affirmative answer, can we add that to the top of the main README?

**Comment by huiser** [comment]
I migrated to https://github.com/HeavyHorst/remco

**Comment by mccricardo** [comment]
That's one of my options.

**Comment by mccricardo** [comment]
#813 asked the same.

**Comment by vvanpo** [comment]
https://groups.google.com/g/confd-users/c/t-hEIX1RPtA/m/gMnj1sn3BAAJ

> kelsey.h...@gmail.com Jun 22, 2020, 11:36:56 PM
> I was always afraid that maintaining so many backends would lead to this. I should have pushed harder on an external plugin model and kept the core simple. I would not be against a fork or transitioning this project to a neutral party under a new name.

**Comment by roopakv** [comment]
Would the maintainers be open to adding go module support otherwise i think this will be unreleasable via brew go1.17 onwards

**Comment by abtreece** [comment]
@roopakv, et al. 

All of the previously active maintainers have left and Kelsey is no longer interested in advancing confd (as noted above).
I have been intermittently pushing my fork of this project forward as we still use `confd` at Spreedly.

**Comment by mccricardo** [comment]
I'm closing this issue as it seems the project is **not** actively maintained.

**Comment by roopakv** [comment]
This will mean that we will probably remove this module from homebrew

**Comment by mccricardo** [comment]
I don't know if anyone has forked and started maintaining **confd**. I wouldn't mind doing it, together with at least a couple more people.

**Comment by thomas-mc-work** [comment]
I found this up2date fork:

https://github.com/abtreece/confd
