### ISSUE TITLE
Use confd with configuration folder outside /etc/confd for non root usage

### ISSUE THREAD

**Issue by krish0005** [kelseyhightower/confd#846]
Hi,

I need to use confd with a user that is not root and without sudo.
I cannot write the templates inside /etc/conf.d

Is it possible to use conf.d without being root or having sudo and write the templates in a custom folder of choice,
different from /etc/conf.d ? 

Thanks

**Comment by chandanpasunoori** [comment]
@krish0005  use can use `confd -confdir <directory>`, with following directory structure

```
<directory>/templates
<directory>/templates/template.conf.tmpl
<directory>/conf.d
<directory>/conf.d/template.toml
```

**Comment by krish0005** [comment]
> @krish0005 use can use `confd -confdir <directory>`, with following directory structure
> 
> ```
> <directory>/templates
> <directory>/templates/template.conf.tmpl
> <directory>/conf.d
> <directory>/conf.d/template.toml
> ```

thank you, i later found this https://github.com/kelseyhightower/confd/blob/master/docs/command-line-flags.md sorry.
