### ISSUE TITLE
Zookeeper Backend

### ISSUE THREAD

**Issue by mentalblock** [kelseyhightower/confd#89]
As the use of Docker containers for hosting applications on distributed clusters become more popular, the need for orchestrating these Docker containers are being met with projects such as Spotify's Helios and Apache Mesos.

Both of these cluster managers require Zookeeper to manage their cluster state and it would be really convenient if Confd supported Zookeeper as a backend. If Zookeeper was supported, it would preclude the need for me to run a separate key-value store such as etcd and Consul when using Helios or Mesos.

**Comment by ryzy** [comment]
Guys, any progress on that? Is anybody working on it?

**Comment by bacongobbler** [comment]
@ryzy #179
